"use client";

import { useState } from "react";
import type { Goal, Holding, Profile } from "../shared/workspace-implementations";

type Result={id:string;model_version:string;shared_path_fingerprint:string;coverage:{start:string;end:string;monthly_observations:number;symbols_simulated:string[]};outcomes:Array<{strategy_key:string;label:string;wealth_percentiles:Record<string,number>;real_wealth_percentiles:Record<string,number>;probability_of_loss:number;drawdown_percentiles:Record<string,number>;recovery_months:{median:number|null;unrecovered_share:number};goal_results:Array<{name:string;probability:number;median_shortfall:number}>;turnover:number;estimated_taxes:number|null;estimated_fees:number;concentration:{largest_weight:number;effective_holdings:number};regret:number;robustness:string}>;assumptions:string[];warnings:string[]};
const pct=(value?:number|null)=>value==null?"—":`${(value*100).toFixed(1)}%`;
const money=(value?:number|null)=>value==null?"—":new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);

export function DecisionLab({request,holdings,profile,goals=[]}:{request:(path:string,init?:RequestInit)=>Promise<Response>;holdings:Holding[];profile:Profile;goals?:Goal[]}){
  const [scenario,setScenario]=useState({economic_state:"unconditioned",inflation_state:"unconditioned",rate_state:"unconditioned",oil:false,credit:false});const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function run(){setBusy(true);setError("");try{const response=await request("/simulations/runs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({holdings,profile:{...profile,inflation_rate:profile.inflation_rate??.025},goals,scenario:{economic_state:scenario.economic_state,inflation_state:scenario.inflation_state,rate_state:scenario.rate_state,shocks:[scenario.oil?"oil":null,scenario.credit?"credit":null].filter(Boolean)},horizon_years:profile.horizon_years,paths:5000,block_months:6,seed:90210})});const body=await response.json();if(!response.ok)throw new Error(body.detail||"Decision Lab failed");setResult(body);}catch(reason){setError(reason instanceof Error?reason.message:"Decision Lab failed");}finally{setBusy(false);}}
  return <section className="decision-lab panel"><div className="panel-head"><div><span>Unified simulation engine</span><h3>Portfolio, macro, and goal Decision Lab</h3><p>All six choices run through the same 5,000 sampled market paths, so differences come from the strategy—not different random markets.</p></div><button className="primary" disabled={busy||!holdings.length} onClick={()=>void run()}>{busy?"Sampling common historical periods…":"Run Decision Lab"}</button></div>
    <div className="decision-lab-controls"><label>Economic state<select value={scenario.economic_state} onChange={event=>setScenario({...scenario,economic_state:event.target.value})}><option value="unconditioned">Any economic state</option><option value="expansion">Expansion</option><option value="slowdown">Slowdown</option><option value="recession">Recession</option></select></label><label>Inflation state<select value={scenario.inflation_state} onChange={event=>setScenario({...scenario,inflation_state:event.target.value})}><option value="unconditioned">Any inflation state</option><option value="cooling">Cooling</option><option value="stable">Stable</option><option value="accelerating">Accelerating</option></select></label><label>Rate state<select value={scenario.rate_state} onChange={event=>setScenario({...scenario,rate_state:event.target.value})}><option value="unconditioned">Any rate state</option><option value="easing">Easing</option><option value="stable">Stable</option><option value="tightening">Tightening</option></select></label><label className="check-row"><input type="checkbox" checked={scenario.oil} onChange={event=>setScenario({...scenario,oil:event.target.checked})}/>Oil shock</label><label className="check-row"><input type="checkbox" checked={scenario.credit} onChange={event=>setScenario({...scenario,credit:event.target.checked})}/>Credit shock</label></div>
    {error&&<div className="warning-strip"><span>{error}</span></div>}{result&&<><div className="decision-lab-audit"><span>{result.coverage.monthly_observations} common monthly observations</span><span>{result.coverage.start}–{result.coverage.end}</span><span>{goals.length} saved goal{goals.length===1?"":"s"} included</span><span>Paired paths {result.shared_path_fingerprint}</span><span>{result.model_version}</span></div><div className="decision-frontier-table"><div><b>Choice</b><b>Median wealth</b><b>Loss probability</b><b>Modeled drawdown</b><b>Turnover / tax</b><b>Robustness</b></div>{result.outcomes.map(row=><div key={row.strategy_key}><strong>{row.label}<small>{row.concentration.effective_holdings.toFixed(1)} effective holdings</small></strong><span>{money(row.wealth_percentiles.p50)}<small>Today’s dollars {money(row.real_wealth_percentiles?.p50)} · P10 {money(row.wealth_percentiles.p10)}</small>{row.goal_results.map(goal=><small key={goal.name}>{goal.name}: {pct(goal.probability)} attainment · {money(goal.median_shortfall)} median shortfall</small>)}</span><span>{pct(row.probability_of_loss)}</span><span>{pct(row.drawdown_percentiles.p10)}<small>Recovery median {row.recovery_months.median??"unavailable"} months</small></span><span>{pct(row.turnover)}<small>{money(row.estimated_taxes)} approximate tax · {money(row.estimated_fees)} fees</small></span><span>{row.robustness}<small>{money(row.regret)} median path regret</small></span></div>)}</div><details><summary>How the Decision Lab calculated this</summary>{result.assumptions.map(item=><p key={item}>{item}</p>)}{result.warnings.map(item=><p className="risk" key={item}>△ {item}</p>)}</details></>}
  </section>;
}
