from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal


MetricClass = Literal["SOURCE", "DERIVED", "MODEL", "UNAVAILABLE"]
StatusRole = Literal["CORE", "SUPPORTING", "INFORMATIONAL", "CONDITIONAL"]
ImplementationState = Literal["CURRENT", "DETERMINISTIC_WIRING", "MODEL_LOGIC", "CONTEXT_REQUIRED", "NEW_INGESTION"]


@dataclass(frozen=True)
class ResearchMetric:
    key: str
    section: str
    label: str
    classification: MetricClass
    source_tables: tuple[str, ...]
    source_columns: tuple[str, ...]
    providers: tuple[str, ...]
    formula: str
    required_inputs: tuple[str, ...]
    freshness_policy: str
    null_behavior: str
    evidence_type: str
    status_role: StatusRole
    implementation_state: ImplementationState
    current_path: str | None = None

    def payload(self) -> dict[str, object]:
        return asdict(self)


def metric(
    key: str, section: str, label: str, classification: MetricClass,
    tables: str, columns: str, providers: str, formula: str, inputs: str,
    freshness: str, null_behavior: str, evidence: str, role: StatusRole,
    state: ImplementationState, current_path: str | None = None,
) -> ResearchMetric:
    split = lambda value: tuple(item.strip() for item in value.split("|") if item.strip())
    return ResearchMetric(key, section, label, classification, split(tables), split(columns), split(providers),
                          formula, split(inputs), freshness, null_behavior, evidence, role, state, current_path)


MARKET_FRESH = "Current session when entitled; otherwise latest completed session, stale after 2 trading days."
FUND_FRESH = "Latest filed comparable period; stale after 120 days for quarterly issuers or 400 days for FY-only data."
NEWS_FRESH = "Rolling 30 days; stale when no qualifying article exists in 30 days."
EVENT_FRESH = "Future confirmed event; revalidate daily and mark stale after its scheduled time."
PORTFOLIO_FRESH = "Latest saved portfolio/read model; stale when holdings version or source prices advance."
NULL = "Return null and render the named UNAVAILABLE/PARTIAL state; never substitute zero or a neutral score."


REGISTRY: tuple[ResearchMetric, ...] = (
    # Top company header and chart.
    metric("header.ticker", "header", "Ticker", "SOURCE", "securities", "ticker", "security master", "Identity", "security", "Refresh with security master", NULL, "VERIFIED_FACT", "CORE", "CURRENT", "identity.ticker"),
    metric("header.company_name", "header", "Company name", "SOURCE", "securities|security_master", "company_name|name", "security master|Polygon reference", "Prefer verified security_master.name, fall back to securities.company_name", "security", "Refresh with security master", NULL, "VERIFIED_FACT", "CORE", "CURRENT", "identity.company"),
    metric("header.exchange", "header", "Exchange", "SOURCE", "security_master", "exchange", "Polygon reference", "Normalize MIC for display; XNAS→NASDAQ, XNYS→NYSE", "security_master.exchange", "Refresh with security master; stale after 30 days", NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", "identity.exchange"),
    metric("header.sector", "header", "Sector", "SOURCE", "securities|security_coverage_snapshots", "sector|classification.sector", "stored classification", "Latest verified classification", "security.sector", "Stale after 365 days", NULL, "VERIFIED_FACT", "CORE", "CURRENT", "identity.sector"),
    metric("header.industry", "header", "Industry", "SOURCE", "securities|security_coverage_snapshots", "industry|classification.industry", "stored classification", "Latest verified classification", "security.industry", "Stale after 365 days", NULL, "VERIFIED_FACT", "CORE", "CURRENT", "identity.industry"),
    metric("header.current_price", "header", "Current price", "SOURCE", "market_observations|price_bars", "value|adjusted_close|close", "Polygon snapshot|Polygon|Tiingo", "Prefer entitled snapshot; otherwise latest adjusted daily close", "price_history", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "CURRENT", "market.price"),
    metric("header.daily_change", "header", "Daily price change", "DERIVED", "price_bars", "adjusted_close|close", "Polygon|Tiingo", "P[t]/P[t-1]-1 using consecutive adjusted closes", "price_history", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "CURRENT", "market.daily_change"),
    metric("header.after_hours_change", "header", "After-hours change", "SOURCE", "market_observations", "metadata", "Polygon snapshot", "Requires regular-session close and entitled after-hours trade/snapshot", "after_hours_snapshot", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "INFORMATIONAL", "CURRENT", "market.after_hours_change"),
    metric("header.market_timestamp", "header", "Market timestamp", "SOURCE", "market_observations|price_bars", "observed_at|ts", "Polygon snapshot|Polygon|Tiingo", "Timestamp of selected price observation", "price_history", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "CURRENT", "market.as_of"),
    metric("header.market_delay", "header", "Market delay", "DERIVED", "market_observations|price_bars", "latency_class|entitlement|ts|fetched_at", "Polygon snapshot|Polygon|Tiingo", "Use latency_class when present; otherwise classify daily bars as end-of-day", "price_history", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "DETERMINISTIC_WIRING", "market.delay"),
    metric("header.market_cap", "header", "Market capitalization", "DERIVED", "price_bars|fundamental_periods", "close|metrics.shares_diluted", "Polygon|Tiingo|SEC", "Latest price × latest diluted shares", "price_history|fund.shares_diluted", MARKET_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", "identity.market_cap"),
    metric("header.employees", "header", "Employees", "SOURCE", "research_source_observations", "value_numeric", "Polygon reference", "Latest stored ticker-details employee count", "employees", "Annual reference refresh", NULL, "VERIFIED_FACT", "INFORMATIONAL", "CURRENT", "identity.employees"),
    metric("header.founded", "header", "Founded", "UNAVAILABLE", "", "", "", "No stored field", "founded", "Reference refresh", NULL, "VERIFIED_FACT", "INFORMATIONAL", "NEW_INGESTION", "identity.founded"),
    metric("header.headquarters", "header", "Headquarters", "UNAVAILABLE", "", "", "", "No stored field", "headquarters", "Annual filing/reference refresh", NULL, "VERIFIED_FACT", "INFORMATIONAL", "NEW_INGESTION", "identity.headquarters"),
    metric("header.price_history", "header", "Price chart", "SOURCE", "price_bars", "ts|adjusted_close|close", "Polygon|Tiingo", "Provider-adjusted daily closes filtered to selected range", "price_history", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "CURRENT", "market.history"),

    # Five-question strip.
    metric("summary.what_it_does", "summary", "What does it do?", "UNAVAILABLE", "documents", "business description/filing text", "SEC filing text", "One-line extract from sourced business description and segments", "business_description", "Latest 10-K/20-F", NULL, "VERIFIED_FACT", "CORE", "NEW_INGESTION", "identity.description"),
    metric("summary.improving", "summary", "Is it improving?", "DERIVED", "fundamental_periods", "metrics", "SEC", "Positive when aligned revenue growth>0 and at least one of gross/operating margin is non-declining; negative when revenue<0 or both margins contract; else mixed", "aligned_revenue|aligned_margins", FUND_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", "financial_health.trend_label"),
    metric("summary.cheap", "summary", "Is it cheap?", "DERIVED", "price_bars|fundamental_periods", "close|metrics", "Polygon|Tiingo|SEC", "Deterministic valuation read from supported current multiples versus history/peers", "valuation_read", MARKET_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", None),
    metric("summary.moves", "summary", "What moves it?", "MODEL", "market_events|documents|prediction_markets", "event/news evidence", "stored events|news|Kalshi|Polymarket", "Select highest-importance fresh company-specific catalyst with evidence; do not infer when no qualifying item", "catalyst_evidence", EVENT_FRESH, NULL, "OPINION", "SUPPORTING", "MODEL_LOGIC", "decision.key_catalyst"),
    metric("summary.breaks", "summary", "What breaks it?", "MODEL", "investment_theses|thesis_factors|documents", "breaker/risk evidence", "EagleEyes thesis model|news", "Select highest-severity evidence-linked breaker; prefer saved thesis breaker", "risk_evidence", FUND_FRESH, NULL, "OPINION", "SUPPORTING", "MODEL_LOGIC", "decision.primary_risk"),

    # Company overview families.
    metric("overview.business_description", "overview", "Business description", "UNAVAILABLE", "documents", "10-K Item 1 text", "SEC filing text", "Sourced concise extract; no unsupported generative completion", "business_description", "Latest 10-K/20-F", NULL, "VERIFIED_FACT", "CORE", "NEW_INGESTION", "overview.business_description"),
    metric("overview.segment.name", "overview", "Revenue segment name", "UNAVAILABLE", "documents", "segment note", "SEC filing text/XBRL dimensions", "Issuer-reported segment label", "segment_data", "Latest reported quarter/FY", NULL, "VERIFIED_FACT", "SUPPORTING", "NEW_INGESTION", None),
    metric("overview.segment.revenue_share", "overview", "Revenue segment share", "DERIVED", "fundamental_observations|documents", "segment revenue|total revenue", "SEC XBRL dimensions", "Segment revenue / consolidated revenue for same period", "segment_data|fund.revenue", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "NEW_INGESTION", None),
    metric("overview.segment.growth", "overview", "Revenue segment growth", "DERIVED", "fundamental_observations|documents", "segment revenue", "SEC XBRL dimensions", "Segment revenue current aligned period / prior-year aligned period - 1", "aligned_segment_data", FUND_FRESH, NULL, "VERIFIED_FACT", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("overview.geography.name", "overview", "Geography name", "UNAVAILABLE", "documents", "geographic note", "SEC filing text/XBRL dimensions", "Issuer-reported geography label", "geography_data", "Latest reported quarter/FY", NULL, "VERIFIED_FACT", "SUPPORTING", "NEW_INGESTION", None),
    metric("overview.geography.revenue_share", "overview", "Geographic revenue share", "DERIVED", "fundamental_observations|documents", "geographic revenue|total revenue", "SEC XBRL dimensions", "Geographic revenue / consolidated revenue for same period", "geography_data|fund.revenue", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "NEW_INGESTION", None),
    metric("overview.customer.name", "overview", "Material customer name", "UNAVAILABLE", "documents", "customer concentration note", "SEC filing text", "Display only explicitly disclosed customer name", "customer_data", "Latest 10-K/10-Q", NULL, "VERIFIED_FACT", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("overview.customer.revenue_share", "overview", "Customer concentration", "UNAVAILABLE", "documents", "customer concentration note", "SEC filing text", "Display disclosed percentage; do not infer customer identity", "customer_data", "Latest 10-K/10-Q", NULL, "VERIFIED_FACT", "SUPPORTING", "NEW_INGESTION", None),
    metric("overview.competitor", "overview", "Competitor", "DERIVED", "securities|security_memberships", "industry|membership", "stored classification", "Exact-industry active common stocks; exclude issuer and funds", "security.industry|peer_universe", "Classification stale after 365 days", NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", "overview.competitors"),
    metric("overview.peer_methodology", "overview", "Peer methodology", "DERIVED", "research read model", "comparable_valuation.basis", "EagleEyes", "Disclose deterministic exact-industry, minimum-sample, and outlier rules", "security.industry", "Versioned with research model", NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", "overview.peer_methodology"),

    # Financial health and charts.
    metric("financial.revenue_growth_yoy", "financial_health", "Revenue growth YoY", "DERIVED", "fundamental_periods", "metrics.revenue", "SEC", "Revenue[current] / revenue[same fiscal period prior year] - 1", "aligned_revenue", FUND_FRESH, NULL, "VERIFIED_FACT", "CORE", "CURRENT", "financial_health.revenue_growth"),
    metric("financial.revenue_trend", "financial_health", "Revenue acceleration", "DERIVED", "fundamental_periods", "metrics.revenue", "SEC", "Latest YoY growth minus preceding aligned YoY growth; >+2pp accelerating, <-2pp decelerating, else stable", "two_aligned_revenue_growths", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("financial.eps_growth_yoy", "financial_health", "EPS growth YoY", "DERIVED", "fundamental_periods", "metrics.eps_diluted", "SEC", "Diluted EPS[current] / diluted EPS[same fiscal period prior year] - 1 when prior EPS>0; otherwise percent growth unavailable and show values", "aligned_eps", FUND_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", "financial_health.eps_growth"),
    metric("financial.gross_margin", "financial_health", "Gross margin", "DERIVED", "fundamental_periods", "metrics.gross_profit|metrics.revenue", "SEC", "Gross profit / revenue for the same duration and period", "fund.gross_profit|fund.revenue", FUND_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", "financial_health.gross_margin"),
    metric("financial.gross_margin_change", "financial_health", "Gross margin change", "DERIVED", "fundamental_periods", "metrics.gross_profit|metrics.revenue", "SEC", "Current gross margin - prior-year aligned gross margin, in basis points", "aligned_gross_margin", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("financial.operating_margin", "financial_health", "Operating margin", "DERIVED", "fundamental_periods", "metrics.operating_income|metrics.revenue", "SEC", "Operating income / revenue for the same duration and period", "fund.operating_income|fund.revenue", FUND_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", "financial_health.operating_margin"),
    metric("financial.operating_margin_change", "financial_health", "Operating margin change", "DERIVED", "fundamental_periods", "metrics.operating_income|metrics.revenue", "SEC", "Current operating margin - prior-year aligned operating margin, in basis points", "aligned_operating_margin", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("financial.free_cash_flow", "financial_health", "Free cash flow", "DERIVED", "fundamental_periods", "metrics.operating_cash_flow|metrics.capex", "SEC", "Operating cash flow - capital expenditures for identical reporting duration; no mix of quarterly and YTD values", "fund.operating_cash_flow|fund.capex|period_duration", FUND_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", "financial_health.free_cash_flow"),
    metric("financial.fcf_margin", "financial_health", "FCF margin", "DERIVED", "fundamental_periods", "metrics.operating_cash_flow|metrics.capex|metrics.revenue", "SEC", "Free cash flow / revenue for identical duration", "free_cash_flow|fund.revenue", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("financial.cash", "financial_health", "Cash", "SOURCE", "fundamental_periods", "metrics.cash", "SEC", "Latest instant cash and equivalents", "fund.cash", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", "financial_health.cash"),
    metric("financial.debt", "financial_health", "Debt", "SOURCE", "fundamental_periods", "metrics.total_debt", "SEC", "Latest instant total debt", "fund.total_debt", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "CURRENT", "financial_health.debt"),
    metric("financial.net_cash_debt", "financial_health", "Net cash / net debt", "DERIVED", "fundamental_periods", "metrics.cash|metrics.total_debt", "SEC", "Cash - total debt; positive=net cash, negative=net debt", "fund.cash|fund.total_debt", FUND_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", None),
    metric("financial.share_count_change", "financial_health", "Share-count change", "DERIVED", "fundamental_periods", "metrics.shares_diluted", "SEC", "Diluted shares[current] / diluted shares[same fiscal period prior year] - 1", "aligned_shares", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", "financial_health.share_count_change"),
    metric("financial.roic", "financial_health", "ROIC", "UNAVAILABLE", "fundamental_periods", "operating income|tax expense|debt|equity|cash", "SEC", "NOPAT / average invested capital; tax expense/effective tax rate is not stored", "tax_expense", FUND_FRESH, NULL, "VERIFIED_FACT", "INFORMATIONAL", "NEW_INGESTION", "financial_health.roic"),
    metric("financial.chart.period", "financial_health", "Financial chart period", "SOURCE", "fundamental_periods", "period_end|fiscal_period|fiscal_year", "SEC", "Latest eight complete, non-duplicate comparable reported periods", "fundamental_periods", FUND_FRESH, NULL, "VERIFIED_FACT", "CORE", "CURRENT", "financial_health.periods"),
    metric("financial.chart.revenue", "financial_health", "Quarterly revenue series", "SOURCE", "fundamental_periods", "metrics.revenue", "SEC", "Reported revenue; exclude balance-sheet-only duplicate rows", "fund.revenue", FUND_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", None),
    metric("financial.chart.fcf", "financial_health", "Quarterly FCF series", "DERIVED", "fundamental_periods", "metrics.operating_cash_flow|metrics.capex", "SEC", "Operating cash flow - capex for each complete identical-duration period", "fund.operating_cash_flow|fund.capex|period_duration", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("financial.chart.gross_margin", "financial_health", "Gross-margin series", "DERIVED", "fundamental_periods", "metrics.gross_profit|metrics.revenue", "SEC", "Gross profit / revenue by complete period", "fund.gross_profit|fund.revenue", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("financial.chart.operating_margin", "financial_health", "Operating-margin series", "DERIVED", "fundamental_periods", "metrics.operating_income|metrics.revenue", "SEC", "Operating income / revenue by complete period", "fund.operating_income|fund.revenue", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", None),

    # Valuation.
    metric("valuation.pe_ttm", "valuation", "P/E TTM", "DERIVED", "price_bars|fundamental_periods", "close|metrics.eps_diluted", "Polygon|Tiingo|SEC", "Price / TTM diluted EPS; use FY EPS or sum four non-overlapping quarters", "price_history|ttm_eps", MARKET_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", None),
    metric("valuation.forward_pe", "valuation", "Forward P/E", "UNAVAILABLE", "", "", "consensus provider", "Price / provider consensus next-12-month EPS", "forward_eps", "Consensus stale after 7 days", NULL, "FORECAST", "SUPPORTING", "NEW_INGESTION", None),
    metric("valuation.peg", "valuation", "PEG", "UNAVAILABLE", "", "", "consensus provider", "Forward P/E / consensus long-term EPS growth percent", "forward_pe|long_term_eps_growth", "Consensus stale after 30 days", NULL, "FORECAST", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("valuation.price_to_sales", "valuation", "Price / sales", "DERIVED", "price_bars|fundamental_periods", "close|shares_diluted|revenue", "Polygon|Tiingo|SEC", "Market cap / TTM revenue", "market_cap|ttm_revenue", MARKET_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", None),
    metric("valuation.ev_ebitda", "valuation", "EV / EBITDA", "DERIVED", "price_bars|fundamental_periods|fundamental_dimensional_facts", "price|shares|debt|cash|D&A|operating_income", "Polygon|Tiingo|SEC", "Enterprise value / positive TTM EBITDA using extracted D&A", "price_history|shares|debt|cash|ttm_operating_income|ttm_da", FUND_FRESH, NULL, "VERIFIED_FACT", "INFORMATIONAL", "DETERMINISTIC_WIRING", None),
    metric("valuation.fcf_yield", "valuation", "FCF yield", "DERIVED", "price_bars|fundamental_periods", "close|shares_diluted|operating_cash_flow|capex", "Polygon|Tiingo|SEC", "TTM free cash flow / market cap", "ttm_fcf|market_cap", MARKET_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", None),
    metric("valuation.history_range", "valuation", "Five-year historical range", "DERIVED", "price_bars|fundamental_periods", "historical close|historical reported metric", "Polygon|Tiingo|SEC", "10th–90th percentile of point-in-time trailing multiple sampled monthly over five years", "price_5y|historical_fundamentals", "Recompute daily; require ≥24 monthly observations", NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("valuation.peer_median", "valuation", "Peer median", "DERIVED", "securities|price_bars|fundamental_periods", "industry|multiple inputs", "stored classification|Polygon|Tiingo|SEC", "Median current multiple across eligible same-industry peers; require ≥3", "peer_universe|peer_multiples", MARKET_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "DETERMINISTIC_WIRING", "valuation.peer"),
    metric("valuation.read", "valuation", "Valuation read", "DERIVED", "research read model", "current|history|peer", "EagleEyes", "Attractive ≤p25 and ≤peer−10%; in range p25–p75; slight premium ≤peer+15%; premium >peer+15%; rich >p90", "valuation_comparison", MARKET_FRESH, NULL, "VERIFIED_FACT", "CORE", "DETERMINISTIC_WIRING", None),
    metric("valuation.fair_value.bear", "valuation", "Bear fair value", "MODEL", "", "", "EagleEyes valuation model", "No approved fair-value model currently exists", "valuation_model", "Recalculate on price/fundamental/assumption change", NULL, "OPINION", "CONDITIONAL", "MODEL_LOGIC", "valuation.fair_value.bear"),
    metric("valuation.fair_value.base", "valuation", "Base fair value", "MODEL", "", "", "EagleEyes valuation model", "No approved fair-value model currently exists", "valuation_model", "Recalculate on price/fundamental/assumption change", NULL, "OPINION", "CONDITIONAL", "MODEL_LOGIC", "valuation.fair_value.base"),
    metric("valuation.fair_value.bull", "valuation", "Bull fair value", "MODEL", "", "", "EagleEyes valuation model", "No approved fair-value model currently exists", "valuation_model", "Recalculate on price/fundamental/assumption change", NULL, "OPINION", "CONDITIONAL", "MODEL_LOGIC", "valuation.fair_value.bull"),
    metric("valuation.fair_value.assumptions", "valuation", "Fair-value assumptions", "MODEL", "", "", "EagleEyes valuation model", "Versioned scenario assumptions; must accompany every output", "valuation_model", "Same timestamp as fair value", NULL, "OPINION", "CONDITIONAL", "MODEL_LOGIC", None),
    metric("valuation.implied_expectations", "valuation", "What the price assumes", "MODEL", "", "", "EagleEyes reverse-DCF", "Solve for growth/margin path equating discounted cash flows to enterprise value", "reverse_dcf_model", "Recalculate daily", NULL, "OPINION", "CONDITIONAL", "MODEL_LOGIC", "valuation.implied_expectations"),

    # Earnings and expectations.
    metric("earnings.estimate.period", "earnings", "Estimate period", "UNAVAILABLE", "", "", "consensus provider", "Provider fiscal period", "consensus_estimates", "Stale after 7 days", NULL, "FORECAST", "CORE", "NEW_INGESTION", None),
    metric("earnings.estimate.revenue", "earnings", "Consensus revenue", "UNAVAILABLE", "", "", "consensus provider", "Provider consensus", "consensus_estimates", "Stale after 7 days", NULL, "FORECAST", "CORE", "NEW_INGESTION", None),
    metric("earnings.estimate.eps", "earnings", "Consensus EPS", "UNAVAILABLE", "", "", "consensus provider", "Provider consensus", "consensus_estimates", "Stale after 7 days", NULL, "FORECAST", "CORE", "NEW_INGESTION", None),
    metric("earnings.estimate.revenue_revision", "earnings", "Revenue revision", "UNAVAILABLE", "", "", "consensus provider", "Current consensus / consensus 90 calendar days earlier - 1", "consensus_history", "Stale after 7 days", NULL, "FORECAST", "SUPPORTING", "NEW_INGESTION", "earnings.estimate_revisions"),
    metric("earnings.estimate.eps_revision", "earnings", "EPS revision", "UNAVAILABLE", "", "", "consensus provider", "Current consensus / consensus 90 calendar days earlier - 1", "consensus_history", "Stale after 7 days", NULL, "FORECAST", "SUPPORTING", "NEW_INGESTION", "earnings.estimate_revisions"),
    metric("earnings.next.date", "earnings", "Next earnings date", "UNAVAILABLE", "market_events", "starts_at|verified_at", "earnings calendar", "Nearest future confirmed earnings event", "earnings_event", EVENT_FRESH, NULL, "VERIFIED_FACT", "CORE", "NEW_INGESTION", None),
    metric("earnings.next.session", "earnings", "Before/after market", "UNAVAILABLE", "market_events", "metadata", "earnings calendar", "Provider-supplied session only", "earnings_event_session", EVENT_FRESH, NULL, "VERIFIED_FACT", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("earnings.next.days", "earnings", "Days until earnings", "DERIVED", "market_events", "starts_at", "earnings calendar", "ceil(event timestamp - now in days)", "earnings_event", EVENT_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "NEW_INGESTION", None),
    metric("earnings.next.expected_move", "earnings", "Options-implied expected move", "UNAVAILABLE", "", "", "options provider", "ATM straddle / spot, aligned to first expiry after earnings", "option_chain", "Intraday; stale after one session", NULL, "FORECAST", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("earnings.surprise.period", "earnings", "Surprise-history period", "SOURCE", "fundamental_periods", "fiscal_period|fiscal_year", "SEC", "Reported period label", "fundamental_periods", FUND_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "CURRENT", "earnings.period"),
    metric("earnings.surprise.revenue", "earnings", "Revenue surprise", "UNAVAILABLE", "fundamental_periods", "actual revenue|consensus revenue", "SEC|consensus provider", "Actual / provider consensus - 1", "reported_revenue|consensus_revenue", FUND_FRESH, NULL, "FORECAST", "SUPPORTING", "NEW_INGESTION", "earnings.actual_vs_expectations.revenue"),
    metric("earnings.surprise.eps", "earnings", "EPS surprise", "UNAVAILABLE", "fundamental_periods", "actual EPS|consensus EPS", "SEC|consensus provider", "Actual / provider consensus - 1", "reported_eps|consensus_eps", FUND_FRESH, NULL, "FORECAST", "SUPPORTING", "NEW_INGESTION", "earnings.actual_vs_expectations.eps"),
    metric("earnings.surprise.price_response", "earnings", "Post-earnings price response", "DERIVED", "market_events|price_bars", "starts_at|adjusted_close", "earnings calendar|Polygon|Tiingo", "Close after event session / prior close - 1", "earnings_event|price_history", EVENT_FRESH, NULL, "VERIFIED_MARKET_DATA", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("earnings.call_highlight", "earnings", "Latest call highlight", "MODEL", "documents|document_chunks", "transcript chunks", "earnings transcript provider", "Evidence-linked bounded interpretation from transcript/release chunks", "transcript_chunks", "Latest reported call", NULL, "OPINION", "SUPPORTING", "NEW_INGESTION", "earnings.transcript_evidence"),

    # Thesis, catalysts, and risks.
    metric("thesis.bull.statement", "thesis", "Bull-case statement", "MODEL", "investment_theses|thesis_factors|research read model", "bull_case|supporting evidence", "EagleEyes", "Evidence-linked measurable company-specific statement", "research_evidence", FUND_FRESH, NULL, "OPINION", "CORE", "CURRENT", "thesis.bull"),
    metric("thesis.bear.statement", "thesis", "Bear-case statement", "MODEL", "investment_theses|thesis_factors|research read model", "bear_case|risk evidence", "EagleEyes", "Evidence-linked measurable opposing statement", "research_evidence", FUND_FRESH, NULL, "OPINION", "CORE", "CURRENT", "thesis.bear"),
    metric("thesis.bull_invalidation", "thesis", "Bull invalidation", "MODEL", "thesis_factors|research read model", "breaker conditions", "EagleEyes", "Machine-trackable threshold tied to a sourced metric where possible", "research_evidence", FUND_FRESH, NULL, "OPINION", "SUPPORTING", "CURRENT", "thesis.bull.invalidation_conditions"),
    metric("thesis.bear_invalidation", "thesis", "Bear invalidation", "MODEL", "thesis_factors|research read model", "counter-evidence conditions", "EagleEyes", "Machine-trackable threshold tied to a sourced metric where possible", "research_evidence", FUND_FRESH, NULL, "OPINION", "SUPPORTING", "CURRENT", "thesis.bear.invalidation_conditions"),
    metric("catalyst.date", "catalysts_risks", "Catalyst date", "UNAVAILABLE", "market_events|documents", "starts_at|published_at", "event calendar|news", "Confirmed future event date; recent-news dates are not future catalyst dates", "company_event", EVENT_FRESH, NULL, "VERIFIED_FACT", "SUPPORTING", "NEW_INGESTION", None),
    metric("catalyst.event", "catalysts_risks", "Catalyst event", "MODEL", "market_events|documents|prediction_markets", "event/news evidence", "event calendar|news|prediction markets", "Select company-specific evidence; label interpretation as opinion", "catalyst_evidence", EVENT_FRESH, NULL, "OPINION", "CORE", "CURRENT", "catalysts"),
    metric("catalyst.category", "catalysts_risks", "Catalyst category", "DERIVED", "market_events|documents", "event_type|metadata.catalyst_type", "event calendar|news", "Normalize to earnings/product/regulatory/investor/legal/other", "catalyst_evidence", EVENT_FRESH, NULL, "VERIFIED_FACT", "INFORMATIONAL", "DETERMINISTIC_WIRING", None),
    metric("catalyst.importance", "catalysts_risks", "Catalyst importance", "MODEL", "market_events|documents", "event evidence", "EagleEyes", "High only for earnings, verified high-exposure regulatory/legal events, or explicit thesis breaker; otherwise medium/low", "catalyst_evidence|thesis_context", EVENT_FRESH, NULL, "OPINION", "INFORMATIONAL", "MODEL_LOGIC", None),
    metric("risk.name", "catalysts_risks", "Risk name", "MODEL", "thesis_factors|documents|research snapshots", "risk evidence", "EagleEyes|news", "Company-specific normalized risk label", "risk_evidence", FUND_FRESH, NULL, "OPINION", "CORE", "CURRENT", "risks"),
    metric("risk.explanation", "catalysts_risks", "Risk explanation", "MODEL", "thesis_factors|documents", "risk evidence", "EagleEyes|news", "Evidence-linked concise explanation", "risk_evidence", FUND_FRESH, NULL, "OPINION", "SUPPORTING", "MODEL_LOGIC", None),
    metric("risk.severity", "catalysts_risks", "Risk severity", "MODEL", "thesis_factors|portfolio read model", "importance|exposure", "EagleEyes", "High when explicit breaker or ≥20% revenue/portfolio exposure; medium ≥10%; otherwise low", "risk_evidence", FUND_FRESH, NULL, "OPINION", "SUPPORTING", "MODEL_LOGIC", None),
    metric("risk.affected_thesis", "catalysts_risks", "Affected thesis element", "MODEL", "thesis_factors|investment_theses", "factor linkage", "EagleEyes", "Explicit factor/assumption linkage only", "saved_or_generated_thesis", FUND_FRESH, NULL, "OPINION", "INFORMATIONAL", "MODEL_LOGIC", None),

    # Technicals and benchmark table.
    metric("technical.trend", "market_data", "Trend", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Uptrend when price>SMA50>SMA200; downtrend when price<SMA50<SMA200; otherwise neutral", "price_200d", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "CURRENT", "market.trend"),
    metric("technical.sma_50", "market_data", "50-day moving average", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Mean of latest 50 adjusted closes", "price_50d", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "CURRENT", "market.moving_averages.sma_50"),
    metric("technical.sma_50_distance", "market_data", "Price distance from 50-day MA", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Price/SMA50-1", "price_50d", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("technical.sma_200", "market_data", "200-day moving average", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Mean of latest 200 adjusted closes", "price_200d", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "CURRENT", "market.moving_averages.sma_200"),
    metric("technical.sma_200_distance", "market_data", "Price distance from 200-day MA", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Price/SMA200-1", "price_200d", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("technical.support", "market_data", "Support", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "10th and 25th percentiles of latest 126 adjusted closes below current price", "price_126d", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "CURRENT", "market.support_resistance.support"),
    metric("technical.resistance", "market_data", "Resistance", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "75th and 90th percentiles of latest 126 adjusted closes above current price", "price_126d", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "CURRENT", "market.support_resistance.resistance"),
    metric("technical.rsi_14", "market_data", "RSI (14)", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "100-100/(1+mean gains/mean losses) over 14 close changes", "price_15d", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "CURRENT", "market.rsi_14"),
    metric("technical.rsi_read", "market_data", "RSI interpretation", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "<30 oversold; 30–45 weak; 45–60 neutral; 60–70 firm; >70 extended", "rsi_14", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "INFORMATIONAL", "DETERMINISTIC_WIRING", None),
    metric("technical.beta", "market_data", "Beta", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Cov(asset daily returns, SPY daily returns)/Var(SPY returns), require ≥252 common sessions; display sample count", "price_1y|spy_1y", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "CURRENT", "market.beta"),
    metric("technical.max_drawdown", "market_data", "Maximum drawdown", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Minimum(price/running maximum-1) over selected one-year window", "price_1y", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "CURRENT", "market.maximum_drawdown"),
    metric("technical.benchmark_drawdown", "market_data", "Benchmark max drawdown", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Same max-drawdown formula on SPY for identical dates", "spy_1y", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "INFORMATIONAL", "DETERMINISTIC_WIRING", None),
    metric("performance.security_3m", "market_data", "Security 3M return", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Latest close / close 63 sessions earlier - 1", "price_63d", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "CURRENT", "market.returns.3_month"),
    metric("performance.security_ytd", "market_data", "Security YTD return", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Latest close / final close before Jan 1 - 1", "price_ytd", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "DETERMINISTIC_WIRING", None),
    metric("performance.security_1y", "market_data", "Security 1Y return", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "Latest close / close 252 sessions earlier - 1", "price_1y", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "CURRENT", "market.returns.1_year"),
    metric("performance.spy", "market_data", "SPY benchmark returns", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "3M/YTD/1Y total price returns using identical formulas", "spy_1y", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("performance.qqq", "market_data", "QQQ benchmark returns", "DERIVED", "price_bars", "adjusted_close", "Polygon|Tiingo", "3M/YTD/1Y total price returns using identical formulas", "qqq_1y", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("performance.sector_etf", "market_data", "Sector ETF returns", "DERIVED", "price_bars|classification", "adjusted_close|sector", "Polygon|Tiingo|stored mapping", "Map sector to disclosed ETF then compute 3M/YTD/1Y returns", "sector_etf_1y", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "DETERMINISTIC_WIRING", None),

    # Ownership and sentiment.
    metric("ownership.institutional_percent", "ownership_sentiment", "Institutional ownership", "UNAVAILABLE", "", "", "13F provider", "Latest reported institutional shares / shares outstanding", "institutional_holdings", "Quarterly; stale after 135 days", NULL, "VERIFIED_FACT", "CORE", "NEW_INGESTION", None),
    metric("ownership.institutional_change", "ownership_sentiment", "Institutional ownership change", "UNAVAILABLE", "", "", "13F provider", "Latest institutional percent - prior-quarter percent", "institutional_history", "Quarterly; stale after 135 days", NULL, "VERIFIED_FACT", "SUPPORTING", "NEW_INGESTION", None),
    metric("ownership.insider_net", "ownership_sentiment", "Insider net activity", "UNAVAILABLE", "", "", "SEC Form 4", "Open-market buy shares/value minus sell shares/value over six months", "form4_transactions", "Refresh daily; stale after 7 days", NULL, "VERIFIED_FACT", "CORE", "NEW_INGESTION", None),
    metric("ownership.insider_count", "ownership_sentiment", "Insider transaction count", "UNAVAILABLE", "", "", "SEC Form 4", "Count qualifying buy/sell transactions; separate 10b5-1", "form4_transactions", "Refresh daily; stale after 7 days", NULL, "VERIFIED_FACT", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("ownership.short_percent", "ownership_sentiment", "Short interest percent", "UNAVAILABLE", "", "", "short-interest provider", "Shares short / public float", "short_interest", "Bi-monthly; stale after 25 days", NULL, "VERIFIED_FACT", "CORE", "NEW_INGESTION", None),
    metric("ownership.short_change", "ownership_sentiment", "Short-interest change", "UNAVAILABLE", "", "", "short-interest provider", "Latest short percent - prior publication", "short_interest_history", "Bi-monthly; stale after 25 days", NULL, "VERIFIED_FACT", "SUPPORTING", "NEW_INGESTION", None),
    metric("ownership.days_to_cover", "ownership_sentiment", "Days to cover", "UNAVAILABLE", "", "", "short-interest provider", "Shares short / 30-day average daily volume", "short_interest|price_volume_30d", "Bi-monthly; stale after 25 days", NULL, "VERIFIED_FACT", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("ownership.analyst_consensus", "ownership_sentiment", "Analyst consensus", "UNAVAILABLE", "", "", "consensus provider", "Provider normalized consensus; preserve analyst count", "analyst_ratings", "Stale after 30 days", NULL, "FORECAST", "CORE", "NEW_INGESTION", None),
    metric("ownership.analyst_counts", "ownership_sentiment", "Buy/hold/sell counts", "UNAVAILABLE", "", "", "consensus provider", "Provider counts", "analyst_ratings", "Stale after 30 days", NULL, "FORECAST", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("ownership.revision_signal", "ownership_sentiment", "Estimate-revision signal", "UNAVAILABLE", "", "", "consensus provider", "Up when upgrades>downgrades over 90d; down when reverse; mixed when equal", "consensus_history", "Stale after 7 days", NULL, "FORECAST", "SUPPORTING", "NEW_INGESTION", None),
    metric("ownership.iv_30d", "ownership_sentiment", "30-day implied volatility", "UNAVAILABLE", "", "", "options provider", "Interpolated ATM implied volatility to 30 calendar days", "option_chain", "Intraday; stale after one session", NULL, "FORECAST", "SUPPORTING", "NEW_INGESTION", None),
    metric("ownership.iv_rank", "ownership_sentiment", "IV rank", "UNAVAILABLE", "", "", "options provider", "(current IV-52w min)/(52w max-52w min)", "iv_history", "Intraday; stale after one session", NULL, "FORECAST", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("ownership.event_premium", "ownership_sentiment", "Earnings volatility premium", "UNAVAILABLE", "", "", "options provider", "Event-expiry IV minus adjacent non-event term-structure interpolation", "option_chain|earnings_event", "Intraday", NULL, "FORECAST", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("ownership.put_call", "ownership_sentiment", "Put/call ratio", "UNAVAILABLE", "", "", "options provider", "Put volume or OI / call volume or OI; label basis explicitly", "option_chain", "Intraday; stale after one session", NULL, "FORECAST", "INFORMATIONAL", "NEW_INGESTION", None),
    metric("sentiment.news_score", "ownership_sentiment", "News sentiment", "DERIVED", "documents", "metadata.sentiment_score", "stored news", "Mean classified article score over 30 days; require ≥5 classified articles", "news_30d", NEWS_FRESH, NULL, "OPINION", "CORE", "CURRENT", "ownership_sentiment.sentiment"),
    metric("sentiment.news_driver", "ownership_sentiment", "News sentiment driver", "MODEL", "documents", "title|summary|sentiment", "stored news|EagleEyes", "Evidence-linked summary of top recent high-quality articles", "news_30d", NEWS_FRESH, NULL, "OPINION", "SUPPORTING", "MODEL_LOGIC", None),

    # Portfolio relevance. These use existing capability/read-model infrastructure but require user context.
    metric("portfolio.current_exposure", "portfolio_fit", "Current exposure", "DERIVED", "holdings", "ticker|market_value|weight", "user portfolio", "Security market value / total portfolio value; prefer normalized stored weight", "portfolio", PORTFOLIO_FRESH, NULL, "VERIFIED_FACT", "CORE", "CONTEXT_REQUIRED", "portfolio_fit.holding_detail"),
    metric("portfolio.sector_after", "portfolio_fit", "Sector concentration after buy", "DERIVED", "holdings|securities", "weights|sector", "user portfolio|classification", "Current sector weight + proposed purchase weight adjusted for funding source", "portfolio|candidate_size|security.sector", PORTFOLIO_FRESH, NULL, "MODEL_OUTPUT", "CORE", "CONTEXT_REQUIRED", None),
    metric("portfolio.sector_limit", "portfolio_fit", "Sector target/limit", "SOURCE", "investment_policies", "max_sector_weight|target_allocation", "user policy", "Latest approved policy", "portfolio_policy", "Refresh on policy change", NULL, "USER_CONTEXT", "SUPPORTING", "CONTEXT_REQUIRED", None),
    metric("portfolio.highest_overlap", "portfolio_fit", "Highest-overlap holding", "DERIVED", "price_bars|holdings", "adjusted_close|weights", "Polygon|Tiingo|user portfolio", "Maximum pairwise Pearson daily-return correlation over ≥252 common sessions", "portfolio|price_1y", PORTFOLIO_FRESH, NULL, "MODEL_OUTPUT", "SUPPORTING", "CONTEXT_REQUIRED", None),
    metric("portfolio.correlation", "portfolio_fit", "Correlation to portfolio", "DERIVED", "price_bars|holdings", "adjusted_close|weights", "Polygon|Tiingo|user portfolio", "Correlation of candidate returns with current-weight portfolio daily returns", "portfolio|price_1y", PORTFOLIO_FRESH, NULL, "MODEL_OUTPUT", "CORE", "CONTEXT_REQUIRED", None),
    metric("portfolio.suggested_position", "portfolio_fit", "Suggested position", "MODEL", "holdings|investment_policies|price_bars", "weights|limits|returns", "EagleEyes sizing model", "No approved single-security sizing model currently exists", "position_sizing_model|portfolio", PORTFOLIO_FRESH, NULL, "OPINION", "CONDITIONAL", "MODEL_LOGIC", None),
    metric("portfolio.beta_before_after", "portfolio_fit", "Portfolio beta after buy", "DERIVED", "price_bars|holdings", "adjusted_close|weights", "Polygon|Tiingo|user portfolio", "Weighted constituent beta before and after proposed weight; beta computed vs SPY", "portfolio|candidate_size|betas", PORTFOLIO_FRESH, NULL, "MODEL_OUTPUT", "SUPPORTING", "CONTEXT_REQUIRED", None),
    metric("portfolio.stress_test", "portfolio_fit", "Market stress test", "MODEL", "holdings|price_bars|scenario read model", "weights|betas|scenario", "EagleEyes scenario model", "Existing deterministic scenario outcome or beta-scaled -20% market shock with disclosed assumptions", "portfolio|candidate_size|scenario", PORTFOLIO_FRESH, NULL, "MODEL_OUTPUT", "SUPPORTING", "CONTEXT_REQUIRED", None),
    metric("portfolio.opportunity_cost", "portfolio_fit", "Opportunity cost", "MODEL", "holdings|price_bars|macro observations", "alternatives|cash rate", "EagleEyes", "Compare candidate model return with cash proxy and eligible saved alternatives; no conclusion without common horizon", "portfolio|alternatives", PORTFOLIO_FRESH, NULL, "OPINION", "INFORMATIONAL", "CONTEXT_REQUIRED", None),

    # Decision summary and provenance.
    metric("decision.rating", "decision", "Current rating", "MODEL", "research read model|investment_theses|portfolio read model", "evidence|thesis|fit", "EagleEyes", "No approved deterministic rating policy currently exists", "decision_policy", FUND_FRESH, NULL, "OPINION", "CORE", "MODEL_LOGIC", "decision.rating"),
    metric("decision.confidence", "decision", "Confidence", "DERIVED", "research registry", "coverage|freshness|consistency", "EagleEyes", "High: ≥90% core fresh and no contradiction; medium-high ≥75%; medium ≥55%; else low", "section_statuses", "Recompute with every evidence change", NULL, "OPINION", "CORE", "DETERMINISTIC_WIRING", "decision.confidence"),
    metric("decision.entry", "decision", "Attractive entry", "MODEL", "valuation model", "fair-value sensitivity", "EagleEyes", "Only from approved valuation sensitivity and margin-of-safety policy", "valuation_model", MARKET_FRESH, NULL, "OPINION", "CONDITIONAL", "MODEL_LOGIC", "decision.attractive_entry"),
    metric("decision.invalidation", "decision", "Primary invalidation", "MODEL", "thesis_factors|research read model", "breaker evidence", "EagleEyes", "Highest-importance machine-trackable bull breaker", "research_evidence", FUND_FRESH, NULL, "OPINION", "CORE", "CURRENT", "decision.invalidation"),
    metric("decision.next_review", "decision", "Next review", "DERIVED", "market_events|thesis_factors", "starts_at|trigger", "event calendar|EagleEyes", "Day after nearest material event, otherwise when a tracked breaker updates", "company_event|tracked_breaker", EVENT_FRESH, NULL, "OPINION", "SUPPORTING", "NEW_INGESTION", "decision.next_review"),
    metric("decision.bull_thesis", "decision", "Bull thesis summary", "MODEL", "research read model", "bull case", "EagleEyes", "One-sentence evidence-linked compression of bull case", "research_evidence", FUND_FRESH, NULL, "OPINION", "CORE", "CURRENT", "decision.bull_thesis"),
    metric("decision.bear_thesis", "decision", "Bear thesis summary", "MODEL", "research read model", "bear case", "EagleEyes", "One-sentence evidence-linked compression of bear case", "research_evidence", FUND_FRESH, NULL, "OPINION", "CORE", "CURRENT", "decision.bear_thesis"),
    metric("decision.key_catalyst", "decision", "Key catalyst", "MODEL", "market_events|documents", "event/news evidence", "event calendar|news|EagleEyes", "Highest-ranked fresh company catalyst", "catalyst_evidence", EVENT_FRESH, NULL, "OPINION", "SUPPORTING", "MODEL_LOGIC", "decision.key_catalyst"),
    metric("decision.primary_risk", "decision", "Primary risk", "MODEL", "thesis_factors|documents", "risk evidence", "EagleEyes", "Highest-severity evidence-linked company risk", "risk_evidence", FUND_FRESH, NULL, "OPINION", "SUPPORTING", "MODEL_LOGIC", "decision.primary_risk"),
    metric("sources.verified.provider", "sources", "Verified-fact provider", "SOURCE", "lineage|provider_fetches", "provider", "stored providers", "Unique provider list for facts displayed", "source_lineage", "Same as underlying facts", NULL, "VERIFIED_FACT", "CORE", "CURRENT", "sources.verified.provider"),
    metric("sources.verified.as_of", "sources", "Verified-fact date", "SOURCE", "lineage|fundamental_periods", "effective_at|period_end|filed_at", "stored providers", "Latest relevant filing/effective date, preserving each metric detail", "source_lineage", "Same as underlying facts", NULL, "VERIFIED_FACT", "CORE", "CURRENT", "sources.verified.as_of"),
    metric("sources.market.provider", "sources", "Market-data provider", "SOURCE", "price_bars|market_observations", "provider", "Polygon|Tiingo", "Provider of selected current price", "price_history", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "CORE", "DETERMINISTIC_WIRING", None),
    metric("sources.market.delay", "sources", "Market-data delay", "DERIVED", "market_observations|price_bars", "latency_class|ts", "Polygon|Tiingo", "Same delay classification as header", "price_history", MARKET_FRESH, NULL, "VERIFIED_MARKET_DATA", "SUPPORTING", "DETERMINISTIC_WIRING", None),
    metric("sources.forecast.provider", "sources", "Forecast provider", "UNAVAILABLE", "", "", "consensus provider", "Provider identity and analyst count", "consensus_estimates", "Stale after 7 days", NULL, "FORECAST", "CONDITIONAL", "NEW_INGESTION", "sources.forecast"),
    metric("sources.model.version", "sources", "Model version", "SOURCE", "research read model", "version", "EagleEyes", "Version of each model output", "model_output", "Same calculation timestamp as output", NULL, "OPINION", "CORE", "CURRENT", "sources.opinion.model_version"),
    metric("sources.model.methodology", "sources", "Model methodology", "SOURCE", "research read model", "methodology", "EagleEyes", "Human-readable identifier and material assumptions", "model_output", "Versioned with output", NULL, "OPINION", "CORE", "CURRENT", "sources.opinion.methodology"),
)


SECTION_STATUS_POLICY = {
    "SUCCESS": "Every CORE metric is non-null, fresh, and successful; supporting gaps may remain explicit.",
    "PARTIAL": "At least one CORE metric is usable, but another CORE metric is null, stale, failed, or context-blocked.",
    "UNAVAILABLE": "No CORE metric is usable for the section.",
    "FAILED": "A required source or deterministic calculation errored; existing stale evidence may still be shown separately.",
}


def registry_payload() -> dict[str, object]:
    return {
        "version": "research-metric-registry-v1",
        "classification_definitions": {
            "SOURCE": "Directly stored provider/user value with no analytical transformation beyond normalization.",
            "DERIVED": "Deterministic calculation whose exact formula and required inputs are disclosed.",
            "MODEL": "Scenario, interpretation, ranking, or opinion output; never presented as verified fact.",
            "UNAVAILABLE": "No defensible existing EagleEyes source or approved calculation path.",
        },
        "section_status_policy": SECTION_STATUS_POLICY,
        "metrics": [item.payload() for item in REGISTRY],
    }
