"use client";

import { useEffect, useState } from "react";
import type { Tab, ExploreView, PortfolioView, AdvancedView } from "../../lib/routes";
import type { GuidanceDisclosure } from "../shared/GuidanceLevel";
import { EvidenceTrust } from "../shared/EvidenceTrust";

type EvidenceLink = { label: string; url?: string | null; as_of?: string | null; provider: string };
type DataTimeliness = "live" | "delayed" | "end-of-day" | "cached" | "stale";
type Movement = { ticker: string; label: string; group: "index" | "sector" | "portfolio"; value: number; change_1d?: number | null; change_1w?: number | null; change_1m?: number | null; as_of?: string | null; unit: string; provider: string; source?: string | null; data_status: DataTimeliness };
type MarketIndicator = { key: string; series_id: string; label: string; unit: string; value: number; change?: number | null; as_of?: string | null; provider: string; source?: string | null; data_status: DataTimeliness };
type Relevance = { key: string; factor: string; relevance: "high" | "moderate" | "low"; direction: "positive" | "negative" | "mixed"; explanation: string; destination: string; evidence: EvidenceLink[] };
type Event = { id: string; event_type: string; title: string; starts_at: string; tickers?: string[]; provider: string; source_url?: string | null; timing_status?: string; verified_at?: string | null };
type EventCoverage = { requested_tickers:string[]; earnings_covered_tickers:string[]; earnings_missing_tickers:string[]; earnings_coverage_ratio:number|null; macro_release_count:number; deduplicated_count:number; note:string };
type Attention = {
  id:string;type:string;entity_type:string;entity_key:string;title:string;summary:string;what_changed:string;why_it_matters:string;
  materiality:"CRITICAL"|"HIGH"|"MEDIUM"|"LOW"|"UNKNOWN";thesis_relevance:string;portfolio_relevance:string;
  evidence_quality:string;freshness:string;urgency:string;occurred_at:string;sources:EvidenceLink[];
  linked_thesis_id?:string|null;linked_portfolio_exposure?:{level:string;portfolio_weight?:number;risk_contribution?:number;holdings?:string[]}|null;
  linked_scenario?:string|null;action_label:string;action_target:string;ask_prompts:string[];affected:string[];details:Array<Record<string,unknown>>;
  state:"UNREAD"|"READ"|"DISMISSED"|"SNOOZED"|"RESOLVED";ranking_inputs:Record<string,string>;
};
type PortfolioSummary = {available:boolean;change_1d?:number|null;dollar_change?:number|null;portfolio_value?:number|null;benchmark_ticker:string;benchmark_change_1d?:number|null;contributors:Array<{ticker:string;contribution:number;change_1d:number}>;methodology:string};
type PriceContext = {ticker:string;change_1d:number;evidence_status:string;message:string};
type AlertEvent = {id:string;alert_type:string;materiality:string;title:string;summary:string;occurred_at:string;status:string};
type AlertPreferences = {delivery_mode:"IN_APP_ONLY";threshold:"MATERIAL"|"CRITICAL_ONLY";categories:Record<string,boolean>};

export type TodayBriefing = {
  version:string;as_of:string;market_data_as_of?:string|null;market_business_days_old?:number|null;
  evidence_state:"current"|"partial"|"stale_fallback";guidance:GuidanceDisclosure;headline:string;summary:string;
  portfolio_context:{available:boolean;name?:string|null;holding_count:number;missing_symbols:string[];weak_coverage_symbols:string[]};
  market_movement:Movement[];market_indicators:MarketIndicator[];portfolio_relevance:Relevance[];attention:Attention[];
  attention_summary?:{all_item_count:number;material_item_count:number;unread_count:number;no_material_change:boolean};
  portfolio_summary?:PortfolioSummary;price_context?:PriceContext[];daily_brief?:{text:string;claim_item_ids:string[];methodology:string};
  ranking_methodology?:{version:string;description:string;factors:string[]};upcoming_events:Event[];event_coverage:EventCoverage;
  alerts?:AlertEvent[];alert_preferences?:AlertPreferences;
  research_ideas:Array<unknown>;warnings:string[];calculation:{method:string;version:string;assumptions:string[]};
};

type MacroFactor = { key:string;label:string;why_it_matters:string;as_of:string|null;evidence:Array<{series_id:string;value:number;change:number|null;date:string;source:string}> };
type DataStatus = { counts:Record<string,number>;freshness:Record<string,string|null> };

function pct(value?:number|null,digits=1){return value==null?"—":`${value>=0?"+":""}${(value*100).toFixed(digits)}%`;}
function money(value?:number|null){return value==null?"—":new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1,signDisplay:"always"}).format(value);}
function dateLabel(value?:string|null){if(!value)return"Awaiting data";const dateOnly=/^\d{4}-\d{2}-\d{2}$/.test(value);return new Date(dateOnly?`${value}T12:00:00`:value).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});}
function eventDate(value:string){return new Date(value).toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});}

function EvidenceLinks({evidence}:{evidence:EvidenceLink[]}){return <div className="claim-sources">{evidence.filter(item=>item.url).map(item=><a key={`${item.label}-${item.url}`} href={item.url||"#"} target={item.url?.startsWith("http")?"_blank":undefined} rel="noreferrer"><span>{item.label}</span><small>{item.provider} · {dateLabel(item.as_of)}</small></a>)}</div>;}

function MaterialBadge({item}:{item:Attention}){return <span className={`today-materiality ${item.materiality.toLowerCase()}`}>{item.materiality==="CRITICAL"?"Review required":item.materiality.toLowerCase()}</span>;}

export function TodayPage({loading,refreshing,briefing,hasSavedPortfolio,macroFactors,dataStatus,onRefresh,onNavigate,onExplore,onPortfolio,onAdvanced,request}:{
  loading:boolean;refreshing:boolean;briefing:TodayBriefing|null;hasSavedPortfolio:boolean;macroFactors:MacroFactor[];dataStatus:DataStatus;onRefresh:()=>void;
  onNavigate:(tab:Tab)=>void;onExplore:(view:ExploreView)=>void;onPortfolio:(view:PortfolioView)=>void;onAdvanced:(view:AdvancedView)=>void;
  request:(path:string,init?:RequestInit)=>Promise<Response>;
}){
  const [hidden,setHidden]=useState<string[]>([]);const [busy,setBusy]=useState<string|null>(null);const [localState,setLocalState]=useState<Record<string,string>>({});const [stateError,setStateError]=useState<string|null>(null);
  const [alertPrefs,setAlertPrefs]=useState<AlertPreferences|null>(null);const [preferenceState,setPreferenceState]=useState<string>("");
  useEffect(()=>{if(briefing?.alert_preferences)setAlertPrefs(briefing.alert_preferences);},[briefing?.alert_preferences]);
  const attention=(briefing?.attention||[]).filter(item=>!hidden.includes(item.id));
  const material=attention.filter(item=>["CRITICAL","HIGH","MEDIUM"].includes(item.materiality));
  const portfolio=briefing?.portfolio_summary;
  const portfolioExpected=hasSavedPortfolio||Boolean(briefing?.portfolio_context.available);
  const ready=Boolean(briefing);
  const heroTitle=!ready?"Preparing your daily brief":material.length?`${material.length} item${material.length===1?"":"s"} need your attention`:portfolioExpected?"Your portfolio is up to date":"Welcome to your research workspace";
  const heroCopy=briefing?.daily_brief?.text||(!ready?"Restoring your saved portfolio, research, theses, events, and latest validated market evidence.":portfolioExpected?"Your saved portfolio is loaded. No material evidence change currently requires review.":"Add or select a portfolio once; EagleEyes will restore it automatically on future sign-ins.");
  const setState=async(item:Attention,state:"READ"|"DISMISSED"|"SNOOZED")=>{setBusy(item.id);setStateError(null);try{const snoozedUntil=state==="SNOOZED"?new Date(Date.now()+24*60*60*1000).toISOString():null;const response=await request(`/today/attention/${item.id}/state`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({state,snoozed_until:snoozedUntil})});if(!response.ok)throw new Error(await response.text());setLocalState(value=>({...value,[item.id]:state}));if(state!=="READ")setHidden(value=>[...value,item.id]);}catch{setStateError("That attention state could not be saved. The evidence item remains unchanged.");}finally{setBusy(null);}};
  const openTarget=(target:string)=>{if(target.startsWith("/decisions"))onNavigate("decisions");else if(target.startsWith("/portfolio"))onPortfolio("analysis");else if(target.includes("prediction-markets"))onExplore("prediction-markets");else if(target.startsWith("/research"))onExplore("stocks");else onAdvanced("lineage");};
  const saveAlertPrefs=async(next:AlertPreferences)=>{setAlertPrefs(next);setPreferenceState("Saving…");try{const response=await request("/alerts/preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(!response.ok)throw new Error();setPreferenceState("Saved");}catch{setPreferenceState("Could not save alert preferences");}};
  return <section className="workspace today-workspace attention-today">
    <header className={`today-attention-hero ${!ready?"preparing":""}`} aria-busy={loading||refreshing}>
      <div><span className="kicker">Today</span><h1>{heroTitle}</h1><p>{heroCopy}</p><div className="briefing-state-row"><span className={`briefing-state ${briefing?.evidence_state||"partial"}`}>{briefing?.evidence_state?.replaceAll("_"," ")||"preparing"}</span><small>{ready?`Evidence through ${dateLabel(briefing?.market_data_as_of)} · composed ${dateLabel(briefing?.as_of)}`:"Loading your private workspace…"}</small></div>{briefing?.warnings.slice(0,2).map(warning=><p className="briefing-warning" key={warning}>△ {warning}</p>)}</div>
      <aside><span>{ready?"Material items":"Workspace status"}</span><strong>{ready?material.length:"…"}</strong><small>{ready?`${briefing?.attention_summary?.unread_count||0} unread · price movement alone does not create an alert`:"Using saved evidence first; stale providers refresh in the background."}</small><button className="primary" disabled={refreshing||!ready} onClick={onRefresh}>{refreshing?"Refreshing…":ready?"Refresh today":"Preparing…"}</button></aside>
    </header>
    {briefing&&<EvidenceTrust compact label="Today composition trust" data={{kind:"MODEL_OUTPUT",provider:"EagleEyes structured attention",asOf:briefing.as_of,effectiveDate:briefing.market_data_as_of,methodology:briefing.ranking_methodology?.description||briefing.calculation.method,coverage:briefing.portfolio_context.available?briefing.portfolio_context.missing_symbols.length?"partial portfolio coverage":"portfolio-linked coverage":"general research only",freshness:briefing.evidence_state,quality:briefing.warnings.length?"PARTIAL":"SUPPORTED",modelVersion:briefing.ranking_methodology?.version||briefing.calculation.version,assumptions:briefing.calculation.assumptions,missingState:briefing.evidence_state==="stale_fallback"?"STALE":briefing.evidence_state==="partial"?"PARTIAL_COVERAGE":null}}/>}
    {briefing&&<details className="panel phase10-alert-center"><summary><span>In-app alert center</span><strong>{briefing.alerts?.length||0} active material alert{briefing.alerts?.length===1?"":"s"}</strong><small>Derived from Today attention · grouped updates supersede older alerts</small></summary><div className="phase10-alert-layout"><section>{briefing.alerts?.length?briefing.alerts.slice(0,6).map(alert=><article key={alert.id}><span>{alert.materiality} · {alert.alert_type.replaceAll("_"," ")}</span><strong>{alert.title}</strong><p>{alert.summary}</p><small>{dateLabel(alert.occurred_at)}</small></article>):<div className="today-clear-state"><strong>No material alerts</strong><p>Quiet is a valid state. Price moves alone do not create an alert.</p></div>}</section>{alertPrefs&&<aside><h3>Alert preferences</h3><label>Threshold<select value={alertPrefs.threshold} onChange={event=>void saveAlertPrefs({...alertPrefs,threshold:event.target.value as AlertPreferences["threshold"]})}><option value="MATERIAL">Material changes</option><option value="CRITICAL_ONLY">Critical only</option></select></label>{Object.entries(alertPrefs.categories).map(([key,enabled])=><label className="phase10-alert-toggle" key={key}><input type="checkbox" checked={enabled} onChange={event=>void saveAlertPrefs({...alertPrefs,categories:{...alertPrefs.categories,[key]:event.target.checked}})}/>{key.replaceAll("_"," ")}</label>)}<small>Delivery: in app only. Email and push are intentionally not enabled.</small>{preferenceState&&<small role="status">{preferenceState}</small>}</aside>}</div></details>}

    {ready&&!portfolioExpected&&<div className="today-no-portfolio"><div><span>Start your workspace</span><strong>Add or select a portfolio</strong><p>Save it once and EagleEyes will restore its holdings and evidence automatically whenever you sign in.</p></div><button className="primary" onClick={()=>onPortfolio("holdings")}>Add portfolio →</button></div>}

    {portfolioExpected&&<section className="today-portfolio-strip" aria-label="Portfolio summary"><div><span>Portfolio</span><strong>{portfolio?.available?pct(portfolio.change_1d):"Preparing"}</strong><small>{portfolio?.dollar_change==null?"Loading the latest stored session":money(portfolio.dollar_change)}</small></div><div><span>Benchmark · {portfolio?.benchmark_ticker||"SPY"}</span><strong>{pct(portfolio?.benchmark_change_1d)}</strong><small>Latest stored adjusted close</small></div><div><span>Main contributors</span><strong>{portfolio?.contributors.map(item=>item.ticker).join(", ")||"Preparing"}</strong><small>Current weight × one-session return</small></div><details><summary>Method</summary><p>{portfolio?.methodology||"Composing from saved holdings and validated prices."}</p></details></section>}

    {ready&&<section className="today-matters"><div className="section-heading"><div><span className="kicker">What matters</span><h2>{material.length?`${material.length} thing${material.length===1?"":"s"} deserve review`:"Nothing material changed"}</h2><p>{material.length?"Ranked by materiality, thesis and portfolio relevance, evidence quality, urgency, and exposure.":"No material changes were detected across your active theses and relevant forward-looking evidence today."}</p></div><button className="secondary" onClick={()=>onNavigate("ask")}>Ask EagleEyes</button></div>{stateError&&<p className="briefing-warning" role="alert">△ {stateError}</p>}
      {attention.length?<div className="today-attention-list">{attention.map((item,index)=><article className={`${item.state==="READ"||localState[item.id]==="READ"?"read":""}`} key={item.id}><div className="today-attention-rank"><b>{index+1}</b><MaterialBadge item={item}/></div><div className="today-attention-body"><header><div><span>{item.type.replaceAll("_"," ")} · {item.entity_key}</span><h3>{item.title}</h3></div><small>{item.urgency.toLowerCase()} · {item.freshness.toLowerCase()}</small></header><p className="attention-change"><b>What changed</b>{item.what_changed}</p><p><b>Why it matters</b>{item.why_it_matters}</p>{item.affected.length>0&&<p><b>Affected</b>{item.affected.join(", ")}</p>}{item.linked_portfolio_exposure&&<p><b>Portfolio relevance</b>{item.linked_portfolio_exposure.level.toLowerCase()}{item.linked_portfolio_exposure.portfolio_weight!=null?` · ${(item.linked_portfolio_exposure.portfolio_weight*100).toFixed(1)}% current weight exposure`:""}{item.linked_portfolio_exposure.risk_contribution!=null?` · ${(item.linked_portfolio_exposure.risk_contribution*100).toFixed(1)}% modeled risk contribution`:""}</p>}<details><summary>Evidence and ranking</summary><p>{item.summary}</p><div className="attention-ranking-inputs">{Object.entries(item.ranking_inputs).map(([key,value])=><span key={key}>{key.replaceAll("_"," ")}: <b>{value.toLowerCase()}</b></span>)}</div><EvidenceLinks evidence={item.sources}/>{item.details.length>0&&<pre>{JSON.stringify(item.details,null,2)}</pre>}</details><div className="today-attention-actions"><button className="primary" onClick={()=>openTarget(item.action_target)}>{item.action_label} →</button><button onClick={()=>onNavigate("ask")}>Why does this matter?</button><button disabled={busy===item.id} onClick={()=>void setState(item,"READ")}>Mark read</button><button disabled={busy===item.id} onClick={()=>void setState(item,"SNOOZED")}>Snooze until tomorrow</button><button disabled={busy===item.id} onClick={()=>void setState(item,"DISMISSED")}>Dismiss</button></div></div></article>)}</div>:<div className="today-clear-state today-material-clear"><strong>No material changes were detected across your active theses today.</strong><p>That is a valid result. EagleEyes will continue monitoring verified evidence and upcoming review dates without manufacturing alerts.</p></div>}
    </section>}

    {!!briefing?.price_context?.length&&<section className="panel today-price-context"><div className="panel-head"><div><span>Price is context</span><h3>Unusual moves without automatic thesis conclusions</h3></div></div>{briefing.price_context.map(item=><div key={item.ticker}><strong>{item.ticker} {pct(item.change_1d)}</strong><p>{item.message}</p></div>)}</section>}

    <div className="today-forward-grid"><section className="panel"><div className="panel-head"><div><span>Upcoming</span><h3>Events within the decision horizon</h3></div><button onClick={()=>onExplore("prediction-markets")}>Market expectations →</button></div>{briefing?.event_coverage&&<div className="event-coverage"><strong>{briefing.event_coverage.earnings_coverage_ratio==null?"General calendar":`${Math.round(briefing.event_coverage.earnings_coverage_ratio*100)}% holdings earnings coverage`}</strong>{briefing.event_coverage.earnings_missing_tickers.length>0&&<small>Missing validated dates: {briefing.event_coverage.earnings_missing_tickers.join(", ")}. Missing data is not interpreted as no event.</small>}</div>}<div className="today-event-list">{briefing?.upcoming_events.length?briefing.upcoming_events.slice(0,8).map(event=><a key={event.id} href={event.source_url||"#"} target={event.source_url?.startsWith("http")?"_blank":undefined} rel="noreferrer"><time>{eventDate(event.starts_at)}</time><div><strong>{event.title}</strong><small>{event.event_type.replaceAll("_"," ")} · {event.provider}{event.tickers?.length?` · ${event.tickers.join(", ")}`:""}</small></div></a>):<div className="today-clear-state"><strong>No validated upcoming events are stored</strong><p>EagleEyes does not invent event dates.</p></div>}</div></section>
      <section className="panel today-ask-prompts"><div className="panel-head"><div><span>Ask from today</span><h3>Continue the investigation</h3></div></div>{Array.from(new Set(attention.flatMap(item=>item.ask_prompts))).slice(0,5).map(prompt=><button key={prompt} onClick={()=>onNavigate("ask")}>{prompt} →</button>)}{!attention.length&&<button onClick={()=>onNavigate("ask")}>What should I review next? →</button>}</section></div>

    <details className="panel today-secondary-context"><summary>Secondary market and methodology context</summary><p>Broad prices and macro indicators provide context; they do not outrank verified thesis or portfolio evidence.</p><div className="today-secondary-grid"><section><h3>Broad market</h3>{briefing?.market_movement.filter(row=>row.group==="index").slice(0,5).map(row=><p key={row.ticker}><b>{row.ticker}</b><span>{pct(row.change_1d)} · {dateLabel(row.as_of)}</span></p>)}</section><section><h3>Macro indicators</h3>{briefing?.market_indicators.slice(0,5).map(row=><p key={row.key}><b>{row.label}</b><span>{row.value.toFixed(2)} {row.unit} · {dateLabel(row.as_of)}</span></p>)}</section><section><h3>Portfolio factors</h3>{briefing?.portfolio_relevance.slice(0,5).map(row=><p key={row.key}><b>{row.factor}</b><span>{row.relevance} · {row.direction}</span></p>)}</section></div><p>{briefing?.ranking_methodology?.description}</p><div className="today-coverage-row"><span>Prices {dataStatus.counts.price_bars||0}</span><span>Macro {dataStatus.counts.macro_observations||0}</span><span>Markets {dataStatus.counts.market_snapshots||0}</span><span>Method {briefing?.ranking_methodology?.version||briefing?.calculation.version}</span></div>{macroFactors.slice(0,3).map(factor=><small key={factor.key}>{factor.label} · {factor.why_it_matters}</small>)}</details>
  </section>;
}
