"use client";

/* eslint-disable react-hooks/purity, react-hooks/exhaustive-deps */

import { useMemo, useState } from "react";
import type { Tab, ExploreView, PortfolioView, AdvancedView } from "../../lib/routes";
import { useRouteBudgetTelemetry } from "../../lib/frontend-budget-telemetry";
import type { GuidanceDisclosure } from "../shared/GuidanceLevel";

type EvidenceLink={label:string;url?:string|null;as_of?:string|null;provider:string};
type Movement={ticker:string;label:string;group:"index"|"sector"|"portfolio";value:number;change_1d?:number|null;as_of?:string|null;unit:string;provider:string;data_status:string};
type MarketIndicator={key:string;series_id:string;label:string;unit:string;value:number;change?:number|null;as_of?:string|null;provider:string;data_status:string};
type Relevance={key:string;factor:string;relevance:"high"|"moderate"|"low";direction:"positive"|"negative"|"mixed";explanation:string;destination:string;evidence:EvidenceLink[]};
type Event={id:string;event_type:string;title:string;starts_at:string;tickers?:string[];provider:string;source_url?:string|null};
type EventCoverage={requested_tickers:string[];earnings_covered_tickers:string[];earnings_missing_tickers:string[];earnings_coverage_ratio:number|null;macro_release_count:number;deduplicated_count:number;note:string};
type Attention={id:string;title:string;ask_prompts:string[]};
type PortfolioSummary={available:boolean;change_1d?:number|null;dollar_change?:number|null;portfolio_value?:number|null;benchmark_ticker:string;benchmark_change_1d?:number|null;contributors:Array<{ticker:string;contribution:number;change_1d:number}>;methodology:string};
export type TodayBriefing={version:string;as_of:string;market_data_as_of?:string|null;evidence_state:"current"|"partial"|"stale_fallback";guidance:GuidanceDisclosure;headline:string;summary:string;portfolio_context:{available:boolean;name?:string|null;holding_count:number;missing_symbols:string[];weak_coverage_symbols:string[]};market_movement:Movement[];market_indicators:MarketIndicator[];portfolio_relevance:Relevance[];attention:Attention[];portfolio_summary?:PortfolioSummary;daily_brief?:{text:string};upcoming_events:Event[];event_coverage:EventCoverage;warnings:string[];calculation:{method:string;version:string;assumptions:string[]}};

type HealthComponent={score?:number;weight?:number;coverage?:number};
export type PortfolioAction={id:string;source_key:string;source:string;action:"REVIEW"|"REDUCE"|"ADD"|"HOLD"|"INVESTIGATE";title:string;reason:string;affected_holdings:string[];materiality:string;urgency:string;confidence:string;portfolio_exposure:number;evidence_date?:string|null;suggested_next_step:string;follow_up_date?:string|null;priority:number;state:"OPEN"|"INVESTIGATING"|"ACCEPTED"|"SNOOZED"|"COMPLETED"|"DISMISSED";snoozed_until?:string|null};
export type PortfolioHoldingHealth={ticker:string;company:string;weight:number;market_value?:number|null;health_score:number;health_contribution:number;fundamental_score?:number|null;valuation_score?:number|null;momentum_score?:number|null;risk_contribution?:number|null;performance:{"1d"?:number|null;"1m"?:number|null;"1y"?:number|null};thesis_status:string;thesis_monitor_status:string;conviction?:number|null;data_confidence:string;data_quality:string;evidence_date?:string|null;change:number;active_action_count:number};
type PortfolioHealth={score?:number;band?:string;confidence?:string;coverage?:number;delta?:number|null;components?:Record<string,HealthComponent>;largest_positive?:string|null;largest_negative?:string|null};
export type PortfolioOverview={version?:string;portfolio?:{id:string;name:string};as_of?:string;trigger?:string;snapshot_id?:string;refresh_queued?:boolean;health?:PortfolioHealth;holdings?:PortfolioHoldingHealth[];actions?:PortfolioAction[];changes?:Array<{type:string;title:string;delta?:number;occurred_at:string;ticker?:string;component?:string;status?:string}>;history?:Array<{id:string;effective_at:string;trigger:string;score:number;band:string}>;warnings?:string[];methodology?:string};
type MacroFactor={key:string;label:string;why_it_matters:string;as_of:string|null;evidence:Array<{series_id:string;value:number;change:number|null;date:string;source:string}>};
type DataStatus={counts:Record<string,number>;freshness:Record<string,string|null>};
type PortfolioOption={id:string|number;name:string;holdings:Array<unknown>};
type HeatSort="priority"|"weight"|"health"|"risk"|"performance"|"change";

const pct=(value?:number|null,digits=1,sign=true)=>value==null?"—":`${sign&&value>=0?"+":""}${(value*100).toFixed(digits)}%`;
const money=(value?:number|null)=>value==null?"—":new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1}).format(value);
function dateLabel(value?:string|null){if(!value)return"Awaiting data";const dateOnly=/^\d{4}-\d{2}-\d{2}$/.test(value);return new Date(dateOnly?`${value}T12:00:00`:value).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});}
const eventDate=(value:string)=>new Date(value).toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});
const scoreTone=(score?:number|null)=>score==null?"unavailable":score>=70?"good":score>=55?"watch":"weak";
const componentLabel=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

export function TodayPage({loading,refreshing,briefing,overview,portfolios,selectedPortfolioId,hasSavedPortfolio,macroFactors,dataStatus,onRefreshOverview,onSelectPortfolio,onOverviewChange,onNavigate,onExplore,onPortfolio,request}:{loading:boolean;refreshing:boolean;briefing:TodayBriefing|null;overview:PortfolioOverview|null;portfolios:PortfolioOption[];selectedPortfolioId:string|number|null;hasSavedPortfolio:boolean;macroFactors:MacroFactor[];dataStatus:DataStatus;onRefresh:()=>void;onRefreshOverview:()=>void;onSelectPortfolio:(id:string)=>void;onOverviewChange:(overview:PortfolioOverview)=>void;onNavigate:(tab:Tab)=>void;onExplore:(view:ExploreView)=>void;onPortfolio:(view:PortfolioView)=>void;onAdvanced:(view:AdvancedView)=>void;request:(path:string,init?:RequestInit)=>Promise<Response>}){
  useRouteBudgetTelemetry("today");
  const [sort,setSort]=useState<HeatSort>("priority");
  const [busyAction,setBusyAction]=useState<string|null>(null);
  const [actionError,setActionError]=useState<string|null>(null);
  const [showActions,setShowActions]=useState(false);
  const [showHoldings,setShowHoldings]=useState(false);
  const portfolioExpected=hasSavedPortfolio||Boolean(briefing?.portfolio_context.available);
  const holdings=overview?.holdings||[],changes=overview?.changes||[],history=overview?.history||[];
  const health=overview?.health,healthComponents=health?.components||{};
  const activeActions=(overview?.actions||[]).filter(item=>!["COMPLETED","DISMISSED"].includes(item.state));
  const primaryAction=activeActions[0],nextEvent=briefing?.upcoming_events?.[0],materialChanges=changes.slice(0,3);
  const thesisChanges=changes.filter(item=>item.type.toLowerCase().includes("thesis")||item.status?.toLowerCase().includes("thesis")).slice(0,3);
  const riskHolding=[...holdings].sort((a,b)=>a.health_score-b.health_score)[0],opportunityHolding=[...holdings].sort((a,b)=>b.change-a.change)[0];
  const sortedHoldings=useMemo(()=>[...holdings].sort((left,right)=>sort==="weight"?right.weight-left.weight:sort==="health"?left.health_score-right.health_score:sort==="risk"?Number(right.risk_contribution||0)-Number(left.risk_contribution||0):sort==="performance"?Number(right.performance["1y"]||0)-Number(left.performance["1y"]||0):sort==="change"?left.change-right.change:right.active_action_count-left.active_action_count||left.health_score-right.health_score||right.weight-left.weight),[holdings,sort]);

  async function setActionState(item:PortfolioAction,state:PortfolioAction["state"]){setBusyAction(item.id);setActionError(null);try{const snoozedUntil=state==="SNOOZED"?new Date(Date.now()+86400000).toISOString():null;const response=await request(`/portfolio-actions/${item.id}/state`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({state,snoozed_until:snoozedUntil,note:""})});if(!response.ok)throw new Error(await response.text());const updated=await response.json();if(overview)onOverviewChange({...overview,actions:(overview.actions||[]).map(action=>action.id===item.id?updated:action)});}catch{setActionError("That action state could not be saved. The recommendation remains unchanged.");}finally{setBusyAction(null);}}

  if(!portfolioExpected&&!loading)return <section className="workspace today-workspace" data-route-budget="today"><div className="today-no-portfolio"><div><span>Portfolio intelligence</span><strong>Add or select a portfolio</strong><p>Save holdings once and EagleEyes will build a private, persistent health history for that portfolio.</p></div><button className="primary" onClick={()=>onPortfolio("holdings")}>Add portfolio →</button></div></section>;

  return <section className="workspace today-workspace portfolio-overview-workspace" data-route-budget="today" aria-busy={loading}>
    <header className="portfolio-overview-header"><div><span className="kicker">Today</span><h1>{briefing?.headline||"What changed since yesterday that matters?"}</h1><p>{briefing?.summary||"Restoring the latest portfolio briefing and material changes."}</p></div><div className="portfolio-overview-controls"><label>Portfolio<select value={selectedPortfolioId==null?"":String(selectedPortfolioId)} onChange={event=>onSelectPortfolio(event.target.value)}>{portfolios.map(item=><option key={String(item.id)} value={String(item.id)}>{item.name} · {item.holdings.length} holdings</option>)}</select></label><button className="secondary" disabled={!overview||refreshing} onClick={onRefreshOverview}>{refreshing?"Refreshing…":"Recalculate"}</button></div></header>
    {!overview?<section className="panel overview-snapshot-loading"><strong>{loading?"Restoring the latest portfolio snapshot…":"Portfolio snapshot unavailable"}</strong><p>{loading?"Stored evidence is being composed. Future visits load the saved result immediately.":"The briefing remains available, but portfolio health could not be loaded. No score or zero-value substitute was inferred."}</p>{!loading&&<button className="secondary" disabled={refreshing} onClick={onRefreshOverview}>{refreshing?"Retrying…":"Retry portfolio snapshot"}</button>}</section>:<>
      <section className="today-priority-grid" aria-label="What matters today">
        <article className="panel"><span>Top material changes</span><h2>{materialChanges.length?`${materialChanges.length} changes need review`:"No material change recorded"}</h2>{materialChanges.length?materialChanges.map((item,index)=><p key={`${item.type}-${index}`}><strong>{item.title}</strong><small>{item.delta==null?item.type:`${item.delta>=0?"▲":"▼"} ${Math.abs(item.delta).toFixed(1)} · ${item.type}`}</small></p>):<p>The current snapshot has no verified change versus its baseline.</p>}</article>
        <article className="panel"><span>Highest-priority action</span>{primaryAction?<><h2>{primaryAction.title}</h2><p>{primaryAction.reason}</p><button className="secondary" onClick={()=>setShowActions(true)}>Review action →</button></>:<><h2>No open action</h2><p>Quiet is a valid state. EagleEyes will not manufacture a recommendation.</p></>}</article>
        <article className="panel"><span>Next material event</span>{nextEvent?<><h2>{nextEvent.title}</h2><p>{eventDate(nextEvent.starts_at)} · {nextEvent.provider}</p><button className="secondary" onClick={()=>onExplore("prediction-markets")}>All upcoming events →</button></>:<><h2>No validated upcoming event</h2><p>Missing dates are not interpreted as no event.</p></>}</article>
      </section>
      {(overview.warnings||[]).map(warning=><p className="briefing-warning" key={warning}>△ {warning}</p>)}
      <section className="today-support-grid">
        <article className={`panel ${scoreTone(health?.score)}`}><span>Health trend</span>{health?.score==null?<><h2>Health score unavailable</h2><p>This snapshot is partial. No score or zero-value substitute was inferred.</p></>:<><h2>{health.score.toFixed(0)} · {health.band||"Band unavailable"}</h2><p>{health.delta==null?"First recorded baseline":`${health.delta>=0?"▲":"▼"} ${Math.abs(health.delta).toFixed(1)} since the prior snapshot`} · {health.coverage==null?"coverage unavailable":`${Math.round(health.coverage*100)}% evidence coverage`}</p></>}<small>{history.length} recorded snapshot{history.length===1?"":"s"}</small></article>
        <article className="panel"><span>Risk / opportunity shortlist</span><h2>{riskHolding?`${riskHolding.ticker} needs the closest review`:"Risk ranking unavailable"}</h2><p>{riskHolding?`${riskHolding.health_score.toFixed(0)} health · ${pct(riskHolding.weight,1,false)} weight`:"No covered holding is available."}</p>{opportunityHolding&&opportunityHolding.ticker!==riskHolding?.ticker&&<small>Improving most: {opportunityHolding.ticker} {opportunityHolding.change>=0?"▲":"▼"} {Math.abs(opportunityHolding.change).toFixed(1)}</small>}</article>
        <article className="panel"><span>Thesis changes</span><h2>{thesisChanges.length?`${thesisChanges.length} thesis item${thesisChanges.length===1?"":"s"}`:"No recorded thesis change"}</h2>{thesisChanges.map((item,index)=><p key={`${item.title}-${index}`}>{item.title}</p>)}<button className="secondary" onClick={()=>onNavigate("decisions")}>Open decisions →</button></article>
      </section>
      <section className="today-health-components panel"><header><div><span>Health evidence</span><h2>Supporting components</h2></div><small>{health?.confidence||"Partial / unavailable"} confidence</small></header>{Object.keys(healthComponents).length?<div>{Object.entries(healthComponents).slice(0,5).map(([key,item])=><p key={key}><span>{componentLabel(key)}</span><strong>{item.score==null?"Unavailable":item.score.toFixed(0)}</strong><small>{item.coverage==null?"coverage unavailable":`${Math.round(item.coverage*100)}% covered`}</small></p>)}</div>:<p>No component scores are available in this partial snapshot.</p>}</section>
      <div className="today-on-demand-controls"><button className="secondary" aria-expanded={showActions} onClick={()=>setShowActions(value=>!value)}>{showActions?"Hide action workflow":"Review all actions"}</button><button className="secondary" aria-expanded={showHoldings} onClick={()=>setShowHoldings(value=>!value)}>{showHoldings?"Hide holdings detail":"Open holdings heatmap"}</button></div>
      {showActions&&<section className="portfolio-action-center"><div className="section-heading"><div><span className="kicker">Action Center</span><h2>Full action workflow</h2></div><small>{activeActions.length} active</small></div>{actionError&&<p className="briefing-warning" role="alert">△ {actionError}</p>}{!activeActions.length&&<p>No open portfolio actions.</p>}{activeActions.map((item,index)=><article key={item.id}><div className="action-rank"><b>{index+1}</b><span className={`action-type ${item.action.toLowerCase()}`}>{item.action}</span></div><div><header><div><h3>{item.title}</h3><small>{item.source.replaceAll("_"," ")} · {item.urgency.toLowerCase()} · {item.confidence.toLowerCase()} confidence</small></div><strong>{item.priority.toFixed(0)}</strong></header><p>{item.reason}</p><details><summary>Recommended next step</summary><p>{item.suggested_next_step}</p><small>Evidence {dateLabel(item.evidence_date)} · follow up {dateLabel(item.follow_up_date)}</small></details><footer><button disabled={busyAction===item.id} onClick={()=>void setActionState(item,"INVESTIGATING")}>Investigate</button><button disabled={busyAction===item.id} onClick={()=>void setActionState(item,"ACCEPTED")}>Accept plan</button><button disabled={busyAction===item.id} onClick={()=>void setActionState(item,"SNOOZED")}>Snooze</button><button disabled={busyAction===item.id} onClick={()=>void setActionState(item,"DISMISSED")}>Dismiss</button><button onClick={()=>onNavigate("ask")}>Ask why →</button></footer></div></article>)}</section>}
      {showHoldings&&<section className="holdings-heatmap"><div className="section-heading"><div><span className="kicker">Holdings heatmap</span><h2>Every holding, on demand</h2></div><label>Sort<select value={sort} onChange={event=>setSort(event.target.value as HeatSort)}><option value="priority">Action priority</option><option value="weight">Position size</option><option value="health">Weakest health</option><option value="risk">Risk contribution</option><option value="performance">One-year performance</option><option value="change">Largest deterioration</option></select></label></div><div className="heatmap-table" role="table"><div className="heatmap-row heatmap-head" role="row"><span>Holding</span><span>Position</span><span>Health</span><span>Fundamentals</span><span>Valuation</span><span>Momentum</span><span>Risk</span><span>1Y return</span><span>Thesis</span><span>Evidence</span></div>{sortedHoldings.map(item=><div className={`heatmap-row ${scoreTone(item.health_score)}`} role="row" key={item.ticker}><span><strong>{item.ticker}</strong><small>{item.company}</small></span><span><strong>{pct(item.weight,1,false)}</strong><small>{money(item.market_value)}</small></span><span><strong>{item.health_score.toFixed(0)}</strong><small>{item.change===0?"No change":`${item.change>0?"▲":"▼"} ${Math.abs(item.change).toFixed(1)}`}</small></span><ScoreCell value={item.fundamental_score}/><ScoreCell value={item.valuation_score}/><ScoreCell value={item.momentum_score}/><span><strong>{item.risk_contribution==null?"—":pct(item.risk_contribution,1,false)}</strong><small>modeled</small></span><span><strong>{pct(item.performance["1y"])}</strong><small>{pct(item.performance["1m"])} 1M</small></span><span><strong>{item.thesis_status.replaceAll("_"," ")}</strong><small>Conviction {item.conviction==null?"Not set":`${item.conviction}/5`}</small></span><span><strong>{item.data_confidence}</strong><small>{item.data_quality} · {dateLabel(item.evidence_date)}</small></span></div>)}</div></section>}
    </>}
    <details className="panel today-secondary-context"><summary>Broad market, macro context, and methodology</summary><div className="today-secondary-grid"><section><h3>Broad market</h3>{briefing?.market_movement.filter(row=>row.group==="index").slice(0,5).map(row=><p key={row.ticker}><b>{row.ticker}</b><span>{pct(row.change_1d)} · {dateLabel(row.as_of)}</span></p>)}</section><section><h3>Macro indicators</h3>{briefing?.market_indicators.slice(0,5).map(row=><p key={row.key}><b>{row.label}</b><span>{row.value.toFixed(2)} {row.unit} · {dateLabel(row.as_of)}</span></p>)}</section><section><h3>Portfolio factors</h3>{briefing?.portfolio_relevance.slice(0,5).map(row=><p key={row.key}><b>{row.factor}</b><span>{row.relevance} · {row.direction}</span></p>)}</section></div><p>{overview?.methodology||"Methodology is unavailable for this partial snapshot."}</p><div className="today-coverage-row"><span>Prices {dataStatus.counts.price_bars||0}</span><span>Macro {dataStatus.counts.macro_observations||0}</span><span>Markets {dataStatus.counts.market_snapshots||0}</span><span>Health model {overview?.version||"unavailable"}</span></div>{macroFactors.slice(0,3).map(factor=><small key={factor.key}>{factor.label} · {factor.why_it_matters}</small>)}</details>
  </section>;
}

function ScoreCell({value}:{value?:number|null}){return <span><strong>{value==null?"—":value.toFixed(0)}</strong><small>{value==null?"uncovered":value>=70?"supportive":value>=55?"mixed":"weak"}</small></span>;}
