"use client";

import type { Dispatch, SetStateAction } from "react";
import type { InvestmentThesis, ThesisAssumption, ThesisFactor } from "./contracts";

export type ThesisRelationship="OWN"|"CONSIDER"|"WATCH"|"AVOID";

const relationshipCopy:Record<ThesisRelationship,string>={
  OWN:"I own it",CONSIDER:"I’m considering it",WATCH:"I’m watching it",AVOID:"I currently avoid it",
};

export function GuidedThesisEditor({form,setForm,selected,drafting,saving,stage,setStage,relationship,setRelationship,personalReason,setPersonalReason,reviewConfirmed,setReviewConfirmed,onDraft}:{
  form:InvestmentThesis;setForm:Dispatch<SetStateAction<InvestmentThesis>>;selected:boolean;drafting:boolean;saving:boolean;
  stage:"setup"|"review";setStage:(value:"setup"|"review")=>void;relationship:ThesisRelationship;setRelationship:(value:ThesisRelationship)=>void;
  personalReason:string;setPersonalReason:(value:string)=>void;reviewConfirmed:boolean;setReviewConfirmed:(value:boolean)=>void;onDraft:()=>void;
}){
  const assumptions=form.assumptions||[];const factors=form.factors||[];
  const markChanged=()=>setReviewConfirmed(false);
  const updateForm=(patch:Partial<InvestmentThesis>)=>{markChanged();setForm(value=>({...value,...patch}));};
  const setAssumption=(index:number,patch:Partial<ThesisAssumption>)=>{markChanged();setForm(value=>({...value,assumptions:value.assumptions.map((item,itemIndex)=>itemIndex===index?{...item,...patch,evidence_mapping:{...item.evidence_mapping,...patch.evidence_mapping,origin:"USER_BELIEF",confirmation_state:"PENDING"}}:item)}));};
  const setFactor=(index:number,patch:Partial<ThesisFactor>)=>{markChanged();setForm(value=>({...value,factors:value.factors.map((item,itemIndex)=>itemIndex===index?{...item,...patch,evidence_mapping:{...item.evidence_mapping,...patch.evidence_mapping,origin:"USER_BELIEF",confirmation_state:"PENDING"}}:item)}));};
  const addAssumption=()=>{markChanged();setForm(value=>({...value,assumptions:[...value.assumptions,{description:"",category:"CUSTOM",importance:"MEDIUM",status:"UNTESTED",evidence_mapping:{source:"user-authored",origin:"USER_BELIEF",confirmation_state:"PENDING"}}]}));};
  const addFactor=(factor_type:ThesisFactor["factor_type"])=>{markChanged();setForm(value=>({...value,factors:[...value.factors,{factor_type,description:"",evidence_mapping:{source:"user-authored",origin:"USER_BELIEF",confirmation_state:"PENDING"}}]}));};
  if(stage==="setup"&&!selected)return <section className="guided-thesis-setup">
    <header><div><span>Three quick inputs</span><h3>Start with your relationship to the company.</h3><p>EagleEyes will assemble an editable thesis from verified research. It will not save or claim that you believe anything until you review it.</p></div></header>
    <div className="guided-thesis-questions">
      <label><b>1. Company</b><input value={form.ticker} maxLength={10} onChange={event=>setForm({...form,ticker:event.target.value.toUpperCase()})} placeholder="AAPL"/><small>A supported stock or ETF ticker</small></label>
      <fieldset><legend>2. What is your relationship to it?</legend>{(Object.keys(relationshipCopy) as ThesisRelationship[]).map(value=><label key={value} className={relationship===value?"selected":""}><input type="radio" name="thesis-relationship" value={value} checked={relationship===value} onChange={()=>setRelationship(value)}/><span>{relationshipCopy[value]}</span></label>)}</fieldset>
      <label><b>3. Why is it on your mind? <em>Optional</em></b><textarea value={personalReason} maxLength={500} onChange={event=>setPersonalReason(event.target.value)} placeholder="One sentence is enough—for example, I think cloud demand may remain durable."/><small>This is saved as your belief, separate from company evidence.</small></label>
      <label><b>Expected horizon</b><select value={form.investment_horizon} onChange={event=>setForm({...form,investment_horizon:event.target.value as InvestmentThesis["investment_horizon"]})}><option value="short">Under 1 year</option><option value="medium">1–3 years</option><option value="long">3+ years</option><option value="custom">Custom</option></select></label>
    </div>
    <button type="button" className="primary guided-build-button" disabled={drafting||!form.ticker.trim()} onClick={onDraft}>{drafting?"Reviewing verified research…":"Build an evidence-assisted thesis →"}</button>
  </section>;

  const factorGroups=(['CATALYST','RISK','BREAKER'] as const).map(type=>({type,items:factors.map((item,index)=>({item,index})).filter(({item})=>item.factor_type===type)}));
  return <section className="guided-thesis-review">
    <header><div><span>{selected?`Saved thesis · version ${form.current_version}`:"Unsaved evidence-assisted draft"}</span><h3>Review what must remain true.</h3><p>Remove weak suggestions, edit the language, and add your own belief. Remaining suggestions become yours only after confirmation.</p></div>{!selected&&<button type="button" onClick={()=>{setStage("setup");setReviewConfirmed(false);}}>← Change the setup</button>}</header>
    <div className="thesis-origin-key"><span className="suggested">Suggested by EagleEyes</span><span className="belief">Your belief</span><span className="confirmed">Confirmed by you</span></div>
    <section className="guided-thesis-summary"><label><span>Core thesis</span><textarea required value={form.summary} onChange={event=>{markChanged();setForm({...form,summary:event.target.value,source_context:{...form.source_context,summary_edited_by_user:true}});}}/></label><aside><label><span>Your reason <em>Optional</em></span><textarea value={personalReason} maxLength={500} onChange={event=>{markChanged();setPersonalReason(event.target.value);}} placeholder="Add one sentence about why this is on your mind."/></label><small>User belief · not inferred from financial evidence</small></aside></section>
    <section className="guided-thesis-block"><header><div><span>What must remain true</span><h4>Key assumptions</h4><p>Keep only the conditions you want EagleEyes to monitor.</p></div><button type="button" onClick={addAssumption}>＋ Add assumption</button></header>{assumptions.length?assumptions.map((item,index)=>{const userAuthored=item.evidence_mapping?.origin==="USER_BELIEF";const confirmed=item.evidence_mapping?.confirmation_state==="USER_CONFIRMED";return <article className="guided-edit-row" key={item.id||index}><div className="guided-item-copy"><span className={userAuthored?"belief":confirmed?"confirmed":"suggested"}>{userAuthored?"Your belief":confirmed?"Confirmed by you":"EagleEyes draft"}</span><textarea rows={2} aria-label={`Assumption ${index+1}`} value={item.description} onChange={event=>setAssumption(index,{description:event.target.value,evidence_mapping:{...item.evidence_mapping,edited_by_user:true}})}/></div><div className="guided-item-actions"><label><small>Importance</small><select aria-label={`Importance for assumption ${index+1}`} value={item.importance} onChange={event=>setAssumption(index,{importance:event.target.value as ThesisAssumption["importance"]})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><button type="button" className="remove" onClick={()=>{markChanged();setForm({...form,assumptions:assumptions.filter((_,itemIndex)=>itemIndex!==index)});}}>Remove</button></div></article>}):<p>No assumption is currently included. Add one only if it matters to your view.</p>}</section>
    <div className="guided-factor-list">{factorGroups.map(({type,items})=><section className="guided-thesis-block" key={type}><header><div><span>{type==="CATALYST"?"What could help":type==="RISK"?"What could hurt":"What ends the thesis"}</span><h4>{type==="BREAKER"?"Thesis breakers":`${type[0]}${type.slice(1).toLowerCase()}s`}</h4></div><button type="button" onClick={()=>addFactor(type)}>＋ Add</button></header>{items.length?<div className="guided-factor-rows">{items.map(({item,index})=>{const userAuthored=item.evidence_mapping?.origin==="USER_BELIEF";const confirmed=item.evidence_mapping?.confirmation_state==="USER_CONFIRMED";return <article className="guided-edit-row" key={item.id||index}><div className="guided-item-copy"><span className={userAuthored?"belief":confirmed?"confirmed":"suggested"}>{userAuthored?"Your belief":confirmed?"Confirmed by you":"EagleEyes draft"}</span><textarea rows={3} aria-label={`${type.toLowerCase()} ${index+1}`} value={item.description} onChange={event=>setFactor(index,{description:event.target.value,evidence_mapping:{...item.evidence_mapping,edited_by_user:true}})}/></div><button type="button" className="remove" onClick={()=>{markChanged();setForm({...form,factors:factors.filter((_,itemIndex)=>itemIndex!==index)});}}>Remove</button></article>})}</div>:<p>No {type.toLowerCase()} is included.</p>}</section>)}</div>
    <details className="guided-thesis-advanced"><summary>Edit thesis details and monitoring rules</summary><p>The structured editor remains available for investors who want precise thresholds. It is not required to save a useful thesis.</p><div className="thesis-fields"><label>Relationship<select value={relationship} onChange={event=>{markChanged();setRelationship(event.target.value as ThesisRelationship);}}>{(Object.keys(relationshipCopy) as ThesisRelationship[]).map(value=><option key={value} value={value}>{relationshipCopy[value]}</option>)}</select></label><label>Status<select value={form.status} onChange={event=>updateForm({status:event.target.value as InvestmentThesis["status"]})}><option>DRAFT</option><option>ACTIVE</option><option>UNDER_REVIEW</option><option>CLOSED</option><option>ARCHIVED</option></select></label><label>Horizon<select value={form.investment_horizon} onChange={event=>updateForm({investment_horizon:event.target.value as InvestmentThesis["investment_horizon"]})}><option value="short">Short</option><option value="medium">Medium</option><option value="long">Long</option><option value="custom">Custom</option></select></label><label>Review date<input type="date" value={form.review_date||""} onChange={event=>updateForm({review_date:event.target.value||null})}/></label></div><label>Base case<textarea value={form.base_case} onChange={event=>updateForm({base_case:event.target.value})}/></label><label>Bull case<textarea value={form.bull_case} onChange={event=>updateForm({bull_case:event.target.value})}/></label><label>Bear case<textarea value={form.bear_case} onChange={event=>updateForm({bear_case:event.target.value})}/></label>
      <section className="advanced-rule-list"><h4>Optional assumption thresholds</h4>{assumptions.map((item,index)=><div key={item.id||index}><strong>{item.description||`Assumption ${index+1}`}</strong><input aria-label={`Metric for assumption ${index+1}`} value={item.metric||""} onChange={event=>setAssumption(index,{metric:event.target.value||null})} placeholder="Metric"/><select aria-label={`Operator for assumption ${index+1}`} value={item.operator||""} onChange={event=>setAssumption(index,{operator:(event.target.value||null) as ThesisAssumption["operator"]})}><option value="">No rule</option>{[">",">=","<","<=","=","!="].map(value=><option key={value}>{value}</option>)}</select><input aria-label={`Target for assumption ${index+1}`} type="number" step="any" value={item.target_value??""} onChange={event=>setAssumption(index,{target_value:event.target.value===""?null:Number(event.target.value)})} placeholder="Target"/><input aria-label={`Unit for assumption ${index+1}`} value={item.unit||""} onChange={event=>setAssumption(index,{unit:event.target.value||null})} placeholder="Unit"/></div>)}</section>
    </details>
    <label className="thesis-confirmation"><input type="checkbox" checked={reviewConfirmed} onChange={event=>setReviewConfirmed(event.target.checked)}/><span><strong>I reviewed this thesis and want to save it as my investment belief.</strong><small>EagleEyes suggestions are not treated as your belief until you confirm this box.</small></span></label>
    <footer><small>{selected?"Saving creates a new thesis version; the earlier version remains in decision history.":"No investment decision is recorded automatically. You can save a WATCH thesis or decide to do nothing."}</small><button className="primary" disabled={saving||!reviewConfirmed||!form.summary.trim()}>{saving?"Saving…":selected?"Confirm and save new version":"Confirm and save thesis"}</button></footer>
  </section>;
}
