"use client";

import {useEffect,useState} from "react";
import Link from "next/link";
import type {LearningLesson} from "../../lib/learning";

function MarkdownText({content}:{content:string}){const blocks=content.trim().split(/\n\s*\n/);return <div className="lesson-markdown">{blocks.map((block,index)=>{if(block.startsWith("# "))return <h1 key={index}>{block.slice(2)}</h1>;if(block.startsWith("## "))return <h3 key={index}>{block.slice(3)}</h3>;if(block.split("\n").every(line=>line.startsWith("- ")))return <ul key={index}>{block.split("\n").map(line=><li key={line}>{line.slice(2)}</li>)}</ul>;return <p key={index}>{block}</p>})}</div>}

export function LearnPublicPreview({apiUrl,onSignIn}:{apiUrl:string;onSignIn:()=>void}){const [lesson,setLesson]=useState<LearningLesson|null>(null);const [error,setError]=useState("");useEffect(()=>{fetch(`${apiUrl}/learn/lessons/why-invest`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(typeof data?.detail==="string"?data.detail:"Preview unavailable");setLesson(data)}).catch(reason=>setError(reason.message));},[apiUrl]);return <main className="public-learn"><header><Link href="/">EA <b>EagleEyes</b></Link><button onClick={onSignIn}>Sign in</button></header><section className="public-learn-hero"><span>Investing education grounded in evidence</span><h1>Learn the basics before taking market risk.</h1><p>Short lessons, transparent calculators, private mastery, and a source-grounded tutor for first-time investors.</p><button className="primary" onClick={onSignIn}>Create an account to start learning</button></section><section className="public-learn-paths"><article><b>01</b><h2>Start safely</h2><p>Cash needs, debt, accounts, compounding, inflation, and investment types.</p></article><article><b>02</b><h2>Build a portfolio</h2><p>Risk, diversification, ETF overlap, fees, rebalancing, and declines.</p></article><article><b>03</b><h2>Understand markets</h2><p>Prices, expectations, fundamentals, valuation, macro conditions, and evidence quality.</p></article></section><section className="public-preview-lesson"><span>Free preview</span>{lesson?<><MarkdownText content={lesson.content}/><div className="lesson-sources"><h3>Reviewed sources</h3>{lesson.sources.map(source=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">{source.publisher} · {source.title}</a>)}</div></>:<p>{error||"Opening the preview…"}</p>}<button className="primary" onClick={onSignIn}>Continue the full path</button></section></main>}
