"use client";

import { FormEvent, useEffect, useState } from "react";
import type { LearningCatalog, LearningLesson, LearningPreferences, LearningProgress } from "../../lib/learning";

type RequestFn=(path:string,init?:RequestInit)=>Promise<Response>;

const LABS:Record<string,{title:string;description:string;fields:Array<{key:string;label:string;default:string;kind?:"text"}>}>={
  "compound-growth":{title:"Compound growth",description:"Compare contributions with modeled growth under a constant illustrative return.",fields:[{key:"initial",label:"Starting amount",default:"1000"},{key:"monthly",label:"Monthly contribution",default:"200"},{key:"years",label:"Years",default:"20"},{key:"annual_return",label:"Illustrative annual return (decimal)",default:"0.07"}]},
  inflation:{title:"Purchasing power",description:"See how constant inflation would change the purchasing power of a fixed amount.",fields:[{key:"amount",label:"Amount today",default:"10000"},{key:"years",label:"Years",default:"20"},{key:"inflation_rate",label:"Inflation rate (decimal)",default:"0.025"}]},
  "fee-drag":{title:"Fee drag",description:"Compare two constant expense assumptions over the same illustrative return path.",fields:[{key:"initial",label:"Starting amount",default:"10000"},{key:"years",label:"Years",default:"30"},{key:"annual_return",label:"Illustrative annual return",default:"0.07"},{key:"low_fee",label:"Lower expense ratio",default:"0.0005"},{key:"high_fee",label:"Higher expense ratio",default:"0.01"}]},
  "drawdown-recovery":{title:"Drawdown recovery",description:"Calculate the gain required to recover from a decline.",fields:[{key:"decline",label:"Decline (decimal)",default:"0.30"}]},
  "contribution-timing":{title:"Starting now versus later",description:"Compare the same monthly contribution with a delayed start.",fields:[{key:"monthly",label:"Monthly contribution",default:"200"},{key:"years",label:"Total horizon",default:"30"},{key:"delay_years",label:"Delay in years",default:"5"},{key:"annual_return",label:"Illustrative annual return",default:"0.07"}]},
  diversification:{title:"Diversification sketch",description:"See why position count alone does not determine diversification.",fields:[{key:"positions",label:"Number of positions",default:"5"},{key:"largest_weight",label:"Largest weight (decimal)",default:"0.40"},{key:"average_correlation",label:"Illustrative average correlation",default:"0.65"}]},
  "etf-overlap":{title:"ETF overlap sketch",description:"Compare two equal-weight lists. EagleEyes uses dated holding weights when available.",fields:[{key:"first_holdings",label:"First holdings (comma separated)",default:"AAPL,MSFT,NVDA",kind:"text"},{key:"second_holdings",label:"Second holdings (comma separated)",default:"MSFT,NVDA,AMZN",kind:"text"}]},
};

function errorText(data:unknown,fallback:string){return typeof (data as {detail?:unknown})?.detail==="string"?(data as {detail:string}).detail:fallback;}

export function LearnPage({request,moduleSlug,lessonId,onOpenLesson,onOpenHub,onDeepLink}:{request:RequestFn;moduleSlug?:string;lessonId?:string;onOpenLesson:(module:string,lesson:string)=>void;onOpenHub:()=>void;onDeepLink:(path:string)=>void}){
  const [catalog,setCatalog]=useState<LearningCatalog|null>(null);
  const [lesson,setLesson]=useState<LearningLesson|null>(null);
  const [progress,setProgress]=useState<LearningProgress[]>([]);
  const [preferences,setPreferences]=useState<LearningPreferences>({selected_path:null,knowledge_level:"beginner",interests:[],portfolio_context_enabled:false});
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{let active=true;request("/learn/catalog").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(errorText(data,"Learning catalog is unavailable"));if(active){setCatalog(data);setProgress(data.progress||[]);setPreferences(data.preferences||preferences);}}).catch(reason=>active&&setError(reason.message));return()=>{active=false};},[request]);
  useEffect(()=>{if(!lessonId){setLesson(null);return;}let active=true;setBusy(true);request(`/learn/lessons/${lessonId}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(errorText(data,"Lesson is unavailable"));if(active)setLesson(data);}).catch(reason=>active&&setError(reason.message)).finally(()=>active&&setBusy(false));return()=>{active=false};},[lessonId,request]);
  async function refreshProgress(){const response=await request("/learn/progress");if(response.ok)setProgress(await response.json());}
  async function savePreferences(next:LearningPreferences){setPreferences(next);const response=await request("/learn/preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(!response.ok)setError(errorText(await response.json(),"Unable to save learning preferences"));}
  async function saveProgress(nextStatus:LearningProgress["status"],completion:number){if(!lesson)return;setBusy(true);const response=await request(`/learn/progress/${lesson.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({module_id:lesson.module_id,content_version:lesson.content_version,status:nextStatus,completion_percentage:completion})});if(response.ok)await refreshProgress();else setError(errorText(await response.json(),"Unable to save lesson progress"));setBusy(false);}
  if(error&&!catalog)return <section className="workspace learn-workspace"><div className="empty-state"><h2>Learning is temporarily unavailable</h2><p>{error}</p></div></section>;
  if(lessonId)return <LessonView lesson={lesson} busy={busy} error={error} request={request} progress={progress} portfolioContext={preferences.portfolio_context_enabled} onBack={onOpenHub} onDeepLink={onDeepLink} onSaveProgress={saveProgress} onRefreshProgress={refreshProgress} catalog={catalog} onNext={onOpenLesson}/>;
  const preferredLessonIds=catalog?.modules.find(item=>item.id===preferences.selected_path)?.lesson_ids||[];
  const recommendedLessons=[...(catalog?.lessons.filter(item=>preferredLessonIds.includes(item.id))||[]),...(catalog?.lessons.filter(item=>!preferredLessonIds.includes(item.id))||[])];
  const currentLesson=recommendedLessons.find(item=>!progress.some(row=>row.lesson_id===item.id&&row.content_version===item.content_version&&row.status==="mastered"));
  const mastered=progress.filter(item=>item.status==="mastered").length;
  const conceptState=new Map<string,"not_started"|"developing"|"mastered">();
  for(const item of catalog?.lessons||[]){const row=progress.find(progressRow=>progressRow.lesson_id===item.id&&progressRow.content_version===item.content_version);const state=row?.status==="mastered"?"mastered":row?"developing":"not_started";for(const concept of item.concept_ids){const current=conceptState.get(concept);if(current!=="mastered"&&(current!=="developing"||state==="mastered"))conceptState.set(concept,state);}}
  const conceptGroups={mastered:[] as string[],developing:[] as string[],not_started:[] as string[]};for(const [concept,state] of conceptState)conceptGroups[state].push(concept);
  return <section className="workspace learn-workspace" data-testid="learn-hub">
    <div className="learn-hero"><div><span className="kicker">Build confidence before complexity</span><h2>Learn how investing works, then inspect the evidence yourself.</h2><p>Short lessons, deterministic practice, and a source-grounded tutor. No public leaderboard, trade signals, or guaranteed outcomes.</p><div className="learn-hero-actions">{currentLesson&&<button className="primary" onClick={()=>onOpenLesson(currentLesson.module_id,currentLesson.id)}>Continue: {currentLesson.title} →</button>}<button className="secondary" onClick={()=>onOpenLesson("start-safely",catalog?.preview_lesson_id||"why-invest")}>Start the foundation</button></div></div><div className="mastery-summary"><span>Private mastery</span><strong>{mastered}<small> concepts completed</small></strong><p>Your progress belongs to this EagleEyes account.</p></div></div>
    <div className="learn-settings panel"><div><h3>Shape the path</h3><p>This changes lesson order, not investment calculations.</p></div><label>Starting confidence<select value={preferences.knowledge_level} onChange={event=>void savePreferences({...preferences,knowledge_level:event.target.value as LearningPreferences["knowledge_level"]})}><option value="beginner">New to investing</option><option value="developing">Know the basics</option><option value="confident">Ready to deepen research</option></select></label><label className="check-row"><input type="checkbox" checked={preferences.portfolio_context_enabled} onChange={event=>void savePreferences({...preferences,portfolio_context_enabled:event.target.checked})}/><span>Allow explicit “use my portfolio” exercises<small>Off by default. Lessons remain educational.</small></span></label></div>
    <div className="concept-mastery-grid" aria-label="Concept mastery status"><article><span>Mastered</span><strong>{conceptGroups.mastered.length}</strong><p>{conceptGroups.mastered.slice(0,4).map(item=>item.replaceAll("-"," ")).join(" · ")||"Complete a lesson and score at least 80%."}</p></article><article><span>Developing</span><strong>{conceptGroups.developing.length}</strong><p>{conceptGroups.developing.slice(0,4).map(item=>item.replaceAll("-"," ")).join(" · ")||"Concepts appear here after you begin a lesson."}</p></article><article><span>Not started</span><strong>{conceptGroups.not_started.length}</strong><p>{conceptGroups.not_started.slice(0,4).map(item=>item.replaceAll("-"," ")).join(" · ")||"Your current curriculum is complete."}</p></article></div>
    <div className="learning-path-grid">{catalog?.modules.map((module,index)=>{const rows=module.lesson_ids.map(id=>catalog.lessons.find(item=>item.id===id)).filter(Boolean);const completed=rows.filter(item=>progress.some(row=>row.lesson_id===item?.id&&row.status==="mastered")).length;return <article key={module.id} className={`learning-path-card ${preferences.selected_path===module.id?"selected":""}`}><header><span>Path {index+1}</span><b>{completed}/{rows.length} mastered</b></header><h3>{module.title}</h3><p>{module.description}</p><ul>{module.outcomes.map(item=><li key={item}>{item}</li>)}</ul><div className="lesson-list">{rows.map(item=>item&&<button key={item.id} onClick={()=>onOpenLesson(module.slug,item.id)}><span className={`mastery-dot ${progress.find(row=>row.lesson_id===item.id)?.status||"not_started"}`}/><span><b>{item.title}</b><small>{item.estimated_minutes} min · {item.lab_ids.length?`${item.lab_ids.length} practice lab${item.lab_ids.length===1?"":"s"}`:"knowledge check"}</small></span><i>→</i></button>)}</div><button className="secondary" onClick={()=>void savePreferences({...preferences,selected_path:module.id})}>{preferences.selected_path===module.id?"Selected path":"Make this my path"}</button></article>})}</div>
    <div className="learn-practice panel"><div><span className="kicker">Practice before portfolio decisions</span><h3>Seven transparent learning labs</h3><p>Every output shows its inputs, formula version, assumptions, and educational limitation.</p></div><div>{Object.entries(LABS).map(([id,lab])=><span key={id}>{lab.title}</span>)}</div></div>
  </section>;
}

function LessonView({lesson,busy,error,request,progress,portfolioContext,onBack,onDeepLink,onSaveProgress,onRefreshProgress,catalog,onNext}:{lesson:LearningLesson|null;busy:boolean;error:string;request:RequestFn;progress:LearningProgress[];portfolioContext:boolean;onBack:()=>void;onDeepLink:(path:string)=>void;onSaveProgress:(status:LearningProgress["status"],completion:number)=>Promise<void>;onRefreshProgress:()=>Promise<void>;catalog:LearningCatalog|null;onNext:(module:string,lesson:string)=>void}){
  if(busy&&!lesson)return <section className="workspace learn-workspace"><div className="learn-loading">Opening lesson…</div></section>;
  if(!lesson)return <section className="workspace learn-workspace"><button className="text-button" onClick={onBack}>← Learning hub</button><div className="empty-state"><h2>Lesson unavailable</h2><p>{error||"Choose another lesson from the learning hub."}</p></div></section>;
  const row=progress.find(item=>item.lesson_id===lesson.id&&item.content_version===lesson.content_version);
  const module=catalog?.modules.find(item=>item.id===lesson.module_id);const index=module?.lesson_ids.indexOf(lesson.id)??-1;const nextId=index>=0?module?.lesson_ids[index+1]:undefined;
  return <section className="workspace learn-workspace lesson-workspace" data-testid="learn-lesson"><button className="text-button" onClick={onBack}>← Learning hub</button><div className="lesson-header"><div><span className="kicker">{module?.title||"EagleEyes Learn"}</span><h2>{lesson.title}</h2><p>{lesson.estimated_minutes} minutes · {lesson.sources.length} authoritative sources · content {lesson.content_version}</p></div><div className={`mastery-badge ${row?.status||"not_started"}`}>{(row?.status||"not started").replaceAll("_"," ")}</div></div>
    <div className="lesson-layout"><article className="lesson-reading"><MarkdownText content={lesson.content}/><div className="lesson-links"><h3>See this in EagleEyes</h3><p>Open validated research without turning the lesson into a recommendation.</p>{lesson.eagleeyes_links.map(link=><button key={link.route} className="secondary" onClick={()=>onDeepLink(link.route)}>{link.label} →</button>)}{portfolioContext&&<p className="portfolio-context-note">Portfolio context is enabled. It is used only after an exercise explicitly asks for it.</p>}</div><div className="lesson-sources"><h3>Sources</h3>{lesson.sources.map(source=><a key={source.id} href={source.url} target="_blank" rel="noreferrer"><span>{source.publisher}</span>{source.title}</a>)}</div></article><aside><div className="lesson-actions panel"><span>Lesson progress</span><p>Complete the reading and knowledge check. Mastery requires at least 80%.</p><button className="primary" disabled={busy} onClick={()=>void onSaveProgress("completed",1)}>Mark lesson complete</button></div><Tutor lesson={lesson} request={request}/></aside></div>
    {lesson.lab_ids.map(id=><LearningLab key={id} labId={id} request={request}/>)}
    {lesson.quiz&&<LearningQuiz lesson={lesson} request={request} onComplete={onRefreshProgress}/>}
    <div className="lesson-next panel"><div><span>Next step</span><h3>{nextId?catalog?.lessons.find(item=>item.id===nextId)?.title:"Return to your learning map"}</h3></div><button className="primary" onClick={()=>nextId?onNext(lesson.module_id,nextId):onBack()}>{nextId?"Continue lesson →":"View learning map →"}</button></div>
  </section>;
}

function MarkdownText({content}:{content:string}){const blocks=content.trim().split(/\n\s*\n/);return <div className="lesson-markdown">{blocks.map((block,index)=>{if(block.startsWith("# "))return <h1 key={index}>{block.slice(2)}</h1>;if(block.startsWith("## "))return <h3 key={index}>{block.slice(3)}</h3>;if(block.split("\n").every(line=>line.startsWith("- ")))return <ul key={index}>{block.split("\n").map(line=><li key={line}>{line.slice(2)}</li>)}</ul>;return <p key={index}>{block}</p>})}</div>}

function LearningLab({labId,request}:{labId:string;request:RequestFn}){const lab=LABS[labId];const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries((lab?.fields||[]).map(field=>[field.key,field.default])));const [result,setResult]=useState<{result:Record<string,unknown>;assumptions:string[];calculation_version:string;warning:string}|null>(null);const [error,setError]=useState("");if(!lab)return null;async function calculate(event:FormEvent){event.preventDefault();setError("");const inputs=Object.fromEntries(lab.fields.map(field=>[field.key,field.kind==="text"?values[field.key].split(",").map(item=>item.trim()).filter(Boolean):Number(values[field.key])]));const response=await request(`/learn/labs/${labId}/calculate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({inputs})});const data=await response.json();if(!response.ok){setError(errorText(data,"Unable to calculate this lab"));return;}setResult(data)}return <section className="learning-lab"><div><span className="kicker">Practice lab</span><h3>{lab.title}</h3><p>{lab.description}</p></div><form onSubmit={calculate}>{lab.fields.map(field=><label key={field.key}>{field.label}<input type={field.kind==="text"?"text":"number"} step="any" value={values[field.key]} onChange={event=>setValues({...values,[field.key]:event.target.value})}/></label>)}<button className="primary">Calculate illustration</button></form>{error&&<p className="learn-error">{error}</p>}{result&&<div className="lab-result"><div>{Object.entries(result.result).map(([key,value])=><p key={key}><span>{key.replaceAll("_"," ")}</span><strong>{Array.isArray(value)?value.join(", ")||"None":typeof value==="number"?value.toLocaleString(undefined,{maximumFractionDigits:4}):String(value)}</strong></p>)}</div><details><summary>Method and assumptions</summary><small>{result.calculation_version}</small><ul>{result.assumptions.map(item=><li key={item}>{item}</li>)}</ul><p>{result.warning}</p></details></div>}</section>}

function LearningQuiz({lesson,request,onComplete}:{lesson:LearningLesson;request:RequestFn;onComplete:()=>Promise<void>}){const quiz=lesson.quiz!;const [answers,setAnswers]=useState<number[]>(Array(quiz.questions.length).fill(-1));const [result,setResult]=useState<{score:number;total_questions:number;percentage:number;mastery_eligible:boolean;feedback:Array<{correct:boolean;correct_index:number;explanation:string}>}|null>(null);const [error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();if(answers.some(answer=>answer<0)){setError("Answer every question before submitting.");return;}const response=await request(`/learn/quizzes/${quiz.id}/attempts`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers})});const data=await response.json();if(!response.ok){setError(errorText(data,"Unable to submit knowledge check"));return;}setResult(data);await onComplete()}return <section className="learning-quiz"><span className="kicker">Knowledge check</span><h3>Explain it back to yourself</h3><form onSubmit={submit}>{quiz.questions.map((question,qIndex)=><fieldset key={question.question}><legend>{question.question}</legend>{question.options.map((option,oIndex)=><label key={option}><input type="radio" name={`q-${qIndex}`} checked={answers[qIndex]===oIndex} onChange={()=>setAnswers(answers.map((value,index)=>index===qIndex?oIndex:value))}/><span>{option}</span></label>)}{result&&<p className={result.feedback[qIndex].correct?"correct":"incorrect"}>{result.feedback[qIndex].explanation}</p>}</fieldset>)}{error&&<p className="learn-error">{error}</p>}<button className="primary">Submit knowledge check</button></form>{result&&<div className="quiz-result"><strong>{result.score}/{result.total_questions}</strong><span>{result.mastery_eligible?"Mastery score reached":"Review the explanations and try again"}</span></div>}</section>}

function Tutor({lesson,request}:{lesson:LearningLesson;request:RequestFn}){const [thread,setThread]=useState<string|null>(null);const [messages,setMessages]=useState<Array<{role:string;content:string}>>([]);const [question,setQuestion]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();if(!question.trim()||busy)return;setBusy(true);setError("");let threadId=thread;if(!threadId){const response=await request("/learn/tutor/threads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lesson_id:lesson.id,title:lesson.title})});const data=await response.json();if(!response.ok){setError(errorText(data,"Unable to open the tutor"));setBusy(false);return;}threadId=data.id;setThread(threadId)}const prompt=question.trim();setQuestion("");setMessages(items=>[...items,{role:"user",content:prompt}]);const response=await request(`/learn/tutor/threads/${threadId}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:prompt})});const data=await response.json();if(response.ok)setMessages(items=>[...items,data.message]);else setError(errorText(data,"Tutor answer unavailable"));setBusy(false)}return <div className="lesson-tutor panel"><span className="kicker">Lesson tutor</span><h3>Ask about this concept</h3><p>Answers use only this lesson and its cited sources. The tutor cannot pick stocks or calculate a new result.</p><div className="tutor-messages">{messages.map((message,index)=><div key={index} className={message.role}>{message.content}</div>)}{busy&&<div className="assistant">Reviewing the lesson sources…</div>}</div>{error&&<p className="learn-error">{error}</p>}<form onSubmit={submit}><textarea value={question} onChange={event=>setQuestion(event.target.value)} placeholder="What is the difference between risk tolerance and loss capacity?"/><button className="primary" disabled={busy}>Ask tutor</button></form></div>}

export function LearnPublicPreview({apiUrl,onSignIn}:{apiUrl:string;onSignIn:()=>void}){const [lesson,setLesson]=useState<LearningLesson|null>(null);const [error,setError]=useState("");useEffect(()=>{fetch(`${apiUrl}/learn/lessons/why-invest`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(errorText(data,"Preview unavailable"));setLesson(data)}).catch(reason=>setError(reason.message));},[apiUrl]);return <main className="public-learn"><header><a href="/">EA <b>EagleEyes</b></a><button onClick={onSignIn}>Sign in</button></header><section className="public-learn-hero"><span>Investing education grounded in evidence</span><h1>Learn the basics before taking market risk.</h1><p>Short lessons, transparent calculators, private mastery, and a source-grounded tutor for first-time investors.</p><button className="primary" onClick={onSignIn}>Create an account to start learning</button></section><section className="public-learn-paths"><article><b>01</b><h2>Start safely</h2><p>Cash needs, debt, accounts, compounding, inflation, and investment types.</p></article><article><b>02</b><h2>Build a portfolio</h2><p>Risk, diversification, ETF overlap, fees, rebalancing, and declines.</p></article><article><b>03</b><h2>Understand markets</h2><p>Prices, expectations, fundamentals, valuation, macro conditions, and evidence quality.</p></article></section><section className="public-preview-lesson"><span>Free preview</span>{lesson?<><MarkdownText content={lesson.content}/><div className="lesson-sources"><h3>Reviewed sources</h3>{lesson.sources.map(source=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">{source.publisher} · {source.title}</a>)}</div></>:<p>{error||"Opening the preview…"}</p>}<button className="primary" onClick={onSignIn}>Continue the full path</button></section></main>}
