"use client";

import { useState } from "react";
import type { Holding, Profile } from "../shared/workspace-implementations";

type RequestFn=(path:string,init?:RequestInit)=>Promise<Response>;
type Allocation={ticker:string;name?:string;company?:string;issuer?:string;category?:string;sector?:string;target_range:number[];reference_weight:number;expense_ratio?:number;marginal_contribution_to_risk?:number;what_it_contributes?:string;included_because?:string};
type BuilderResult={id:string;model_version:string;objective:string;universe:{requested:string[];eligible:string[];excluded:Array<{ticker:string;reason:string}>;count:number};allocations:Allocation[];portfolio_metrics:{annual_return?:number|null;volatility?:number|null;sharpe_ratio?:number|null;maximum_drawdown?:number|null};benchmarks:Array<{name:string;annual_return?:number|null;volatility?:number|null;sharpe_ratio?:number|null;maximum_drawdown?:number|null}>;constraints:{status:string;diagnostics:string[]};warnings:string[];expected_expense_dollars_year_one?:number;overlap?:Array<{left:string;right:string;overlap_weight:number;shared_holdings:number}>};
type SimulationSummary={model_version:string;shared_path_fingerprint:string;outcomes:Array<{strategy_key:string;label:string;wealth_percentiles:Record<string,number>;real_wealth_percentiles?:Record<string,number>;drawdown_percentiles:Record<string,number>}>};
const pct=(value?:number|null)=>value==null?"—":`${(value*100).toFixed(1)}%`;
const money=(value?:number|null)=>value==null?"—":new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);

function Results({result,type,onSimulate,simulation,simulationBusy}:{result:BuilderResult;type:"ETF"|"Stock";onSimulate:()=>void;simulation:SimulationSummary|null;simulationBusy:boolean}){
  return <section className="builder-results"><header><div><span>Decision frontier input</span><h3>{type} research allocation</h3><p>{result.universe.count} eligible of {result.universe.requested.length} requested · {result.objective.replaceAll("_"," ")}</p></div><b className={result.constraints.status==="satisfied"?"good":"risk"}>{result.constraints.status}</b></header>
    <div className="builder-metrics"><p><span>Expected historical return</span><strong>{pct(result.portfolio_metrics.annual_return)}</strong></p><p><span>Volatility</span><strong>{pct(result.portfolio_metrics.volatility)}</strong></p><p><span>Sharpe ratio</span><strong>{result.portfolio_metrics.sharpe_ratio?.toFixed(2)??"—"}</strong></p><p><span>Historical max drawdown</span><strong>{pct(result.portfolio_metrics.maximum_drawdown)}</strong></p>{type==="ETF"&&<p><span>Estimated first-year expenses</span><strong>{money(result.expected_expense_dollars_year_one)}</strong></p>}</div>
    <div className="builder-allocation-table"><div><b>Security</b><b>Target range</b><b>Reference</b><b>{type==="ETF"?"Cost":"Risk contribution"}</b><b>Role</b></div>{result.allocations.map(row=><div key={row.ticker}><strong>{row.ticker}<small>{row.name||row.company||row.category}</small></strong><span>{pct(row.target_range[0])}–{pct(row.target_range[1])}</span><span>{pct(row.reference_weight)}</span><span>{type==="ETF"?pct(row.expense_ratio):pct(row.marginal_contribution_to_risk)}</span><span>{row.what_it_contributes||row.included_because}</span></div>)}</div>
    {!!result.benchmarks.length&&<div className="builder-benchmarks"><span>Benchmarks</span>{result.benchmarks.map(row=><p key={row.name}><strong>{row.name}</strong><small>{pct(row.annual_return)} return · {pct(row.volatility)} volatility · {row.sharpe_ratio?.toFixed(2)??"—"} Sharpe</small></p>)}</div>}
    {!!result.overlap?.length&&<details><summary>ETF overlap and duplicate holdings</summary>{result.overlap.slice(0,10).map(row=><p key={`${row.left}-${row.right}`}><b>{row.left} / {row.right}</b> {pct(row.overlap_weight)} overlap across {row.shared_holdings} holdings</p>)}</details>}
    {!!result.universe.excluded.length&&<details className="warning"><summary>Excluded funds or securities ({result.universe.excluded.length})</summary>{result.universe.excluded.map(row=><p key={row.ticker}><b>{row.ticker}</b> — {row.reason}</p>)}</details>}
    <div className="builder-simulation-bridge"><div><span>Use the shared engine</span><strong>Compare this allocation on the same 5,000 market paths.</strong><small>The builder reference weights become a research input. No trades are submitted.</small></div><button className="secondary" disabled={simulationBusy||result.constraints.status!=="satisfied"} onClick={onSimulate}>{simulationBusy?"Running paired paths…":"Send to Decision Lab"}</button></div>
    {simulation&&<div className="builder-simulation-result"><span>Paired paths {simulation.shared_path_fingerprint}</span>{simulation.outcomes.filter(row=>["current","risk_controlled","balanced"].includes(row.strategy_key)).map(row=><p key={row.strategy_key}><strong>{row.label}</strong><b>{money(row.wealth_percentiles.p50)}</b><small>today’s dollars {money(row.real_wealth_percentiles?.p50)} · modeled drawdown {pct(row.drawdown_percentiles.p10)}</small></p>)}<small>{simulation.model_version}</small></div>}
    <footer>Version {result.model_version}. Ranges surround a deterministic reference solution; this is research, not a trade instruction.</footer>
  </section>;
}

export function ETFAllocationBuilder({request,holdings,profile}:{request:RequestFn;holdings:Holding[];profile:Profile}){
  const [tickers,setTickers]=useState("VTI, VXUS, BND, QQQ, SCHD");const [objective,setObjective]=useState("balanced");const [maxExpense,setMaxExpense]=useState(.005);const [maxWeight,setMaxWeight]=useState(.40);const [result,setResult]=useState<BuilderResult|null>(null);const [simulation,setSimulation]=useState<SimulationSummary|null>(null);const [busy,setBusy]=useState(false);const [simulationBusy,setSimulationBusy]=useState(false);const [error,setError]=useState("");
  async function run(){setBusy(true);setError("");try{const response=await request("/builders/etf/optimize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({candidate_tickers:tickers.split(",").map(value=>value.trim().toUpperCase()).filter(Boolean),current_holdings:holdings,objective,time_horizon_years:profile.horizon_years,risk_tolerance:profile.risk_tolerance,loss_capacity:profile.loss_capacity,income_stability:profile.suitability_profile.income_stability,initial_investment:holdings.reduce((sum,row)=>sum+Number(row.market_value||0),0)||10000,annual_contribution:profile.annual_contribution,annual_withdrawal:profile.annual_withdrawal,account_type:profile.account_type,tax_rate:profile.tax_rate,max_expense_ratio:maxExpense,max_fund_weight:maxWeight})});const body=await response.json();if(!response.ok)throw new Error(body.detail||"ETF builder failed");setResult(body);}catch(reason){setError(reason instanceof Error?reason.message:"ETF builder failed");}finally{setBusy(false);}}
  async function simulate(){if(!result)return;setSimulationBusy(true);setError("");try{const response=await request("/simulations/runs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({holdings:result.allocations.map(row=>({ticker:row.ticker,weight:row.reference_weight,account_type:profile.account_type})),profile,paths:5000,block_months:6,seed:90210})});const body=await response.json();if(!response.ok)throw new Error(body.detail||"Simulation failed");setSimulation(body);}catch(reason){setError(reason instanceof Error?reason.message:"Simulation failed");}finally{setSimulationBusy(false);}}
  return <section className="workspace builder-workspace"><div className="section-intro"><div><span className="kicker">Guided ETF Allocation Builder</span><h2>Build a fund mix with costs and overlap visible.</h2><p>Choose the eligible funds and constraints. EagleEyes uses stored dated holdings and adjusted history—never frozen frontend assumptions.</p></div></div><div className="builder-controls panel"><label>ETF candidates<input value={tickers} onChange={event=>setTickers(event.target.value.toUpperCase())}/><small>Comma-separated U.S. ETF symbols</small></label><label>Objective<select value={objective} onChange={event=>setObjective(event.target.value)}><option value="balanced">Balanced tradeoff</option><option value="lower_downside">Lower downside</option><option value="growth">Growth</option><option value="income">Income</option><option value="lowest_cost">Lowest cost</option></select></label><label>Maximum expense ratio (%)<input type="number" step="0.05" value={maxExpense*100} onChange={event=>setMaxExpense(+event.target.value/100)}/></label><label>Maximum fund weight (%)<input type="number" value={maxWeight*100} onChange={event=>setMaxWeight(+event.target.value/100)}/></label><button className="primary" disabled={busy} onClick={()=>void run()}>{busy?"Reconciling history and holdings…":"Build ETF allocation"}</button></div>{error&&<div className="warning-strip"><span>{error}</span></div>}{result&&<Results result={result} type="ETF" onSimulate={()=>void simulate()} simulation={simulation} simulationBusy={simulationBusy}/>}</section>;
}

export function StockBasketBuilder({request,holdings,profile}:{request:RequestFn;holdings:Holding[];profile:Profile}){
  const [tickers,setTickers]=useState("AAPL, MSFT, NVDA, GOOGL, AMZN");const [objective,setObjective]=useState("diversification");const [benchmark,setBenchmark]=useState("SPY");const [maxWeight,setMaxWeight]=useState(.25);const [result,setResult]=useState<BuilderResult|null>(null);const [simulation,setSimulation]=useState<SimulationSummary|null>(null);const [busy,setBusy]=useState(false);const [simulationBusy,setSimulationBusy]=useState(false);const [error,setError]=useState("");
  async function run(){setBusy(true);setError("");try{const response=await request("/builders/stocks/optimize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({candidate_tickers:tickers.split(",").map(value=>value.trim().toUpperCase()).filter(Boolean),current_holdings:holdings,objective,benchmark,max_security_weight:maxWeight})});const body=await response.json();if(!response.ok)throw new Error(body.detail||"Stock builder failed");setResult(body);}catch(reason){setError(reason instanceof Error?reason.message:"Stock builder failed");}finally{setBusy(false);}}
  async function simulate(){if(!result)return;setSimulationBusy(true);setError("");try{const response=await request("/simulations/runs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({holdings:result.allocations.map(row=>({ticker:row.ticker,weight:row.reference_weight,account_type:profile.account_type})),profile,paths:5000,block_months:6,seed:90210})});const body=await response.json();if(!response.ok)throw new Error(body.detail||"Simulation failed");setSimulation(body);}catch(reason){setError(reason instanceof Error?reason.message:"Simulation failed");}finally{setSimulationBusy(false);}}
  return <section className="workspace builder-workspace"><div className="section-intro"><div><span className="kicker">Guided Stock Basket Builder</span><h2>Compare a disclosed stock universe under transparent constraints.</h2><p>Selections use adjusted history and EagleEyes research evidence. No trend-derived BUY, HOLD, or SELL labels are created.</p></div></div><div className="builder-controls panel"><label>Stock candidates<input value={tickers} onChange={event=>setTickers(event.target.value.toUpperCase())}/></label><label>Objective<select value={objective} onChange={event=>setObjective(event.target.value)}><option value="diversification">Diversification</option><option value="lower_downside">Lower downside</option><option value="quality_growth">Quality and growth</option><option value="value">Value</option><option value="income">Income</option><option value="macro_resilience">Macro resilience</option></select></label><label>Benchmark<input value={benchmark} onChange={event=>setBenchmark(event.target.value.toUpperCase())}/></label><label>Maximum stock weight (%)<input type="number" value={maxWeight*100} onChange={event=>setMaxWeight(+event.target.value/100)}/></label><button className="primary" disabled={busy} onClick={()=>void run()}>{busy?"Building paired comparisons…":"Build stock basket"}</button></div>{error&&<div className="warning-strip"><span>{error}</span></div>}{result&&<Results result={result} type="Stock" onSimulate={()=>void simulate()} simulation={simulation} simulationBusy={simulationBusy}/>}</section>;
}
