"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type Freshness={status:"daily"|"delayed"|"stale"|"unavailable";label:string;days_old:number|null};
type CatalogRow={ticker:string;name:string;issuer?:string|null;category?:string|null;asset_class?:string|null;strategy?:string|null;benchmark?:string|null;expense_ratio?:number|null;effective_at?:string|null;source_url?:string|null;holdings_as_of?:string|null;snapshot_holdings_count?:number|null;holdings_provider?:string|null;holdings_freshness:Freshness};
type Holding={constituent_ticker:string;weight:number;as_of:string;provider:string;source_url?:string|null};
type Exposure={exposure_type:string;exposure_name:string;weight:number;as_of:string;provider:string};
type Detail={catalog:CatalogRow;holdings:Holding[];exposures:Exposure[];holdings_freshness:Freshness;concentration:{holdings_count:number;top_10_weight:number;largest_holding?:Holding|null;hhi:number;effective_holdings?:number|null};snapshot_coverage:{reported_weight:number;coverage_percentage:number;unexplained_weight:number;over_reported_weight:number;within_tolerance:boolean;tolerance:number;treatment:string};portfolio_overlap:{weight:number;holdings:Holding[];funds:Array<{ticker:string;overlap_weight:number;shared_holdings:number}>};lineage:Array<{provider:string;dataset:string;effective_through?:string|null;source_url?:string|null}>;how_calculated:string};
type Payload={results:CatalogRow[];summary:{total:number;issuers:number;with_holdings:number};method:{universe:string}};
const pct=(value?:number|null)=>value==null?"Unavailable":`${(value*100).toFixed(2)}%`;
const dateLabel=(value?:string|null)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):"Unavailable";
function FreshnessBadge({value}:{value:Freshness}){return <span className={`etf-freshness ${value.status}`}>{value.label}{value.days_old!=null?` · ${value.days_old}d old`:""}</span>}

export function ETFResearch({request}:{request:(path:string,init?:RequestInit)=>Promise<Response>}){
  const requestRef=useRef(request);
  const [query,setQuery]=useState(""); const [payload,setPayload]=useState<Payload|null>(null); const [detail,setDetail]=useState<Detail|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
  async function open(ticker:string,preserveMessage=false){if(!preserveMessage)setMessage("");const response=await request(`/research/etfs/${ticker}`);if(!response.ok)throw new Error(await response.text());setDetail(await response.json());}
  async function search(event?:FormEvent){event?.preventDefault();setLoading(true);setMessage("");try{const response=await request(`/research/etfs?q=${encodeURIComponent(query)}&limit=100`);if(!response.ok)throw new Error(await response.text());const data=await response.json();setPayload(data);if(query.trim()&&data.results.length===1)await open(data.results[0].ticker);}catch(reason){setMessage(reason instanceof Error?reason.message:"ETF search failed");}finally{setLoading(false)}}
  async function refresh(){if(!detail)return;setLoading(true);try{const response=await request(`/research/etfs/${detail.catalog.ticker}/refresh`,{method:"POST"});const result=await response.json();if(!response.ok)throw new Error(result.detail||"Refresh failed");setMessage(result.reason||"Holdings refresh completed.");await open(detail.catalog.ticker,true);}catch(reason){setMessage(reason instanceof Error?reason.message:"Holdings refresh failed");}finally{setLoading(false)}}
  async function refreshCatalog(){setLoading(true);setMessage("");try{const response=await request("/research/etfs/refresh-catalog",{method:"POST"});const result=await response.json();if(!response.ok)throw new Error(result.detail||"ETF catalog refresh failed");setMessage(`ETF catalog refreshed: ${result.row_count??result.count??0} reference records processed.`);await search();}catch(reason){setMessage(reason instanceof Error?reason.message:"ETF catalog refresh failed");}finally{setLoading(false)}}
  useEffect(()=>{requestRef.current=request;},[request]);
  useEffect(()=>{let active=true;(async()=>{try{const response=await requestRef.current("/research/etfs?q=&limit=100");if(!response.ok)throw new Error(await response.text());if(active)setPayload(await response.json());}catch(reason){if(active)setMessage(reason instanceof Error?reason.message:"ETF search failed");}finally{if(active)setLoading(false);}})();return()=>{active=false};},[]);
  return <section className="workspace etf-workspace">
    <div className="section-intro"><div><span className="kicker">US-listed fund research</span><h2>Search ETFs by ticker, name, or issuer.</h2><p>Reference coverage and constituent coverage are separate. Every breakdown identifies its snapshot date and whether holdings are daily, delayed, stale, or unavailable.</p></div><button className="secondary" disabled={loading} onClick={()=>void refreshCatalog()}>↻ Refresh ETF catalog</button></div>
    <form className="etf-search panel" onSubmit={search}><label><span>ETF ticker, fund name, or issuer</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="QQQ, ARKK, iShares, Vanguard…"/></label><button className="primary" disabled={loading}>{loading?"Searching…":"Search ETFs"}</button></form>
    {message&&<div className="notice etf-notice">{message}</div>}
    {payload&&<div className="etf-catalog-summary panel"><div><span>Searchable catalog</span><strong>{payload.summary.total.toLocaleString()} ETFs</strong><small>{payload.summary.issuers.toLocaleString()} identified issuers</small></div><div><span>Stored breakdowns</span><strong>{payload.summary.with_holdings.toLocaleString()}</strong><small>Funds with a dated holdings snapshot</small></div><p>{payload.method.universe}</p></div>}
    <div className="etf-browser-grid"><div className="etf-results panel">{payload?.results.map(row=><button key={row.ticker} className={detail?.catalog.ticker===row.ticker?"active":""} onClick={()=>void open(row.ticker)}><div><strong>{row.ticker}</strong><span>{row.name}</span><small>{row.issuer||"Issuer not classified"}</small></div><div><FreshnessBadge value={row.holdings_freshness}/><small>{row.snapshot_holdings_count?`${row.snapshot_holdings_count} holdings · ${dateLabel(row.holdings_as_of)}`:"Reference record only"}</small></div></button>)}{!loading&&payload?.results.length===0&&<p>No active US ETF reference matched this search.</p>}</div>
      <div className="etf-detail">{!detail&&<div className="panel etf-empty"><strong>Select a fund to inspect it.</strong><p>Fund pages show holdings, sector look-through, concentration, portfolio overlap, fees, benchmark, freshness, and exact data limitations.</p></div>}{detail&&<>
        <article className="panel etf-hero"><header><div><span>{detail.catalog.issuer||"Issuer unavailable"}</span><h3>{detail.catalog.ticker} · {detail.catalog.name}</h3><p>{detail.catalog.category||detail.catalog.asset_class||"Category unavailable"}</p></div><FreshnessBadge value={detail.holdings_freshness}/></header><div className="etf-key-facts"><div><span>Expense ratio</span><strong>{pct(detail.catalog.expense_ratio)}</strong></div><div><span>Benchmark</span><strong>{detail.catalog.benchmark||"Unavailable"}</strong></div><div><span>Holdings snapshot</span><strong>{dateLabel(detail.holdings[0]?.as_of)}</strong></div><div><span>Provider</span><strong>{detail.holdings[0]?.provider||"Unavailable"}</strong></div></div><button onClick={()=>void refresh()} disabled={loading}>↻ Refresh holdings</button>{detail.catalog.source_url&&<a href={detail.catalog.source_url} target="_blank" rel="noreferrer">Open catalog source ↗</a>}</article>
        {detail.holdings.length===0?<article className="panel unavailable-panel"><h3>Constituent holdings unavailable</h3><p>The fund exists in the searchable catalog, but no connected provider returned a validated snapshot. It is not treated as a zero-holding fund. Try Refresh holdings; issuer feeds and ETF Global entitlement determine availability.</p></article>:<><article className="panel"><div className="panel-head"><div><span>Complete dated snapshot audit</span><h3>{detail.holdings.length} holdings as of {dateLabel(detail.holdings[0]?.as_of)}</h3></div><FreshnessBadge value={detail.holdings_freshness}/></div><div className={`etf-snapshot-coverage ${detail.snapshot_coverage.within_tolerance?"ready":"warning"}`}><strong>{pct(detail.snapshot_coverage.coverage_percentage)} of fund weight explained</strong><span>{pct(detail.snapshot_coverage.unexplained_weight)} unexplained · tolerance {pct(detail.snapshot_coverage.tolerance)}</span><small>{detail.snapshot_coverage.treatment}</small></div><div className="etf-holdings-table"><div><b>Security</b><b>Fund weight</b></div>{detail.holdings.map(row=><div key={row.constituent_ticker}><span>{row.constituent_ticker}</span><span>{pct(row.weight)}</span></div>)}</div></article>
          <div className="etf-analytics-grid"><article className="panel"><span>Concentration</span><h3>Top 10: {pct(detail.concentration.top_10_weight)}</h3><dl><div><dt>Largest holding</dt><dd>{detail.concentration.largest_holding?.constituent_ticker||"—"} · {pct(detail.concentration.largest_holding?.weight)}</dd></div><div><dt>Effective holdings</dt><dd>{detail.concentration.effective_holdings?.toFixed(1)||"—"}</dd></div><div><dt>HHI</dt><dd>{detail.concentration.hhi.toFixed(4)}</dd></div></dl></article>
          <article className="panel"><span>Portfolio overlap</span><h3>{pct(detail.portfolio_overlap.weight)} direct look-through</h3>{detail.portfolio_overlap.holdings.slice(0,8).map(row=><p key={row.constituent_ticker}><b>{row.constituent_ticker}</b><span>{pct(row.weight)} of fund</span></p>)}{detail.portfolio_overlap.funds.map(row=><p key={row.ticker}><b>{row.ticker} fund overlap</b><span>{pct(row.overlap_weight)} · {row.shared_holdings} shared</span></p>)}{!detail.portfolio_overlap.holdings.length&&!detail.portfolio_overlap.funds.length&&<small>No overlap could be measured against stored portfolio symbols.</small>}</article>
          <article className="panel"><span>Sector exposure</span><h3>Latest look-through</h3>{detail.exposures.filter(row=>row.exposure_type==="sector").map(row=><div className="etf-exposure" key={row.exposure_name}><span>{row.exposure_name}</span><b>{pct(row.weight)}</b><i><em style={{width:`${Math.min(100,row.weight*100)}%`}}/></i></div>)}{!detail.exposures.length&&<small>No classified constituent exposure is stored. Holdings remain available above.</small>}</article></div></>}
        <details className="panel method-details"><summary>How this was calculated</summary><p>{detail.how_calculated}</p>{detail.lineage.map(item=><p key={`${item.provider}-${item.dataset}`}><b>{item.provider}</b> · {item.dataset} · effective {dateLabel(item.effective_through)} {item.source_url&&<a href={item.source_url} target="_blank" rel="noreferrer">source ↗</a>}</p>)}</details>
      </>}</div></div>
  </section>;
}
