"use client";

import { useEffect, useMemo, useState } from "react";
import type { Holding, Profile } from "../shared/workspace-implementations";

type RequestFn=(path:string,init?:RequestInit)=>Promise<Response>;
type Alternative={label:string;weights:Record<string,number>;result?:{portfolio_metrics?:Record<string,number|null>;constraints?:{status:string;diagnostics:string[]};warnings?:string[]}|null};
type Comparison={version:string;status:string;universe:{requested:string[];analyzed:string[];funds:string[];stocks:string[];count:number;disclosure:string};alternatives:Record<string,Alternative>;warnings:string[]};
type Backtest={version:string;status:string;period?:{start:string;end:string;monthly_observations:number};results:Array<{key:string;label:string;annual_return:number|null;volatility:number|null;sharpe_ratio:number|null;maximum_drawdown:number|null;ending_growth_of_one:number|null}>;assumptions?:string[];warnings:string[]};
type ModelPortfolio={id:string;name:string;portfolio_type:"stocks"|"etfs"|"mixed";status:string;candidate_universe:Record<string,unknown>;basket:Array<{ticker:string;weight?:number}>;configuration:Record<string,unknown>;comparison_results:Comparison|Record<string,never>;backtest_results:Backtest|Record<string,never>;simulation_run_id?:string|null;converted_portfolio_id?:string|null;updated_at:string};

const pct=(value?:number|null)=>value==null?"—":`${(value*100).toFixed(1)}%`;
const money=(value?:number|null)=>value==null?"—":new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
const objectiveOrder=["equal_weight","lower_downside","balanced","quality_growth","value","income","custom"];
const objectiveCopy:Record<string,string>={equal_weight:"Same starting weight for every eligible security.",lower_downside:"Tilts toward lower historical covariance and volatility.",balanced:"Balances diversification, historical return and concentration.",quality_growth:"Uses available quality and growth evidence with risk controls.",value:"Uses available relative valuation evidence with risk controls.",income:"Prioritizes available income evidence; gaps stay explicit.",custom:"Uses your disclosed factor priorities."};

export function ModelPortfolioBuilder({request,profile}:{request:RequestFn;holdings:Holding[];profile:Profile}){
  const [type,setType]=useState<"stocks"|"etfs"|"mixed">("mixed");
  const [name,setName]=useState("My research portfolio");
  const [input,setInput]=useState("AAPL, MSFT, NVDA, VTI, BND");
  const [basket,setBasket]=useState<string[]>(["AAPL","MSFT","NVDA","VTI","BND"]);
  const [benchmark,setBenchmark]=useState("SPY");
  const [factorWeights,setFactorWeights]=useState({quality:.30,growth:.30,value:.20,income:.10,macro_resilience:.10});
  const [comparison,setComparison]=useState<Comparison|null>(null);
  const [selected,setSelected]=useState("balanced");
  const [backtest,setBacktest]=useState<Backtest|null>(null);
  const [simulation,setSimulation]=useState<any>(null);
  const [scenario,setScenario]=useState({economic_state:"unconditioned",inflation_state:"unconditioned",rate_state:"unconditioned",shock:"none"});
  const [models,setModels]=useState<ModelPortfolio[]>([]);
  const [modelId,setModelId]=useState<string|null>(null);
  const [busy,setBusy]=useState("");
  const [error,setError]=useState("");

  const selectedAlternative=comparison?.alternatives[selected];
  const universeDisclosure=comparison?.universe.disclosure||`Draft universe: ${basket.length} explicitly selected securities. EagleEyes ranks evidence only inside this list.`;
  const body=useMemo(()=>({name,portfolio_type:type,status:"saved",candidate_universe:comparison?.universe||{requested:basket,analyzed:basket,count:basket.length,disclosure:universeDisclosure},basket:basket.map(ticker=>({ticker,weight:selectedAlternative?.weights?.[ticker]})),configuration:{benchmark,selected_alternative:selected,factor_weights:factorWeights,scenario},comparison_results:comparison||{},backtest_results:backtest||{},simulation_run_id:simulation?.id||null}),[name,type,basket,comparison,universeDisclosure,selectedAlternative,benchmark,selected,factorWeights,scenario,backtest,simulation]);

  async function loadModels(){try{const response=await request("/model-portfolios");if(response.ok)setModels((await response.json()).model_portfolios||[]);}catch{/* The builder remains usable when saved-list retrieval fails. */}}
  useEffect(()=>{void loadModels();},[]);

  function addCandidates(){const values=input.split(/[\s,;]+/).map(value=>value.trim().toUpperCase()).filter(value=>/^[A-Z][A-Z0-9.-]{0,9}$/.test(value));setBasket(current=>Array.from(new Set([...current,...values])).slice(0,100));}
  function resetOutputs(){setComparison(null);setBacktest(null);setSimulation(null);setSelected("balanced");}
  async function compare(){setBusy("compare");setError("");try{const response=await request("/model-portfolios/compare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({portfolio_type:type,candidate_tickers:basket,benchmark,factor_weights:factorWeights,max_security_weight:Math.min(.60,Math.max(.35,1/Math.max(1,basket.length)))})});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Alternative comparison failed");setComparison(data);const preferred=data.alternatives.balanced?"balanced":Object.keys(data.alternatives)[0];setSelected(preferred);setBacktest(null);setSimulation(null);}catch(reason){setError(reason instanceof Error?reason.message:"Alternative comparison failed");}finally{setBusy("");}}
  async function runBacktest(){if(!comparison)return;setBusy("backtest");setError("");try{const alternatives=Object.fromEntries(Object.entries(comparison.alternatives).filter(([,item])=>Object.keys(item.weights||{}).length).map(([key,item])=>[key,item.weights]));const response=await request("/model-portfolios/backtest",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({alternatives,benchmark})});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Backtest failed");setBacktest(data);}catch(reason){setError(reason instanceof Error?reason.message:"Backtest failed");}finally{setBusy("");}}
  async function simulate(){if(!selectedAlternative?.weights)return;setBusy("simulate");setError("");try{const response=await request("/simulations/runs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({holdings:Object.entries(selectedAlternative.weights).map(([ticker,weight])=>({ticker,weight,account_type:profile.account_type})),profile,scenario:{economic_state:scenario.economic_state,inflation_state:scenario.inflation_state,rate_state:scenario.rate_state,shocks:scenario.shock==="none"?[]:[scenario.shock]},paths:5000,block_months:6,seed:90210})});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Simulation failed");setSimulation(data);}catch(reason){setError(reason instanceof Error?reason.message:"Simulation failed");}finally{setBusy("");}}
  async function save(status:"draft"|"saved"="saved"){setBusy("save");setError("");try{const response=await request(modelId?`/model-portfolios/${modelId}`:"/model-portfolios",{method:modelId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,status})});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Model portfolio could not be saved");setModelId(data.id);await loadModels();}catch(reason){setError(reason instanceof Error?reason.message:"Model portfolio could not be saved");}finally{setBusy("");}}
  async function convert(){if(!modelId)return;const confirmed=window.confirm("Copy the selected model weights into a tracked portfolio? This does not submit trades.");if(!confirmed)return;setBusy("convert");setError("");try{const response=await request(`/model-portfolios/${modelId}/convert`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,alternative_key:selected,initial_value:10000,account_type:profile.account_type})});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Conversion failed");await loadModels();window.history.pushState({},"","/portfolio");window.dispatchEvent(new PopStateEvent("popstate"));}catch(reason){setError(reason instanceof Error?reason.message:"Conversion failed");}finally{setBusy("");}}
  async function removeModel(id:string){if(!window.confirm("Delete this saved model portfolio? Tracked portfolios and immutable simulation runs are unchanged."))return;await request(`/model-portfolios/${id}`,{method:"DELETE"});if(modelId===id){setModelId(null);}await loadModels();}
  function openModel(model:ModelPortfolio){setModelId(model.id);setName(model.name);setType(model.portfolio_type);setBasket(model.basket.map(row=>row.ticker));setInput(model.basket.map(row=>row.ticker).join(", "));setComparison(Object.keys(model.comparison_results||{}).length?model.comparison_results as Comparison:null);setBacktest(Object.keys(model.backtest_results||{}).length?model.backtest_results as Backtest:null);setSelected(String(model.configuration.selected_alternative||"balanced"));setBenchmark(String(model.configuration.benchmark||"SPY"));setSimulation(model.simulation_run_id?{id:model.simulation_run_id,outcomes:[]}:null);}

  return <section className="workspace model-portfolio-workbench">
    <div className="section-intro"><div><span className="kicker">Start a portfolio</span><h2>Build evidence first. Track holdings only when you choose.</h2><p>Screen a disclosed universe, keep a persistent draft basket, compare transparent alternatives, backtest on common history, and stress the selected model.</p></div><a className="secondary button-link" href={`/ask?prompt=${encodeURIComponent(`Find candidates for a ${type} portfolio. Disclose the exact universe and show the strongest evidence within it—not universally best investments.`)}`}>Ask EagleEyes for candidates</a></div>
    <div className="portfolio-builder-flow" aria-label="Portfolio building workflow">{["Ask or screen","Draft basket","Build alternatives","Backtest","Stress + simulate","Save model"].map((label,index)=><div key={label} className={(index===0||basket.length>1&&index===1||comparison&&index<=2||backtest&&index<=3||simulation&&index<=4||modelId&&index<=5)?"complete":""}><i>{index+1}</i><span>{label}</span></div>)}</div>
    <div className="model-builder-grid">
      <aside className="panel model-saved-list"><header><span>Saved research models</span><button onClick={()=>{setModelId(null);setName("My research portfolio");resetOutputs();}}>+ New</button></header>{models.length?models.map(model=><article key={model.id} className={model.id===modelId?"active":""}><button onClick={()=>openModel(model)}><strong>{model.name}</strong><small>{model.portfolio_type} · {model.basket.length} securities · {model.status}</small></button><button aria-label={`Delete ${model.name}`} onClick={()=>void removeModel(model.id)}>×</button></article>):<p>No saved model portfolios yet.</p>}</aside>
      <div className="model-builder-main">
        <section className="panel model-basket-editor"><header><div><span>1 · Define the research universe</span><h3>{name}</h3></div><div className="model-draft-actions"><label>Name<input value={name} onChange={event=>setName(event.target.value)}/></label><button className="secondary" disabled={busy==="save"||basket.length<2} onClick={()=>void save("draft")}>{busy==="save"?"Saving…":"Save draft"}</button></div></header><div className="model-type-choice">{(["stocks","etfs","mixed"] as const).map(value=><button key={value} className={type===value?"active":""} onClick={()=>{setType(value);resetOutputs();}}><strong>{value==="stocks"?"Stocks":value==="etfs"?"ETFs":"Mixed"}</strong><small>{value==="stocks"?"Individual company basket":value==="etfs"?"Fund allocation with costs":"Stocks and ETFs together"}</small></button>)}</div><div className="basket-entry"><label>Tickers or symbols<input value={input} onChange={event=>setInput(event.target.value.toUpperCase())} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();addCandidates();}}}/></label><button className="secondary" onClick={addCandidates}>Add to basket</button></div><div className="basket-chips">{basket.map(ticker=><button key={ticker} title={`Remove ${ticker}`} onClick={()=>{setBasket(rows=>rows.filter(item=>item!==ticker));resetOutputs();}}>{ticker}<span>×</span></button>)}</div><div className="universe-disclosure"><strong>Analyzed universe</strong><p>{universeDisclosure}</p></div></section>
        <section className="panel model-alternative-controls"><header><div><span>2 · Build alternatives</span><h3>Compare different research objectives</h3></div><label>Benchmark<input value={benchmark} onChange={event=>setBenchmark(event.target.value.toUpperCase())}/></label></header><details><summary>User-defined factor blend</summary><div className="factor-sliders">{Object.entries(factorWeights).map(([key,value])=><label key={key}>{key.replaceAll("_"," ")}<input type="range" min="0" max="1" step=".05" value={value} onChange={event=>setFactorWeights(current=>({...current,[key]:+event.target.value}))}/><b>{Math.round(value*100)}%</b></label>)}</div></details><button className="primary" disabled={busy==="compare"||basket.length<2} onClick={()=>void compare()}>{busy==="compare"?"Building comparable alternatives…":"Build alternatives"}</button></section>
        {comparison&&<section className="model-alternatives"><div className="model-alternative-tabs">{objectiveOrder.filter(key=>comparison.alternatives[key]).map(key=><button key={key} className={selected===key?"active":""} onClick={()=>setSelected(key)}>{comparison.alternatives[key].label}</button>)}</div>{selectedAlternative&&<article className="panel"><header><div><span>Selected model</span><h3>{selectedAlternative.label}</h3><p>{objectiveCopy[selected]}</p></div><b>{Object.keys(selectedAlternative.weights).length} eligible</b></header><div className="model-weight-grid">{Object.entries(selectedAlternative.weights).sort((a,b)=>b[1]-a[1]).map(([ticker,weight])=><div key={ticker}><strong>{ticker}</strong><span>{pct(weight)}</span><i style={{width:`${Math.min(100,weight*100)}%`}}/></div>)}</div>{selectedAlternative.result?.constraints?.diagnostics?.length?<div className="warning-strip">{selectedAlternative.result.constraints.diagnostics.join(" ")}</div>:null}</article>} {comparison.warnings.map(item=><div className="warning-strip" key={item}>{item}</div>)}</section>}
        {comparison&&<section className="panel model-evaluation-actions"><div><span>3–5 · Test the basket</span><h3>Use identical history and shared forward paths.</h3><p>Backtests are hypothetical. Combine economic, inflation, rate, and independent shock conditions without forcing them into one regime.</p><div className="model-stress-controls"><label>Economy<select value={scenario.economic_state} onChange={event=>setScenario(current=>({...current,economic_state:event.target.value}))}><option value="unconditioned">Historical mix</option><option value="expansion">Expansion</option><option value="slowdown">Slowdown</option><option value="recession">Recession</option></select></label><label>Inflation<select value={scenario.inflation_state} onChange={event=>setScenario(current=>({...current,inflation_state:event.target.value}))}><option value="unconditioned">Historical mix</option><option value="cooling">Cooling</option><option value="stable">Stable</option><option value="accelerating">Accelerating</option></select></label><label>Rates<select value={scenario.rate_state} onChange={event=>setScenario(current=>({...current,rate_state:event.target.value}))}><option value="unconditioned">Historical mix</option><option value="easing">Easing</option><option value="stable">Stable</option><option value="tightening">Tightening</option></select></label><label>Shock<select value={scenario.shock} onChange={event=>setScenario(current=>({...current,shock:event.target.value}))}><option value="none">None</option><option value="oil">Oil</option><option value="credit">Credit</option><option value="geopolitical">Geopolitical</option></select></label></div></div><div><button className="secondary" disabled={busy==="backtest"} onClick={()=>void runBacktest()}>{busy==="backtest"?"Aligning common history…":"Backtest all alternatives"}</button><button className="secondary" disabled={!selectedAlternative||busy==="simulate"} onClick={()=>void simulate()}>{busy==="simulate"?"Running 5,000 paths…":"Stress + simulate selected"}</button></div></section>}
        {backtest&&<section className="panel model-backtest"><header><div><span>Historical comparison</span><h3>{backtest.period?`${backtest.period.start} to ${backtest.period.end}`:"Backtest unavailable"}</h3><p>{backtest.period?.monthly_observations||0} shared monthly observations · adjusted prices</p></div></header><div className="backtest-table"><div><b>Model</b><b>Annual return</b><b>Volatility</b><b>Sharpe</b><b>Max drawdown</b></div>{backtest.results.map(row=><div key={row.key}><strong>{row.label}</strong><span>{pct(row.annual_return)}</span><span>{pct(row.volatility)}</span><span>{row.sharpe_ratio?.toFixed(2)||"—"}</span><span>{pct(row.maximum_drawdown)}</span></div>)}</div>{backtest.warnings.map(item=><p className="warning-strip" key={item}>{item}</p>)}</section>}
        {simulation&&<section className="panel model-simulation"><header><div><span>Forward simulation</span><h3>{selectedAlternative?.label}</h3></div><a href="/decisions">Open Decision Lab →</a></header>{simulation.outcomes?.slice(0,6).map((row:any)=><article key={row.strategy_key}><strong>{row.label||row.strategy_key}</strong><b>{money(row.wealth_percentiles?.p50)}</b><small>{pct(row.probability_of_loss)} probability of loss · {pct(row.drawdown_percentiles?.p10)} modeled drawdown</small></article>)}{simulation.id&&<small>Stored immutable run {simulation.id}</small>}</section>}
        {error&&<div className="warning-strip">{error}</div>}
        <footer className="model-save-bar"><div><strong>{modelId?"Saved model portfolio":"Unsaved research model"}</strong><small>Saving does not change actual holdings or submit trades.</small></div><button className="primary" disabled={busy==="save"||!comparison} onClick={()=>void save("saved")}>{busy==="save"?"Saving…":modelId?"Update model portfolio":"Save model portfolio"}</button>{modelId&&<button className="secondary" disabled={busy==="convert"||!comparison} onClick={()=>void convert()}>{busy==="convert"?"Copying…":"Convert to tracked portfolio"}</button>}</footer>
      </div>
    </div>
  </section>;
}
