"use client";

/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect, react-hooks/refs, react-hooks/exhaustive-deps */

import { type FormEvent, type ReactNode, useEffect, useRef, useState } from "react";
import type { PresentationLevel } from "../../lib/presentation-level";

type Request = (path: string, init?: RequestInit) => Promise<Response>;
type Holding = { ticker: string; weight?: number | null; market_value?: number | null };
type ResearchField = {
  key: string; label: string; value: any; status: "AVAILABLE"|"STALE"|"UNAVAILABLE"|"PLAN_GATED"|"REQUIRES_CONTEXT"|"DATA_UNAVAILABLE"|"NOT_DISCLOSED"|"NOT_APPLICABLE"|"INSUFFICIENT_EVIDENCE"|"COMPUTATION_FAILED"|"DEPENDENCY_FAILED";
  evidence_type: string; provider?: string|null; source_url?: string|null; as_of?: string|null; freshness_policy?: string;
  formula?: string|null; methodology?: Record<string,any>|null; classification?: string; stale?: boolean; reason?:string|null; source_record?:string|null; retrieved_at?:string|null; input_evidence?:Array<Record<string,any>>;
};
type SectionState = { status:"SUCCESS"|"PARTIAL"|"UNAVAILABLE"; coverage:number; available_fields:string[]; missing_fields:string[]; plan_gated_fields:string[]; stale_fields:string[]; execution_status?:string; freshness_status?:string };
type CapabilityModel = { ticker:string; version:string; generated_at:string; status:string; coverage:number; fields:Record<string,ResearchField>; sections:Record<string,SectionState>; lineage?:Record<string,any> };
type Overview = { ticker:string; security?:Record<string,any>; membership:{holding:boolean;watchlist:boolean;holding_detail?:Holding|null}; missing_data?:string[]; partial:boolean; stage?:"header"|"core"|"full"; cache:{status:string}; research_capabilities?:CapabilityModel };
type Props = { view:"stocks"|"sectors"|"themes"; request:Request; presentationLevel:PresentationLevel; holdings:Holding[]; watchlist:string[]; portfolioId?:string|number|null; onWatchlistChange?:(tickers:string[])=>void };
type CollectionItem = { sector?:string; key?:string; label?:string; security_count?:number; member_count?:number; description?:string; leaders?:string[]; mapping_rule?:string };
type CollectionPayload = { sectors?:CollectionItem[]; themes?:CollectionItem[] };

const money=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(value):"—";
const compact=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(value):"—";
const percent=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?`${(Math.abs(value)<=2?value*100:value).toFixed(1)}%`:"—";
const number=(value:unknown,digits=2)=>typeof value==="number"&&Number.isFinite(value)?value.toFixed(digits):"—";
const dateLabel=(value:unknown)=>typeof value==="string"&&value?new Date(value).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):"Awaiting data";
const displayText=(value:unknown)=>typeof value==="string"&&value.trim()?value:value==null?"—":String(value);
const errorMessage=(reason:unknown,fallback:string)=>reason instanceof Error?reason.message:fallback;
const list=(value:unknown):any[]=>Array.isArray(value)?value:[];

const NULL_COPY:Record<string,string>={
  "header.founded":"Founding date is unavailable from supported sources.",
  "overview.customer.name":"Not disclosed with usable revenue concentration.",
  "overview.customer.revenue_share":"Not disclosed with usable revenue concentration.",
  "technical.resistance":"No qualifying resistance level detected.",
  "earnings.call_highlight":"Unavailable — no supported earnings-call transcript exists.",
};

function unavailable(field:ResearchField|undefined,key:string){
  if(field?.reason)return field.reason;
  if(field?.status==="PLAN_GATED")return key==="valuation.forward_pe"||key==="valuation.peg"?"Forward consensus data unavailable under current entitlement.":"Unavailable under the current data entitlement.";
  if(field?.status==="REQUIRES_CONTEXT"||key.startsWith("portfolio."))return "Select/connect a portfolio to calculate.";
  return NULL_COPY[key]||"Unavailable from currently supported evidence.";
}
function evidenceKind(value?:string){return value==="FORECAST"?"forecast":value==="OPINION"?"opinion":"fact"}
function EvidenceBadge({field}:{field?:ResearchField}){if(!field||!["AVAILABLE","STALE"].includes(field.status))return <span className="research-evidence-badge unavailable">{field?.status?.replaceAll("_"," ")||"Unavailable"}</span>;const kind=evidenceKind(field.evidence_type);return <span className={`research-evidence-badge ${kind}`}>{kind==="fact"?"Verified fact":kind==="forecast"?"Forecast":"Model output / opinion"}</span>}
function FieldDetails({field}:{field?:ResearchField}){if(!field)return null;const methodology=field.methodology;const version=methodology?.model_version||methodology?.version;return <details className="research-field-details"><summary>Source & method</summary><dl><div><dt>Status</dt><dd>{field.status?.replaceAll("_"," ")}</dd></div>{field.provider&&<div><dt>Provider</dt><dd>{field.provider}</dd></div>}{field.source_record&&<div><dt>Record</dt><dd>{field.source_record}</dd></div>}<div><dt>As of</dt><dd>{dateLabel(field.as_of)}</dd></div>{field.retrieved_at&&<div><dt>Retrieved</dt><dd>{dateLabel(field.retrieved_at)}</dd></div>}<div><dt>Freshness</dt><dd>{field.freshness_policy||"Not specified"}</dd></div>{version&&<div><dt>Version</dt><dd>{String(version)}</dd></div>}{field.formula&&<div><dt>Method</dt><dd>{field.formula}</dd></div>}{field.reason&&<div><dt>Reason</dt><dd>{field.reason}</dd></div>}{field.input_evidence?.length&&<div><dt>Inputs</dt><dd>{field.input_evidence.map(item=>item.source_record||item.metric||item.provider).filter(Boolean).join(", ")}</dd></div>}</dl>{field.source_url&&<a href={field.source_url} target="_blank" rel="noreferrer">Open source ↗</a>}</details>}
function Empty({children}:{children:ReactNode}){return <div className="research-empty">{children}</div>}
function StatusBadge({state}:{state?:SectionState}){return <span className={`research-section-status ${(state?.status||"UNAVAILABLE").toLowerCase()}`}>{state?.status||"UNAVAILABLE"}{state?` · ${Math.round(state.coverage*100)}% coverage${state.freshness_status==="STALE"?" · STALE":""}`:""}</span>}
function AskAction({ticker,section,capabilities,label}:{ticker:string;section:string;capabilities:string[];label:string}){const prompt=`${label} for ${ticker}. Use the shared Research capabilities for ${section} and cite the relevant evidence.`;const href=`/ask?ticker=${encodeURIComponent(ticker)}&research_section=${encodeURIComponent(section)}&capabilities=${encodeURIComponent(capabilities.join(","))}&prompt=${encodeURIComponent(prompt)}`;return <a className="research-ask-action" href={href}>{label} ↗</a>}
function SectionTitle({number,title,state,action}:{number:string;title:string;state?:SectionState;action?:ReactNode}){return <header className="research-section-title"><div><span>{number}</span><h2>{title}</h2></div><div>{action}<StatusBadge state={state}/></div></header>}
function MetricCard({field,label,format=(value)=>displayText(value),missing}:{field?:ResearchField;label?:string;format?:(value:any)=>string;missing?:string}){const shown=field?.status==="AVAILABLE"||field?.status==="STALE";return <article className={`research-metric ${field?.status?.toLowerCase()||"unavailable"}`}><div className="research-metric-label"><span>{label||field?.label}</span><EvidenceBadge field={field}/></div><strong>{shown?format(field.value):missing||unavailable(field,field?.key||"")}</strong>{field?.stale&&<small className="research-stale">Stale — refresh pending</small>}<FieldDetails field={field}/></article>}
function EvidenceCard({title,field,children,empty}:{title:string;field?:ResearchField;children?:ReactNode;empty?:string}){const shown=(field?.status==="AVAILABLE"||field?.status==="STALE")&&(!Array.isArray(field.value)||field.value.length>0);return <article className="research-card"><header><h3>{title}</h3><EvidenceBadge field={field}/></header>{shown?children:<Empty>{empty||unavailable(field,field?.key||"")}</Empty>}<FieldDetails field={field}/></article>}
function PriceChart({rows}:{rows:Array<{date?:string;ts?:string;close?:number;adjusted_close?:number}>}){const pointsData=rows.map(row=>({date:row.date||row.ts||"",close:Number(row.adjusted_close??row.close)})).filter(row=>Number.isFinite(row.close));if(pointsData.length<2)return <Empty>Historical price data is unavailable for this security.</Empty>;const values=pointsData.map(row=>row.close);const min=Math.min(...values),max=Math.max(...values),span=max-min||1;const points=pointsData.map((row,index)=>`${(index/(pointsData.length-1))*100},${94-((row.close-min)/span)*80}`).join(" ");return <div className="research-price-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Historical price chart"><defs><linearGradient id="researchPriceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity=".3"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#researchPriceFill)"/><polyline points={points} fill="none" stroke="currentColor" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/></svg><div><span>{dateLabel(pointsData[0].date)}</span><strong>{money(values.at(-1))}</strong><span>{dateLabel(pointsData.at(-1)?.date)}</span></div></div>}

function SecurityOverview({overview,busy,onToggleWatchlist}:{overview:Overview;busy:boolean;onToggleWatchlist:()=>void}){
  const model=overview.research_capabilities;
  const [period,setPeriod]=useState("1Y");
  if(!model||!model.fields)return <Empty>The shared Research read model is unavailable. Legacy values are intentionally not substituted.</Empty>;
  const f=(key:string)=>model.fields[key];const s=(key:string)=>model.sections[key];
  const sessions:Record<string,number>={"1D":2,"1W":6,"1M":22,"6M":126,"YTD":260,"1Y":253,"5Y":1260};const allHistory=list(f("header.price_history")?.value);const history=allHistory.slice(-sessions[period]);
  const summary=[["What does it do?","summary.what_it_does","overview"],["Is it improving?","summary.improving","health"],["Is it cheap?","summary.cheap","valuation"],["What moves it?","summary.moves","catalysts"],["What breaks it?","summary.breaks","catalysts"]];
  const segmentNames=list(f("overview.segment.name")?.value),segmentShares=list(f("overview.segment.revenue_share")?.value),segmentGrowth=list(f("overview.segment.growth")?.value);const geographyNames=list(f("overview.geography.name")?.value),geographyShares=list(f("overview.geography.revenue_share")?.value);const customerNames=list(f("overview.customer.name")?.value),customerShares=list(f("overview.customer.revenue_share")?.value);
  const periods=list(f("financial.chart.period")?.value),revenues=list(f("financial.chart.revenue")?.value),fcfs=list(f("financial.chart.fcf")?.value),grossMargins=list(f("financial.chart.gross_margin")?.value),operatingMargins=list(f("financial.chart.operating_margin")?.value);const historyRange=f("valuation.history_range")?.value||{},peerMedian=f("valuation.peer_median")?.value||{};
  const formatMultiple=(value:any)=>typeof value==="number"?`${value.toFixed(2)}×`:displayText(value);const historyDisplay=(key:string)=>key==="valuation.pe_ttm"&&historyRange?.pe_ttm?`${formatMultiple(historyRange.pe_ttm.low)} – ${formatMultiple(historyRange.pe_ttm.high)}`:"Not calculated";const ask=(section:string,capabilities:string[],label:string)=><AskAction ticker={overview.ticker} section={section} capabilities={capabilities} label={label}/>;const marketChange=f("header.daily_change")?.value;
  return <div className="unified-security-report research-dossier">
    <header className="research-company-header"><div className="research-company-copy"><span>{overview.membership.holding?"Portfolio holding":overview.membership.watchlist?"Watchlist":"Company research"}</span><h1>{displayText(f("header.ticker")?.value)} <small>{displayText(f("header.company_name")?.value)}</small></h1><p>{displayText(f("header.exchange")?.value)} · {displayText(f("header.sector")?.value)} / {displayText(f("header.industry")?.value)}</p><div className="research-price-line"><strong>{money(f("header.current_price")?.value)}</strong><b className={(marketChange||0)>=0?"good":"risk"}>{percent(marketChange)}</b>{f("header.after_hours_change")?.value!=null&&<small>After hours {percent(f("header.after_hours_change").value)}</small>}</div><small>Market data through {dateLabel(f("header.market_timestamp")?.value)} · {displayText(f("header.market_delay")?.value)}</small><div className="research-company-facts"><MetricCard field={f("header.market_cap")} label="Market cap" format={compact}/><MetricCard field={f("header.employees")} label="Employees" format={compact}/><MetricCard field={f("header.founded")} label="Founded"/><MetricCard field={f("header.headquarters")} label="Headquarters"/></div><div className="research-header-actions"><button className={overview.membership.watchlist?"secondary active":"secondary"} disabled={busy} onClick={onToggleWatchlist}>{overview.membership.watchlist?"✓ On watchlist":"＋ Add to watchlist"}</button><a className="secondary" href={`/decisions?ticker=${encodeURIComponent(overview.ticker)}&source=research`}>Draft thesis</a>{ask("header",["header.current_price","header.price_history"],"What changed?")}</div></div><div className="research-chart-card"><header><span>Price history</span><div>{Object.keys(sessions).map(value=><button key={value} className={period===value?"active":""} onClick={()=>setPeriod(value)}>{value}</button>)}</div></header><PriceChart rows={history}/><FieldDetails field={f("header.price_history")}/></div></header>
    <div className="research-page-status"><StatusBadge state={s("page")}/><span>{model.sections.page.available_fields.length} of 148 fields populated · Registry-based status</span></div>
    <section className="research-five-questions">{summary.map(([label,key,target])=>{const field=f(key);return <a key={key} href={`#${target}`}><span>{label}</span><strong>{field?.value!=null?displayText(field.value):unavailable(field,key)}</strong><EvidenceBadge field={field}/></a>})}</section>
    <nav className="research-jump-nav">{[["overview","Overview"],["health","Financial health"],["valuation","Valuation"],["earnings","Earnings"],["thesis","Thesis"],["catalysts","Catalysts & risks"],["technicals","Market data"],["ownership","Ownership"],["portfolio","Portfolio fit"],["decision","Decision"],["sources","Sources"]].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
    {overview.stage==="header"?<div className="panel research-report-skeleton research-progressive-stage" role="status"><span/><div><strong>Identity and market data are ready</strong><small>Loading financial health, valuation, and the remaining evidence independently.</small></div></div>:<>
    <section id="overview" className="research-section"><SectionTitle number="01 / Company overview" title="What the business does and how it makes money" state={s("overview")} action={ask("overview",["overview.business_description","overview.segment.name","overview.competitor"],"Compare with competitor")}/><div className="research-two-col wide-left"><EvidenceCard title="Business description" field={f("overview.business_description")}><p className="research-long-copy">{displayText(f("overview.business_description").value)}</p><div className="research-bars"><h3>Revenue segments</h3>{segmentNames.length?segmentNames.map((name,index)=><div key={`${name}-${index}`}><span>{displayText(name)}<b>{percent(segmentShares[index])}{segmentGrowth[index]!=null?` · ${percent(segmentGrowth[index])} growth`:""}</b></span><i><em style={{width:`${Math.min(100,Math.max(0,Number(segmentShares[index]||0)*(Math.abs(Number(segmentShares[index]||0))<=2?100:1)))}%`}}/></i></div>):<Empty>{unavailable(f("overview.segment.name"),"overview.segment.name")}</Empty>}<FieldDetails field={f("overview.segment.name")}/></div></EvidenceCard><div className="research-side-stack"><EvidenceCard title="Geographic exposure" field={f("overview.geography.name")}><ul>{geographyNames.map((name,index)=><li key={`${name}-${index}`}>{displayText(name)}{geographyShares[index]!=null?` · ${percent(geographyShares[index])}`:""}</li>)}</ul></EvidenceCard><EvidenceCard title="Customers" field={f("overview.customer.revenue_share")} empty={unavailable(f("overview.customer.revenue_share"),"overview.customer.revenue_share")}><ul>{customerShares.map((share,index)=><li key={index}>{displayText(customerNames[index]||"Undisclosed customer")} · {percent(share)}</li>)}</ul></EvidenceCard><EvidenceCard title="Industry & competitors" field={f("overview.competitor")}><ul>{list(f("overview.competitor").value).map(item=><li key={String(item)}>{displayText(item)}</li>)}</ul><small>{displayText(f("overview.peer_methodology")?.value)}</small></EvidenceCard></div></div></section>
    <section id="health" className="research-section"><SectionTitle number="02 / Financial health" title="Is the business actually improving?" state={s("financial_health")}/><div className="research-metric-grid">{[["financial.revenue_growth_yoy",percent],["financial.eps_growth_yoy",percent],["financial.gross_margin",percent],["financial.operating_margin",percent],["financial.free_cash_flow",compact],["financial.fcf_margin",percent],["financial.net_cash_debt",compact],["financial.share_count_change",percent],["financial.roic",percent]].map(([key,format])=><MetricCard key={key as string} field={f(key as string)} format={format as (value:any)=>string}/>)}</div><div className="research-two-col"><EvidenceCard title="Revenue & free cash flow" field={f("financial.chart.period")}><div className="research-period-table"><div><b>Period</b><b>Revenue</b><b>Free cash flow</b></div>{periods.map((item,index)=><div key={`${item?.period_end}-${index}`}><span>{item?.fiscal_period||dateLabel(item?.period_end)}</span><b>{compact(revenues[index])}</b><b>{compact(fcfs[index])}</b></div>)}</div></EvidenceCard><EvidenceCard title="Margin trend" field={f("financial.chart.period")}><div className="research-period-table"><div><b>Period</b><b>Gross</b><b>Operating</b></div>{periods.map((item,index)=><div key={`${item?.period_end}-margin-${index}`}><span>{item?.fiscal_period||dateLabel(item?.period_end)}</span><b>{percent(grossMargins[index])}</b><b>{percent(operatingMargins[index])}</b></div>)}</div></EvidenceCard></div></section>
    <section id="valuation" className="research-section"><SectionTitle number="03 / Valuation" title="Is the stock attractively priced?" state={s("valuation")} action={ask("valuation",["valuation.pe_ttm","valuation.price_to_sales","valuation.ev_ebitda","valuation.history_range","valuation.fair_value.base"],"Explain this valuation")}/><p className="research-method-note">Current multiples are deterministic. Historical analysis is shown only for P/E. Fair value is a gated model output; unsupported implied-expectations heuristics are suppressed.</p><div className="research-two-col wide-left"><EvidenceCard title="Multiples vs history and peers" field={f("valuation.pe_ttm")}><div className="research-valuation-table"><div><b>Metric</b><b>Now</b><b>Peer</b><b>History</b></div>{[["valuation.pe_ttm","pe_ttm"],["valuation.forward_pe","forward_pe"],["valuation.peg","peg"],["valuation.price_to_sales","price_to_sales"],["valuation.ev_ebitda","ev_to_ebitda"],["valuation.fcf_yield","fcf_yield"]].map(([key,peerKey])=><div key={key}><span>{f(key)?.label}</span><b>{f(key)?.value==null?unavailable(f(key),key):key.includes("yield")?percent(f(key).value):formatMultiple(f(key).value)}</b><b>{peerMedian[peerKey]==null?"Unavailable":key.includes("yield")?percent(peerMedian[peerKey]):formatMultiple(peerMedian[peerKey])}</b><b>{historyDisplay(key)}</b></div>)}</div><FieldDetails field={f("valuation.history_range")}/></EvidenceCard><div className="research-side-stack"><EvidenceCard title="Fair value scenarios" field={f("valuation.fair_value.base")}><ul><li>Bear · {money(f("valuation.fair_value.bear")?.value)}</li><li>Base · {money(f("valuation.fair_value.base")?.value)}</li><li>Bull · {money(f("valuation.fair_value.bull")?.value)}</li></ul></EvidenceCard><EvidenceCard title="What the price already assumes" field={f("valuation.implied_expectations")}><pre className="research-structured-value">{JSON.stringify(f("valuation.implied_expectations").value,null,2)}</pre></EvidenceCard></div></div></section>
    {overview.stage==="core"?<div className="panel research-report-skeleton research-progressive-stage" role="status"><span/><div><strong>Core financial and valuation evidence is ready</strong><small>Loading earnings, thesis, risks, market, ownership, portfolio, and decision evidence.</small></div></div>:<>
    <section id="earnings" className="research-section"><SectionTitle number="04 / Earnings" title="What analysts expect and how management has delivered" state={s("earnings")} action={ask("earnings",["earnings.surprise.period","earnings.surprise.revenue","earnings.surprise.eps","earnings.call_highlight"],"Explain latest earnings")}/><div className="research-two-col wide-left"><EvidenceCard title="Consensus estimates & revisions" field={f("earnings.estimate.period")} empty={unavailable(f("earnings.estimate.period"),"earnings.estimate.period")}><div className="research-period-table">{list(f("earnings.estimate.period")?.value).map((item,index)=><div key={index}><span>{displayText(item)}</span><b>{compact(list(f("earnings.estimate.revenue")?.value)[index])}</b><b>{displayText(list(f("earnings.estimate.eps")?.value)[index])}</b></div>)}</div></EvidenceCard><div className="research-side-stack"><EvidenceCard title="Reported history" field={f("earnings.surprise.period")}><ul>{list(f("earnings.surprise.period")?.value).map((item,index)=><li key={index}>{item?.fiscal_period||"Period"} {item?.fiscal_year||""}{list(f("earnings.surprise.revenue")?.value)[index]!=null?` · revenue surprise ${percent(list(f("earnings.surprise.revenue").value)[index])}`:""}</li>)}</ul></EvidenceCard><EvidenceCard title="Latest call highlights" field={f("earnings.call_highlight")} empty={unavailable(f("earnings.call_highlight"),"earnings.call_highlight")}><ul>{list(f("earnings.call_highlight").value).map((item,index)=><li key={index}>{displayText(item)}</li>)}</ul></EvidenceCard></div></div></section>
    <section id="thesis" className="research-section"><SectionTitle number="05 / Thesis" title="Bull case, bear case, and what would prove each wrong" state={s("thesis")}/><p className="research-model-disclaimer">Generated research cases are model output, not a saved belief. Nothing becomes your thesis until you explicitly confirm and save it in Decisions.</p><div className="research-cases-grid">{[["bull","thesis.bull.statement","thesis.bull_invalidation","Challenge bull case"],["bear","thesis.bear.statement","thesis.bear_invalidation","Challenge bear case"]].map(([kind,key,invalidation,action])=><article key={key} className={`research-case ${kind}`}><header><div><span>{kind} case</span><h3>{kind==="bull"?"Upside evidence":"Downside evidence"}</h3></div><EvidenceBadge field={f(key)}/></header>{list(f(key)?.value).length?<ul>{list(f(key).value).map((item,index)=><li key={index}>{displayText(item)}</li>)}</ul>:<Empty>{unavailable(f(key),key)}</Empty>}<div><strong>What would invalidate it</strong>{list(f(invalidation)?.value).length?list(f(invalidation)?.value).map((item,index)=><span key={index}>• {displayText(item)}</span>):<span>{unavailable(f(invalidation),invalidation)}</span>}</div>{ask("thesis",kind==="bull"?[key,invalidation,"thesis.bear.statement","risk.explanation","valuation.read","earnings.surprise.revenue"]:[key,invalidation,"thesis.bull.statement","catalyst.event","valuation.read","earnings.surprise.revenue"],action)}<FieldDetails field={f(key)}/></article>)}</div></section>
    <section id="catalysts" className="research-section"><SectionTitle number="06 / Catalysts & risks" title="What could move it, and what could go wrong" state={s("catalysts_risks")} action={ask("catalysts_risks",["risk.name","risk.explanation","risk.severity"],"Why is this a risk?")}/><div className="research-two-col"><EvidenceCard title="Upcoming catalysts" field={f("catalyst.event")}><ul>{list(f("catalyst.event")?.value).map((item,index)=><li key={index}>{displayText(item)}{list(f("catalyst.date")?.value)[index]?` · ${dateLabel(list(f("catalyst.date").value)[index])}`:""}</li>)}</ul></EvidenceCard><EvidenceCard title="Risk register" field={f("risk.explanation")}><strong>{displayText(f("risk.name")?.value)}</strong><p>{displayText(f("risk.explanation")?.value)}</p>{f("risk.severity")?.value&&<small>Severity: {displayText(f("risk.severity").value)}</small>}</EvidenceCard></div></section>
    <section id="technicals" className="research-section"><SectionTitle number="07 / Market & technical data" title="Trend, levels, volatility and relative performance" state={s("market_data")}/><div className="research-metric-grid">{[["technical.trend",displayText],["technical.sma_50",money],["technical.sma_200",money],["technical.support",(v:any)=>list(v).map(money).join(" / ")],["technical.resistance",(v:any)=>list(v).map(money).join(" / ")],["technical.rsi_14",(v:any)=>number(v,1)],["technical.beta",number],["technical.max_drawdown",percent]].map(([key,format])=><MetricCard key={key as string} field={f(key as string)} format={format as (value:any)=>string}/>)}</div><EvidenceCard title="Performance vs benchmarks" field={f("performance.security_1y")}><div className="research-valuation-table"><div><b>Series</b><b>3M</b><b>YTD</b><b>1Y</b></div><div><span>{overview.ticker}</span><b>{percent(f("performance.security_3m")?.value)}</b><b>{percent(f("performance.security_ytd")?.value)}</b><b>{percent(f("performance.security_1y")?.value)}</b></div><div><span>SPY</span><b>—</b><b>—</b><b>{percent(f("performance.spy")?.value)}</b></div><div><span>QQQ</span><b>—</b><b>—</b><b>{percent(f("performance.qqq")?.value)}</b></div><div><span>Sector ETF</span><b>—</b><b>—</b><b>{percent(f("performance.sector_etf")?.value)}</b></div></div></EvidenceCard></section>
    <section id="ownership" className="research-section"><SectionTitle number="08 / Ownership & sentiment" title="Who is buying, who is selling, how the market is positioned" state={s("ownership_sentiment")}/><div className="research-metric-grid">{[["ownership.institutional_percent",percent],["ownership.insider_net",displayText],["ownership.insider_count",displayText],["ownership.short_percent",percent],["ownership.short_change",percent],["ownership.days_to_cover",number],["sentiment.news_score",number],["sentiment.news_driver",displayText]].map(([key,format])=><MetricCard key={key as string} field={f(key as string)} format={format as (value:any)=>string}/>)}</div></section>
    <section id="portfolio" className="research-section"><SectionTitle number="09 / Portfolio relevance" title="What buying this would do to your portfolio" state={s("portfolio_fit")} action={ask("portfolio_fit",["portfolio.current_exposure","portfolio.correlation","portfolio.beta_before_after","portfolio.stress_test"],"Show portfolio impact")}/><div className="research-metric-grid">{[["portfolio.current_exposure",percent],["portfolio.sector_after",percent],["portfolio.highest_overlap",(v:any)=>Array.isArray(v)?`${displayText(v[0])} · ${number(v[1])} correlation`:displayText(v)],["portfolio.correlation",number],["portfolio.suggested_position",percent],["portfolio.beta_before_after",(v:any)=>v&&typeof v==="object"?`${number(v.before)} → ${number(v.after)}`:displayText(v)],["portfolio.stress_test",percent],["portfolio.opportunity_cost",percent]].map(([key,format])=><MetricCard key={key as string} field={f(key as string)} format={format as (value:any)=>string}/>)}</div></section>
    <section id="decision" className="research-section"><SectionTitle number="10 / Decision summary" title="The call, and what would change it" state={s("decision")}/><article className="research-decision-card"><div className="research-decision-lead"><span>Current research state</span><strong>{displayText(f("decision.rating")?.value)}</strong><small>Confidence {displayText(f("decision.confidence")?.value)}</small><EvidenceBadge field={f("decision.rating")}/><FieldDetails field={f("decision.rating")}/></div><div className="research-decision-facts"><MetricCard field={f("decision.entry")} format={(v)=>list(v).map(money).join(" – ")}/><MetricCard field={f("decision.invalidation")}/><MetricCard field={f("decision.next_review")} format={dateLabel}/></div><div className="research-decision-theses">{[["Bull thesis","decision.bull_thesis"],["Bear thesis","decision.bear_thesis"],["Key catalyst","decision.key_catalyst"],["Primary risk","decision.primary_risk"]].map(([label,key])=><p key={key}><span>{label}</span>{f(key)?.value!=null?Array.isArray(f(key).value)?f(key).value.join(" "):displayText(f(key).value):unavailable(f(key),key)}</p>)}</div><footer>Model output is decision support, not investment advice.</footer></article></section>
    <section id="sources" className="research-section"><SectionTitle number="11 / Data freshness & sources" title="Where every figure on this page came from" state={s("sources")}/><div className="research-source-grid">{[["Verified filings","sources.verified.provider","sources.verified.as_of"],["Market data","sources.market.provider","sources.market.delay"],["Model output","sources.model.version","sources.model.methodology"]].map(([label,key,detail])=><EvidenceCard key={key} title={label} field={f(key)}><strong>{displayText(f(key)?.value)}</strong><small>{displayText(f(detail)?.value)}</small></EvidenceCard>)}</div><div className="research-legend"><EvidenceBadge field={{evidence_type:"VERIFIED_FACT",status:"AVAILABLE"} as ResearchField}/><span>Direct source or deterministic calculation</span><EvidenceBadge field={{evidence_type:"FORECAST",status:"AVAILABLE"} as ResearchField}/><span>Provider forecast</span><EvidenceBadge field={{evidence_type:"OPINION",status:"AVAILABLE"} as ResearchField}/><span>Versioned model interpretation</span></div></section>
    </>}
    </>}
  </div>;
}

export function ResearchDiscovery({view,request,holdings,watchlist,portfolioId,onWatchlistChange}:Props){
  const deepLinkedTicker=typeof window==="undefined"?"":new URL(window.location.href).searchParams.get("ticker")?.toUpperCase()||"";const [query,setQuery]=useState(deepLinkedTicker);const [selected,setSelected]=useState(deepLinkedTicker);const [overview,setOverview]=useState<Overview|null>(null);const [membership,setMembership]=useState<"holdings"|"watchlist">("holdings");const [localWatchlist,setLocalWatchlist]=useState(watchlist);const [loading,setLoading]=useState(Boolean(deepLinkedTicker));const [watchlistBusy,setWatchlistBusy]=useState(false);const [error,setError]=useState("");const [collection,setCollection]=useState<CollectionPayload|null>(null);const activeRequest=useRef(0);const abortRef=useRef<AbortController|null>(null);
  useEffect(()=>setLocalWatchlist(watchlist),[watchlist]);
  async function loadOverview(raw:string){const search=raw.trim();if(!search)return;const requestId=++activeRequest.current;abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;setLoading(true);setError("");let headerShown=false;try{let ticker=search.toUpperCase();if(!/^[A-Z][A-Z0-9.-]{0,9}$/.test(ticker)){const searchResponse=await request(`/research/search?q=${encodeURIComponent(search)}&limit=1`,{signal:controller.signal});if(!searchResponse.ok)throw new Error("No supported company matched that search.");const searchPayload=await searchResponse.json();ticker=searchPayload.results?.[0]?.ticker||"";}if(!ticker)throw new Error("No supported company matched that search.");const params=portfolioId?`?portfolio_id=${encodeURIComponent(String(portfolioId))}`:"";const headerResponse=await request(`/research/security/${encodeURIComponent(ticker)}/header${params}`,{signal:controller.signal});if(!headerResponse.ok){const body=await headerResponse.json().catch(()=>({}));throw new Error(body.detail||"Company research is unavailable.");}const header=await headerResponse.json();if(requestId!==activeRequest.current)return;headerShown=true;setSelected(ticker);setQuery(ticker);setOverview(header);setLoading(false);const sectionHash=window.location.hash;window.history.replaceState({},"",`/research?ticker=${encodeURIComponent(ticker)}${sectionHash}`);if(header.stage==="full")return;const coreTask=request(`/research/security/${encodeURIComponent(ticker)}/core${params}`,{signal:controller.signal});const fullTask=request(`/research/security/${encodeURIComponent(ticker)}/overview${params}`,{signal:controller.signal});const coreResponse=await coreTask;if(!coreResponse.ok){const body=await coreResponse.json().catch(()=>({}));throw new Error(body.detail||"Core Research evidence is unavailable.");}const core=await coreResponse.json();if(requestId!==activeRequest.current)return;setOverview({...core,stage:"core"});await new Promise<void>(resolve=>window.requestAnimationFrame(()=>resolve()));const response=await fullTask;if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||"Detailed Research evidence is unavailable.");}const data=await response.json();if(requestId!==activeRequest.current)return;setOverview({...data,stage:"full"});if(sectionHash)window.requestAnimationFrame(()=>document.querySelector(sectionHash)?.scrollIntoView({behavior:"smooth",block:"start"}));}catch(reason){if(controller.signal.aborted||requestId!==activeRequest.current)return;setError(errorMessage(reason,"Company research is unavailable."));if(!headerShown)setOverview(null);}finally{if(requestId===activeRequest.current)setLoading(false);}}
  useEffect(()=>{if(deepLinkedTicker)void loadOverview(deepLinkedTicker);return()=>abortRef.current?.abort();},[]);useEffect(()=>{if(view==="stocks")return;let active=true;const task=window.setTimeout(()=>{if(!active)return;setLoading(true);request(view==="sectors"?"/research/sectors":"/research/themes").then(async response=>{if(!response.ok)throw new Error("Research collection unavailable");const data=await response.json();if(active)setCollection(data);}).catch(reason=>{if(active)setError(errorMessage(reason,"Research collection unavailable"));}).finally(()=>{if(active)setLoading(false);});},0);return()=>{active=false;window.clearTimeout(task);};},[view,request]);
  async function toggleWatchlist(){if(!overview||watchlistBusy)return;const ticker=overview.ticker;const removing=overview.membership.watchlist;const previous=[...localWatchlist];const next=removing?previous.filter(item=>item!==ticker):Array.from(new Set([...previous,ticker]));setWatchlistBusy(true);setLocalWatchlist(next);setOverview({...overview,membership:{...overview.membership,watchlist:!removing}});onWatchlistChange?.(next);try{const response=await request(`/watchlist/${encodeURIComponent(ticker)}`,{method:removing?"DELETE":"PUT"});if(!response.ok)throw new Error("Watchlist update failed");const result=await response.json();setLocalWatchlist(result.tickers);onWatchlistChange?.(result.tickers);}catch(reason){setLocalWatchlist(previous);setOverview(current=>current?{...current,membership:{...current.membership,watchlist:removing}}:current);onWatchlistChange?.(previous);setError(errorMessage(reason,"Watchlist update failed"));}finally{setWatchlistBusy(false);}}
  if(view!=="stocks"){const items=view==="sectors"?collection?.sectors:collection?.themes;return <section className="workspace research-collection"><div className="section-intro"><div><span className="kicker">More research</span><h2>{view==="sectors"?"Sector coverage":"Theme coverage"}</h2><p>Browse the disclosed stored universe, then open a company in the main Research workspace.</p></div></div>{error&&<div className="warning-strip">{error}</div>}<div className="compact-research-table">{(items||[]).map(item=><article key={item.sector||item.key}><strong>{item.sector||item.label}</strong><span>{item.security_count??item.member_count??0} securities</span><small>{item.description||item.leaders?.join(", ")||item.mapping_rule}</small></article>)}</div>{loading&&<p className="report-loading"><span/>Loading stored coverage…</p>}</section>;}
  const symbols=membership==="holdings"?holdings.map(item=>item.ticker):localWatchlist;const unique=Array.from(new Set(symbols.map(item=>item.trim().toUpperCase()).filter(item=>item&&item!=="CASH")));const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();void loadOverview(query);};
  return <section className="workspace unified-research-workspace"><header className="unified-research-header"><div><span className="kicker">Company research</span><h1>One clear view of the evidence.</h1><p>Every displayed result comes from the shared Research capability model used by Ask EagleEyes.</p></div></header><form className="unified-research-search" onSubmit={submit}><label><span>Stock, ETF, or company</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="AAPL or Apple" autoComplete="off"/></label><button type="submit" className="primary" disabled={loading||!query.trim()}>{loading?"Loading saved research…":"Open research →"}</button></form><div className="research-collection-bar"><div role="tablist" aria-label="Research lists"><button className={membership==="holdings"?"active":""} onClick={()=>setMembership("holdings")}>Holdings <span>{holdings.length}</span></button><button className={membership==="watchlist"?"active":""} onClick={()=>setMembership("watchlist")}>Watchlist <span>{localWatchlist.length}</span></button></div><div>{unique.length?unique.map(ticker=><button key={ticker} className={selected===ticker?"selected":""} onClick={()=>void loadOverview(ticker)}>{ticker}</button>):<span>{membership==="holdings"?"No saved holdings yet.":"Your watchlist is empty."}</span>}</div></div>{error&&<div className="warning-strip"><span>{error}</span><button onClick={()=>void loadOverview(query)}>Retry</button></div>}{loading&&<div className="panel research-report-skeleton" role="status"><span/><div><strong>Loading cached company evidence</strong><small>Superseded searches are cancelled automatically.</small></div></div>}{!loading&&overview&&<SecurityOverview overview={overview} busy={watchlistBusy} onToggleWatchlist={()=>void toggleWatchlist()}/>} {!loading&&!overview&&!error&&<div className="panel research-start-state"><span>◎</span><h2>Choose a holding or search a company.</h2><p>Available evidence appears immediately; unsupported fields remain explicit.</p></div>}</section>;
}
